Repository jdf2e/nutui-react, pull requests merged in 2024-02, with the labels that each got.

#1921 docs(tabbar): 文档可读性优化
  src/packages/popover/popover.taro.tsx
  src/packages/tabbar/demo.taro.tsx
  src/packages/tabbar/demo.tsx
  src/packages/tabbar/doc.en-US.md
  src/packages/tabbar/doc.md
  src/packages/tabbar/doc.taro.md
  src/packages/tabbar/doc.zh-TW.md
Labels: size/L

#1922 fix: rtl模式下左右方向箭头的处理
  src/packages/audio/audio.scss
  src/packages/avatar/demo.scss
  src/packages/avatarcropper/demo.taro.tsx
  src/packages/avatarcropper/demo.tsx
  src/packages/button/button.scss
  src/packages/calendarcard/calendarcard.scss
  src/packages/cell/demo.scss
  src/packages/cell/demo.taro.tsx
  src/packages/cell/demo.tsx
  src/packages/fixednav/fixednav.scss
  src/packages/navbar/navbar.scss
  src/packages/pagination/pagination.scss
  src/packages/popup/popup.scss
  src/packages/searchbar/searchbar.scss
  src/packages/swiper/demo.scss
  src/sites/mobile/App.scss
  src/sites/mobile/App.tsx
  src/sites/mobile/Links.scss
Labels: size/L

#1912 fix(input): controlled mode, content clearing does not work
  src/packages/input/__test__/__snapshots__/input.spec.tsx.snap
  src/packages/input/__test__/input.spec.tsx
  src/packages/input/demo.taro.tsx
  src/packages/input/doc.taro.md
  src/packages/input/input.taro.tsx
  src/packages/input/input.tsx
Labels: size/L

#1926 fix(rtl): 修复文本 margin
  src/packages/cell/demo.scss
  src/packages/cell/demo.taro.tsx
  src/packages/cell/demo.tsx
  src/packages/checkbox/demo.taro.tsx
  src/packages/checkbox/demo.tsx
  src/packages/checkboxgroup/checkboxgroup.scss
  src/packages/divider/demo.taro.tsx
  src/packages/divider/demo.tsx
  src/packages/elevator/demo.taro.tsx
  src/packages/elevator/demo.tsx
  src/packages/image/demo.taro.tsx
  src/packages/image/demo.tsx
  src/packages/indicator/demo.taro.tsx
  src/packages/indicator/demo.tsx
  src/packages/sticky/demo.taro.tsx
  src/packages/sticky/demo.tsx
  src/packages/swipe/demo.taro.tsx
  src/packages/swipe/demo.tsx
  src/packages/watermark/demo.taro.tsx
  src/packages/watermark/demo.tsx
Labels: size/L

#1927 feat: 生成用于 rtl 校对的 css 文件
  scripts/generate-css-for-rtl-comparison.js
Labels: size/M

#1929 fix(tabs): 修订左对齐样式
  src/packages/tabs/tabs.scss
  src/packages/tabs/tabs.taro.tsx
Labels: size/M

#1928 fix(sticky): 适配taro
  src/packages/sticky/sticky.taro.tsx
Labels: size/XS

#1940 chore: update renovate.json
  .github/renovate.json
Labels: size/XS

#1930 feat(shortpassword): support ref for form
  src/packages/shortpassword/_test_/index.spec.tsx
  src/packages/shortpassword/shortpassword.taro.tsx
  src/packages/shortpassword/shortpassword.tsx
  src/packages/shortpassword/types.ts
Labels: size/L

#1935 docs(tabs): 文档可读性优化
  src/packages/tabs/demo.taro.tsx
  src/packages/tabs/demo.tsx
  src/packages/tabs/doc.en-US.md
  src/packages/tabs/doc.md
  src/packages/tabs/doc.taro.md
  src/packages/tabs/doc.zh-TW.md
Labels: size/XXL

#1937 feat(form): support renderProps
  src/packages/form/__tests__/form.spec.tsx
  src/packages/form/demo.taro.tsx
  src/packages/form/demo.tsx
  src/packages/form/doc.en-US.md
  src/packages/form/doc.md
  src/packages/form/doc.taro.md
  src/packages/form/doc.zh-TW.md
  src/packages/form/useform.taro.ts
  src/packages/form/useform.ts
  src/packages/formitem/formitem.taro.tsx
  src/packages/formitem/formitem.tsx
Labels: size/XL

#1942 fix(barrage): 解决新增弹幕重叠问题+不同宽度弹幕滚动速度不一致问题+重构taro版本
  src/packages/barrage/__tests__/barrage.spec.tsx
  src/packages/barrage/barrage.scss
  src/packages/barrage/barrage.taro.tsx
  src/packages/barrage/barrage.tsx
  src/packages/barrage/demo.taro.tsx
  src/packages/barrage/demo.tsx
Labels: size/L

#1931 fix(popover): can not be closed
  src/packages/popup/popup.scss
Labels: size/XS

#1955 fix(form): validateFields support promise
  src/packages/form/useform.taro.ts
Labels: size/XS

#1943 feat(inputnumber): support allow empty
  src/packages/inputnumber/__tests__/inputnumber.spec.tsx
  src/packages/inputnumber/demo.taro.tsx
  src/packages/inputnumber/demo.tsx
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/inputnumber/inputnumber.tsx
Labels: size/XL

#1966 fix(elevator): 解决部分安卓手机右侧导航高亮偏差问题
  src/packages/elevator/elevator.tsx
Labels: size/XS

#1960 fix(elevator): 修复增加页码的逻辑
  src/packages/elevator/elevator.tsx
Labels: size/XS

#1964 docs: 修复文档
  src/packages/dialog/doc.en-US.md
  src/packages/dialog/doc.md
  src/packages/dialog/doc.taro.md
  src/packages/dialog/doc.zh-TW.md
  src/packages/empty/doc.en-US.md
  src/packages/empty/doc.md
  src/packages/empty/doc.taro.md
  src/packages/empty/doc.zh-TW.md
  src/packages/rate/doc.en-US.md
  src/packages/rate/doc.md
  src/packages/rate/doc.taro.md
  src/packages/rate/doc.zh-TW.md
Labels: size/L

#1965 feat(inputnumber): 小程序新增软键盘类型
  src/packages/inputnumber/doc.md
  src/packages/inputnumber/doc.taro.md
  src/packages/inputnumber/doc.zh-TW.md
  src/packages/inputnumber/inputnumber.taro.tsx
Labels: size/S
