Repository jdf2e/nutui-react, pull requests merged in 2024-08, with the labels that each got.

#2507 fix(uploader): correct xhrBeforeUpload execution timing
  src/packages/uploader/upload.ts
Labels: size/XS

#2508 refactor(numberkeyboard): optimize code & correct defaultProps
  src/packages/numberkeyboard/numberkeyboard.taro.tsx
  src/packages/numberkeyboard/numberkeyboard.tsx
Labels: size/L

#2492 feat(form): Form.Item 增加 align 属性
  src/packages/form/demos/h5/demo1.tsx
  src/packages/form/demos/taro/demo1.tsx
  src/packages/form/doc.en-US.md
  src/packages/form/doc.md
  src/packages/form/doc.taro.md
  src/packages/form/doc.zh-TW.md
  src/packages/formitem/formitem.taro.tsx
  src/packages/formitem/formitem.tsx
Labels: size/S

#2509 fix(inputNumber): correct onChange, onOverlimit event triggering timing when async & sync
  src/packages/inputnumber/__tests__/inputnumber.spec.tsx
  src/packages/inputnumber/demos/h5/demo3.tsx
  src/packages/inputnumber/demos/h5/demo8.tsx
  src/packages/inputnumber/demos/taro/demo3.tsx
  src/packages/inputnumber/demos/taro/demo8.tsx
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/inputnumber/inputnumber.tsx
Labels: size/L

#2488 feat(menu): menu-item 组件增加标题icon自定义方式
  src/packages/menu/demos/h5/demo6.tsx
  src/packages/menu/demos/taro/demo6.tsx
  src/packages/menu/doc.en-US.md
  src/packages/menu/doc.md
  src/packages/menu/doc.taro.md
  src/packages/menu/doc.zh-TW.md
  src/packages/menu/menu.taro.tsx
  src/packages/menu/menu.tsx
  src/packages/menuitem/menuitem.taro.tsx
  src/packages/menuitem/menuitem.tsx
Labels: size/L

#2514 docs(readme): fix dir => pnpm run dev:taro:weapp、 pnpm run dev:taro:jd
  README.md
Labels: size/XS

#2519 feat(image-preview): 增加索引字段，用于预览内容排序
  src/packages/imagepreview/demos/h5/demo6.tsx
  src/packages/imagepreview/demos/taro/demo6.tsx
  src/packages/imagepreview/doc.en-US.md
  src/packages/imagepreview/doc.md
  src/packages/imagepreview/doc.taro.md
  src/packages/imagepreview/doc.zh-TW.md
  src/packages/imagepreview/imagepreview.taro.tsx
  src/packages/imagepreview/imagepreview.tsx
Labels: size/L

#2526 fix(uploader): sizeType prop didnot work when weapp || jd
  src/packages/uploader/uploader.taro.tsx
Labels: size/XS

#2528 chore(form): correct form methods usage of demo
  src/packages/form/demos/h5/demo3.tsx
  src/packages/form/demos/taro/demo3.tsx
Labels: size/M

#2325 feat(progress): 四端适配
  src/config.json
  src/packages/progress/demo.taro.tsx
  src/packages/progress/demo.tsx
  src/packages/progress/demos/h5/demo1.tsx
  src/packages/progress/demos/h5/demo2.tsx
  src/packages/progress/demos/h5/demo3.tsx
  src/packages/progress/demos/h5/demo4.tsx
  src/packages/progress/demos/h5/demo8.tsx
  src/packages/progress/demos/taro/demo1.tsx
  src/packages/progress/demos/taro/demo2.tsx
  src/packages/progress/demos/taro/demo3.tsx
  src/packages/progress/demos/taro/demo4.tsx
  src/packages/progress/demos/taro/demo6.tsx
  src/packages/progress/demos/taro/demo7.tsx
  src/packages/progress/demos/taro/demo8.tsx
  src/packages/progress/progress.harmony.css
  src/packages/progress/progress.scss
  src/packages/progress/progress.taro.tsx
  src/packages/progress/progress.tsx
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/L

#2550 fix(uploader): ios 下无法回显的问题修复
  src/packages/uploader/preview.tsx
Labels: size/XS

#2538 fix(PullToRefresh): 修复PullToRefresh组件disabled属性在taro中无效的问题
  src/packages/pulltorefresh/demo.taro.tsx
  src/packages/pulltorefresh/demos/taro/demo4.tsx
  src/packages/pulltorefresh/pulltorefresh.taro.tsx
Labels: size/M

#2553 fix(uploader): beforeUpload should trigger every time before uploading
  src/packages/uploader/__tests__/uploader.spec.tsx
  src/packages/uploader/demos/h5/demo1.tsx
  src/packages/uploader/uploader.tsx
Labels: size/S

#2527 feat(cell): add clickable prop to support click style feedback
  src/packages/cell/cell.scss
  src/packages/cell/cell.taro.tsx
  src/packages/cell/cell.tsx
  src/packages/cell/demos/h5/demo1.tsx
  src/packages/cell/demos/taro/demo1.tsx
  src/packages/cell/doc.en-US.md
  src/packages/cell/doc.md
  src/packages/cell/doc.taro.md
  src/packages/cell/doc.zh-TW.md
Labels: size/M

#2554 fix(tabs.taro.tsx): 解决在不需要滚动的时候，切换tab产生tab位置错乱的问题
  src/packages/tabs/tabs.taro.tsx
Labels: size/XS
