Repository jdf2e/nutui-react, pull requests merged in 2024-03, with the labels that each got.

#1950 refactor(docs): 文档支持通过标签使用已有的 demo 代码
  package.json
  packages/nutui-taro-demo/config/index.js
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
  scripts/copy-docs-h5-or-taro.js
  src/packages/button/demo.taro.tsx
  src/packages/button/demo.tsx
  src/packages/button/demos/h5/demo1.tsx
  src/packages/button/demos/h5/demo2.tsx
  src/packages/button/demos/h5/demo3.tsx
  src/packages/button/demos/h5/demo4.tsx
  src/packages/button/demos/h5/demo5.tsx
  src/packages/button/demos/h5/demo6.tsx
  src/packages/button/demos/h5/demo7.tsx
  src/packages/button/demos/h5/demo8.tsx
  src/packages/button/demos/h5/demo9.tsx
  src/packages/button/demos/taro/demo1.tsx
  src/packages/button/demos/taro/demo10.tsx
  src/packages/button/demos/taro/demo2.tsx
  src/packages/button/demos/taro/demo3.tsx
  src/packages/button/demos/taro/demo4.tsx
  src/packages/button/demos/taro/demo5.tsx
  src/packages/button/demos/taro/demo6.tsx
  src/packages/button/demos/taro/demo7.tsx
  src/packages/button/demos/taro/demo8.tsx
  src/packages/button/demos/taro/demo9.tsx
  src/packages/button/doc.en-US.md
  src/packages/button/doc.md
  src/packages/button/doc.taro.md
  src/packages/button/doc.zh-TW.md
  src/packages/icon/doc.en-US.md
  src/packages/pagination/doc.en-US.md
  src/packages/pagination/doc.md
  src/packages/pagination/doc.taro.md
  src/packages/sticky/doc.taro.md
  src/sites/doc/App.tsx
  src/sites/doc/components/demoblock/codeblock.tsx
  src/sites/doc/context.ts
  src/sites/doc/router.ts
  tsconfig.json
  vite.config.build.site.ts
  vite.config.ts
Labels: size/XXL

#1949 refactor: adjust build target to ES6, reduce size of configprovider
  tsconfig.json
  vite.config.build.disperse.taro.ts
  vite.config.build.disperse.ts
Labels: size/S

#1970 chore(ci): update workflows
  .github/workflows/realease-tag.yml
  .github/workflows/sync-gitee.yml
  .github/workflows/sync-h5.yml
  .github/workflows/sync-migrate.yml
  .github/workflows/sync-taro.yml
Labels: size/S

#1958 chore(dev): development mode, remove duplicate CSS stylesheets
  src/sites/mobile/Links.scss
  src/sites/mobile/Links.tsx
  src/sites/mobile/main.tsx
  src/styles/variables-jmapp.scss
  vite.config.build.site.ts
  vite.config.ts
Labels: size/M

#1961 feat(rtl): support progress & range
  src/packages/configprovider/configprovider.taro.tsx
  src/packages/configprovider/configprovider.tsx
  src/packages/configprovider/index.taro.ts
  src/packages/configprovider/index.ts
  src/packages/progress/progress.taro.tsx
  src/packages/progress/progress.tsx
  src/packages/range/range.taro.tsx
  src/packages/range/range.tsx
Labels: size/M

#1971 chore: remove CSS logic conflicting with MDX
  vite.config.ts
Labels: size/XS

#1959 fix(inputnumber): provide finalValue
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/inputnumber/inputnumber.tsx
Labels: size/XS

#1974 chore: 构建 demo 要定义 __PROJECTID__
  vite.config.build.site.ts
Labels: size/XS

#1972 feat(noticebar): supports the center layout
  src/packages/noticebar/__test__/__snapshots__/noticebar.spec.tsx.snap
  src/packages/noticebar/__test__/noticebar.spec.tsx
  src/packages/noticebar/demo.taro.tsx
  src/packages/noticebar/demo.tsx
  src/packages/noticebar/doc.en-US.md
  src/packages/noticebar/doc.md
  src/packages/noticebar/doc.taro.md
  src/packages/noticebar/doc.zh-TW.md
  src/packages/noticebar/index.ts
  src/packages/noticebar/noticebar.scss
  src/packages/noticebar/noticebar.taro.tsx
  src/packages/noticebar/noticebar.tsx
  src/packages/noticebar/types.ts
Labels: size/L

#1978 feat(dialog): support bottom close button
  src/packages/dialog/config.ts
  src/packages/dialog/demo.taro.tsx
  src/packages/dialog/demo.tsx
  src/packages/dialog/dialog.scss
  src/packages/dialog/doc.en-US.md
  src/packages/dialog/doc.md
  src/packages/dialog/doc.taro.md
  src/packages/dialog/doc.zh-TW.md
  src/packages/dialog/index.ts
Labels: size/L

#1979 fix: dts 插件升级导致构建产物路径错误
  package.json
  pnpm-lock.yaml
Labels: size/S

#1984 feat(rtl): noticebar
  src/packages/noticebar/noticebar.taro.tsx
  src/packages/noticebar/noticebar.tsx
Labels: size/XS

#1982 feat(rtl): table
  src/packages/table/table.taro.tsx
  src/packages/table/table.tsx
  src/packages/table/useTableSticky.ts
Labels: size/S

#1981 feat(rtl): collapse
  src/packages/collapse/doc.en-US.md
  src/packages/collapse/doc.md
  src/packages/collapse/doc.taro.md
  src/packages/collapse/doc.zh-TW.md
  src/packages/collapseitem/collapseitem.scss
  src/styles/variables.scss
Labels: size/S

#1986 feat(rtl): badge
  src/packages/badge/badge.taro.tsx
  src/packages/badge/badge.tsx
Labels: size/S

#1985 feat(animatingNumbers): support rtl
  src/packages/animatingnumbers/countup.scss
  vite.config.ts
Labels: size/XS

#1988 feat(empty): 图片变更
  src/packages/empty/__test__/empty.spec.tsx
  src/packages/empty/demo.taro.tsx
  src/packages/empty/demo.tsx
  src/packages/empty/doc.en-US.md
  src/packages/empty/doc.md
  src/packages/empty/doc.taro.md
  src/packages/empty/doc.zh-TW.md
Labels: size/L

#1992 fix(badge): the text set by value unwrap
  src/packages/badge/badge.scss
  src/packages/badge/doc.en-US.md
  src/packages/badge/doc.md
  src/packages/badge/doc.taro.md
  src/packages/badge/doc.zh-TW.md
Labels: size/S

#1957 feat(checkbox): list model
  src/packages/checkbox/__test__/checkbox.spec.tsx
  src/packages/checkbox/checkbox.scss
  src/packages/checkbox/checkbox.taro.tsx
  src/packages/checkbox/checkbox.tsx
  src/packages/checkbox/demo.taro.tsx
  src/packages/checkbox/demo.tsx
  src/packages/checkbox/doc.en-US.md
  src/packages/checkbox/doc.md
  src/packages/checkbox/doc.taro.md
  src/packages/checkbox/doc.zh-TW.md
  src/packages/checkboxgroup/checkboxgroup.scss
  src/packages/checkboxgroup/checkboxgroup.taro.tsx
  src/packages/checkboxgroup/checkboxgroup.tsx
  src/packages/checkboxgroup/context.ts
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
  vite.config.ts
Labels: size/L

#1977 feat(popover): 增加light和dark模式的区分
  src/packages/popover/demo.taro.tsx
  src/packages/popover/demo.tsx
  src/packages/popover/index.taro.ts
  src/packages/popover/index.ts
  src/packages/popover/popover.scss
  src/packages/popover/popover.taro.tsx
  src/packages/popover/popover.tsx
  src/packages/popover/types.ts
  src/packages/tour/tour.taro.tsx
  src/packages/tour/tour.tsx
Labels: size/L

#1994 fix(toast): 变更 taro下的属性 msg 为 content，增加 taro 下 demo
  src/packages/form/demo.taro.tsx
  src/packages/icon/demo.taro.tsx
  src/packages/inputnumber/demo.taro.tsx
  src/packages/numberkeyboard/demo.taro.tsx
  src/packages/progress/demo.taro.tsx
  src/packages/pulltorefresh/demo.taro.tsx
  src/packages/range/demo.taro.tsx
  src/packages/searchbar/demo.taro.tsx
  src/packages/swipe/demo.taro.tsx
  src/packages/table/demo.taro.tsx
  src/packages/toast/demo.taro.tsx
  src/packages/toast/doc.md
  src/packages/toast/doc.taro.md
  src/packages/toast/toast.taro.tsx
Labels: size/M

#1995 feat(Dialog): added custom content area demo
  src/packages/dialog/demo.taro.tsx
  src/packages/dialog/demo.tsx
  src/packages/dialog/doc.en-US.md
  src/packages/dialog/doc.md
  src/packages/dialog/doc.taro.md
  src/packages/dialog/doc.zh-TW.md
Labels: size/L

#1975 chore(deps): bump typescript v5
  package.json
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
  src/packages/calendar/__tests__/calendar.spec.tsx
  src/packages/countdown/countdown.taro.tsx
  src/packages/countdown/countdown.tsx
  src/packages/datepicker/datepicker.taro.tsx
  src/packages/datepicker/datepicker.tsx
  src/packages/form/useform.taro.ts
  src/packages/form/useform.ts
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/inputnumber/inputnumber.tsx
  src/packages/swiper/swiper.tsx
  src/packages/uploader/uploader.taro.tsx
  src/packages/uploader/uploader.tsx
Labels: size/L

#1969 fix: tabs 小程序滚动操作问题
  src/packages/tabs/tabs.taro.tsx
Labels: size/S

#1997 docs(tabs): fix typo
  src/packages/tabs/doc.en-US.md
Labels: size/XS

#1983 feat(dialog): support confirm button loading effect
  src/packages/dialog/__test__/dialog.spec.tsx
  src/packages/dialog/config.ts
  src/packages/dialog/confirm.tsx
  src/packages/dialog/demo.taro.tsx
  src/packages/dialog/demo.tsx
  src/packages/dialog/dialog.taro.tsx
  src/packages/dialog/dialog.tsx
  src/packages/dialog/doc.en-US.md
  src/packages/dialog/doc.md
  src/packages/dialog/doc.taro.md
Labels: size/L

#1996 feat(Swipe): 增加自定义高度的demo
  src/packages/swipe/demo.taro.tsx
  src/packages/swipe/demo.tsx
  src/packages/swipe/doc.en-US.md
  src/packages/swipe/doc.md
  src/packages/swipe/doc.taro.md
  src/packages/swipe/doc.zh-TW.md
  src/packages/swipe/swipe.scss
Labels: size/XL

#1993 fix(virtuallist): 修复 vitrual list 组件 Taro 下获取窗口高度不正确的问题
  src/packages/virtuallist/virtuallist.taro.tsx
Labels: size/S

#1999 fix(toast): add deprecated prop msg
  src/packages/toast/toast.taro.tsx
Labels: size/S

#1998 fix(cell): unify the demos of Cell
  src/packages/cell/demo.taro.tsx
  src/packages/cell/demo.tsx
  src/packages/cell/demos/h5/demo1.tsx
  src/packages/cell/demos/h5/demo2.tsx
  src/packages/cell/demos/h5/demo3.tsx
  src/packages/cell/demos/h5/demo4.tsx
  src/packages/cell/demos/h5/demo5.tsx
  src/packages/cell/demos/h5/demo6.tsx
  src/packages/cell/demos/h5/demo7.tsx
  src/packages/cell/demos/taro/demo1.tsx
  src/packages/cell/demos/taro/demo2.tsx
  src/packages/cell/demos/taro/demo3.tsx
  src/packages/cell/demos/taro/demo4.tsx
  src/packages/cell/demos/taro/demo5.tsx
  src/packages/cell/demos/taro/demo6.tsx
  src/packages/cell/demos/taro/demo7.tsx
  src/packages/cell/doc.en-US.md
  src/packages/cell/doc.md
  src/packages/cell/doc.taro.md
  src/packages/cell/doc.zh-TW.md
Labels: size/XXL

#2002 fix: 构建站点主题变量未成功引入
  src/sites/mobile/main.tsx
  vite.config.build.site.ts
  vite.config.ts
Labels: size/S

#2004 feat(tabs): rtl
  src/packages/address/__test__/__snapshots__/address.spec.tsx.snap
  src/packages/cascader/__tests__/__snapshots__/cascader.spec.tsx.snap
  src/packages/tabs/demo.taro.tsx
  src/packages/tabs/tabs.taro.tsx
  src/packages/tabs/tabs.tsx
Labels: size/M

#2006 fix(badge): 修复value传入0时显示不正确的问题
  src/packages/badge/badge.taro.tsx
  src/packages/badge/badge.tsx
Labels: size/XS

#2005 fix(configProvidder): demo拆解与自动替换脚本&configProvider规范统一
  packages/nutui-taro-demo/config/index.js
  scripts/doc-demo-extract-replace.js
  src/packages/configprovider/demo.taro.tsx
  src/packages/configprovider/demo.tsx
  src/packages/configprovider/demos/h5/demo1.tsx
  src/packages/configprovider/demos/h5/demo2.tsx
  src/packages/configprovider/demos/h5/demo3.tsx
  src/packages/configprovider/demos/h5/demo4.tsx
  src/packages/configprovider/demos/h5/demo5.tsx
  src/packages/configprovider/demos/taro/demo1.tsx
  src/packages/configprovider/demos/taro/demo2.tsx
  src/packages/configprovider/demos/taro/demo3.tsx
  src/packages/configprovider/demos/taro/demo4.tsx
  src/packages/configprovider/demos/taro/demo5.tsx
  src/packages/configprovider/doc.en-US.md
  src/packages/configprovider/doc.md
  src/packages/configprovider/doc.taro.md
  src/packages/configprovider/doc.zh-TW.md
  src/sites/doc/components/demoblock/codeblock.tsx
  src/sites/doc/components/demoblock/demoblock.tsx
  src/sites/doc/components/demoblock/index.ts
  tsconfig.json
  vite.config.build.site.ts
  vite.config.ts
Labels: size/XL

#2009 fix(calendarcard): 选择范围时支持仅选择单个日期
  src/packages/calendarcard/__tests__/calendarcard.spec.tsx
  src/packages/calendarcard/calendarcard.scss
  src/packages/calendarcard/calendarcard.taro.tsx
  src/packages/calendarcard/calendarcard.tsx
Labels: size/M

#2014 fix(grid): demo拆解与规范
  src/packages/grid/demo.taro.tsx
  src/packages/grid/demo.tsx
  src/packages/grid/demos/h5/demo1.tsx
  src/packages/grid/demos/h5/demo10.tsx
  src/packages/grid/demos/h5/demo2.tsx
  src/packages/grid/demos/h5/demo3.tsx
  src/packages/grid/demos/h5/demo4.tsx
  src/packages/grid/demos/h5/demo5.tsx
  src/packages/grid/demos/h5/demo6.tsx
  src/packages/grid/demos/h5/demo7.tsx
  src/packages/grid/demos/h5/demo8.tsx
  src/packages/grid/demos/h5/demo9.tsx
  src/packages/grid/demos/taro/demo1.tsx
  src/packages/grid/demos/taro/demo10.tsx
  src/packages/grid/demos/taro/demo2.tsx
  src/packages/grid/demos/taro/demo3.tsx
  src/packages/grid/demos/taro/demo4.tsx
  src/packages/grid/demos/taro/demo5.tsx
  src/packages/grid/demos/taro/demo6.tsx
  src/packages/grid/demos/taro/demo7.tsx
  src/packages/grid/demos/taro/demo8.tsx
  src/packages/grid/demos/taro/demo9.tsx
  src/packages/grid/doc.en-US.md
  src/packages/grid/doc.md
  src/packages/grid/doc.taro.md
  src/packages/grid/doc.zh-TW.md
Labels: size/XXL

#2013 fix(divider): demo拆解与规范
  src/packages/divider/demo.taro.tsx
  src/packages/divider/demo.tsx
  src/packages/divider/demos/h5/demo1.tsx
  src/packages/divider/demos/h5/demo2.tsx
  src/packages/divider/demos/h5/demo3.tsx
  src/packages/divider/demos/h5/demo4.tsx
  src/packages/divider/demos/h5/demo5.tsx
  src/packages/divider/demos/h5/demo6.tsx
  src/packages/divider/demos/taro/demo1.tsx
  src/packages/divider/demos/taro/demo2.tsx
  src/packages/divider/demos/taro/demo3.tsx
  src/packages/divider/demos/taro/demo4.tsx
  src/packages/divider/demos/taro/demo5.tsx
  src/packages/divider/demos/taro/demo6.tsx
  src/packages/divider/doc.en-US.md
  src/packages/divider/doc.md
  src/packages/divider/doc.taro.md
  src/packages/divider/doc.zh-TW.md
Labels: size/XL

#2012 fix(overlay): demo拆解与规范
  src/packages/overlay/demo.taro.tsx
  src/packages/overlay/demo.tsx
  src/packages/overlay/demos/h5/demo1.tsx
  src/packages/overlay/demos/h5/demo2.tsx
  src/packages/overlay/demos/h5/demo3.tsx
  src/packages/overlay/demos/h5/demo4.tsx
  src/packages/overlay/demos/h5/demo5.tsx
  src/packages/overlay/demos/h5/demo6.tsx
  src/packages/overlay/demos/taro/demo1.tsx
  src/packages/overlay/demos/taro/demo2.tsx
  src/packages/overlay/demos/taro/demo3.tsx
  src/packages/overlay/demos/taro/demo4.tsx
  src/packages/overlay/demos/taro/demo5.tsx
  src/packages/overlay/demos/taro/demo6.tsx
  src/packages/overlay/doc.en-US.md
  src/packages/overlay/doc.md
  src/packages/overlay/doc.taro.md
  src/packages/overlay/doc.zh-TW.md
Labels: size/XXL

#2011 fix(Image): demo拆解与规范
  src/packages/image/demo.taro.tsx
  src/packages/image/demo.tsx
  src/packages/image/demos/h5/demo1.tsx
  src/packages/image/demos/h5/demo2.tsx
  src/packages/image/demos/h5/demo3.tsx
  src/packages/image/demos/h5/demo4.tsx
  src/packages/image/demos/h5/demo5.tsx
  src/packages/image/demos/h5/demo6.tsx
  src/packages/image/demos/h5/demo7.tsx
  src/packages/image/demos/h5/demo8.tsx
  src/packages/image/demos/taro/demo1.tsx
  src/packages/image/demos/taro/demo2.tsx
  src/packages/image/demos/taro/demo3.tsx
  src/packages/image/demos/taro/demo4.tsx
  src/packages/image/demos/taro/demo5.tsx
  src/packages/image/demos/taro/demo6.tsx
  src/packages/image/demos/taro/demo7.tsx
  src/packages/image/demos/taro/demo8.tsx
  src/packages/image/doc.en-US.md
  src/packages/image/doc.md
  src/packages/image/doc.taro.md
  src/packages/image/doc.zh-TW.md
Labels: size/XXL

#2010 fix(icon): demo拆解与规范
  scripts/doc-demo-extract-replace.js
  src/packages/icon/demo.taro.tsx
  src/packages/icon/demo.tsx
  src/packages/icon/demos/h5/demo1.tsx
  src/packages/icon/demos/h5/demo2.tsx
  src/packages/icon/demos/h5/demo3.tsx
  src/packages/icon/demos/h5/demo4.tsx
  src/packages/icon/demos/h5/demo5.tsx
  src/packages/icon/demos/taro/demo1.tsx
  src/packages/icon/demos/taro/demo2.tsx
  src/packages/icon/demos/taro/demo3.tsx
  src/packages/icon/demos/taro/demo4.tsx
  src/packages/icon/demos/taro/demo5.tsx
  src/packages/icon/doc.en-US.md
  src/packages/icon/doc.md
  src/packages/icon/doc.taro.md
  src/packages/icon/doc.zh-TW.md
Labels: size/XL

#2016 fix(layout): demo拆解与规范 & 修复脚本在不同操作系统的正则匹配出错
  scripts/doc-demo-extract-replace.js
  src/packages/layout/demo.taro.tsx
  src/packages/layout/demo.tsx
  src/packages/layout/demos/h5/demo1.tsx
  src/packages/layout/demos/h5/demo2.tsx
  src/packages/layout/demos/h5/demo3.tsx
  src/packages/layout/demos/taro/demo1.tsx
  src/packages/layout/demos/taro/demo2.tsx
  src/packages/layout/demos/taro/demo3.tsx
  src/packages/layout/doc.en-US.md
  src/packages/layout/doc.md
  src/packages/layout/doc.taro.md
  src/packages/layout/doc.zh-TW.md
Labels: size/XXL

#2021 fix(space): demo拆解与规范
  src/packages/cell/demo.taro.tsx
  src/packages/cell/demo.tsx
  src/packages/space/demo.taro.tsx
  src/packages/space/demo.tsx
  src/packages/space/demos/h5/demo1.tsx
  src/packages/space/demos/h5/demo2.tsx
  src/packages/space/demos/h5/demo3.tsx
  src/packages/space/demos/h5/demo4.tsx
  src/packages/space/demos/h5/demo5.tsx
  src/packages/space/demos/h5/demo6.tsx
  src/packages/space/demos/taro/demo1.tsx
  src/packages/space/demos/taro/demo2.tsx
  src/packages/space/demos/taro/demo3.tsx
  src/packages/space/demos/taro/demo4.tsx
  src/packages/space/demos/taro/demo5.tsx
  src/packages/space/demos/taro/demo6.tsx
  src/packages/space/doc.en-US.md
  src/packages/space/doc.md
  src/packages/space/doc.taro.md
  src/packages/space/doc.zh-TW.md
Labels: size/XXL

#2020 docs(SafeArea): 调整demo
  src/packages/button/demo.taro.tsx
  src/packages/button/demo.tsx
  src/packages/safearea/demo.taro.tsx
  src/packages/safearea/demo.tsx
  src/packages/safearea/demos/h5/demo1.tsx
  src/packages/safearea/demos/taro/demo1.tsx
  src/packages/safearea/doc.en-US.md
  src/packages/safearea/doc.md
  src/packages/safearea/doc.taro.md
  src/packages/safearea/doc.zh-TW.md
Labels: size/L

#2023 docs(inputnumber): 修改docs
  src/packages/inputnumber/demo.taro.tsx
  src/packages/inputnumber/demo.tsx
  src/packages/inputnumber/demos/h5/demo1.tsx
  src/packages/inputnumber/demos/h5/demo2.tsx
  src/packages/inputnumber/demos/h5/demo3.tsx
  src/packages/inputnumber/demos/h5/demo4.tsx
  src/packages/inputnumber/demos/h5/demo5.tsx
  src/packages/inputnumber/demos/h5/demo6.tsx
  src/packages/inputnumber/demos/h5/demo7.tsx
  src/packages/inputnumber/demos/h5/demo8.tsx
  src/packages/inputnumber/demos/h5/demo9.tsx
  src/packages/inputnumber/demos/taro/demo1.tsx
  src/packages/inputnumber/demos/taro/demo2.tsx
  src/packages/inputnumber/demos/taro/demo3.tsx
  src/packages/inputnumber/demos/taro/demo4.tsx
  src/packages/inputnumber/demos/taro/demo5.tsx
  src/packages/inputnumber/demos/taro/demo6.tsx
  src/packages/inputnumber/demos/taro/demo7.tsx
  src/packages/inputnumber/demos/taro/demo8.tsx
  src/packages/inputnumber/demos/taro/demo9.tsx
  src/packages/inputnumber/doc.en-US.md
  src/packages/inputnumber/doc.md
  src/packages/inputnumber/doc.taro.md
  src/packages/inputnumber/doc.zh-TW.md
Labels: size/XXL

#2019 style(button): jmapp style
  package.json
  src/packages/button/button.scss
  src/packages/button/button.taro.tsx
  src/packages/button/button.tsx
  src/packages/button/doc.en-US.md
  src/packages/button/doc.md
  src/packages/button/doc.taro.md
  src/packages/button/doc.zh-TW.md
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/M

#2028 fix(ellipsis): 修复设置行数超过内容高度时只显示一行内容的问题
  src/packages/ellipsis/ellipsis.taro.tsx
Labels: size/S

#2017 fix: fix swipe slide element get rect null, get width error
  src/packages/swipe/swipe.taro.tsx
Labels: size/XS

#2025 fix(backtop): demo拆解与规范
  src/packages/backtop/demo.taro.tsx
  src/packages/backtop/demo.tsx
  src/packages/backtop/demos/h5/demo1.tsx
  src/packages/backtop/demos/h5/demo2.tsx
  src/packages/backtop/demos/h5/demo3.tsx
  src/packages/backtop/demos/h5/demo4.tsx
  src/packages/backtop/demos/h5/demo5.tsx
  src/packages/backtop/demos/taro/demo1.tsx
  src/packages/backtop/demos/taro/demo2.tsx
  src/packages/backtop/demos/taro/demo3.tsx
  src/packages/backtop/demos/taro/demo4.tsx
  src/packages/backtop/doc.en-US.md
  src/packages/backtop/doc.md
  src/packages/backtop/doc.taro.md
  src/packages/backtop/doc.zh-TW.md
Labels: size/XL

#2029 fix(range): touchmove 回调中 rect 获取失败时终止
  src/packages/range/range.taro.tsx
Labels: size/XS

#2027 feat(infiniteloading): add type props
  src/packages/infiniteloading/__tests__/__snapshots__/infiniteloading.spec.tsx.snap
  src/packages/infiniteloading/demo.scss
  src/packages/infiniteloading/demo.tsx
  src/packages/infiniteloading/doc.en-US.md
  src/packages/infiniteloading/doc.md
  src/packages/infiniteloading/doc.taro.md
  src/packages/infiniteloading/doc.zh-TW.md
  src/packages/infiniteloading/index.ts
  src/packages/infiniteloading/infiniteloading.scss
  src/packages/infiniteloading/infiniteloading.taro.tsx
  src/packages/infiniteloading/infiniteloading.tsx
  src/packages/infiniteloading/types.ts
Labels: size/L

#2031 feat(ci): add issue-close.yml
  .github/workflows/issue-close.yml
Labels: size/S

#2037 feat(Button): 增加xlarge,按钮内图标大小追随按钮当前字号
  src/packages/button/button.scss
  src/packages/button/button.taro.tsx
  src/packages/button/button.tsx
  src/packages/button/demo.taro.tsx
  src/packages/button/demo.tsx
  src/packages/button/demos/h5/demo3.tsx
  src/packages/button/demos/h5/demo4.tsx
  src/packages/button/demos/h5/demo7.tsx
  src/packages/button/demos/taro/demo4.tsx
  src/packages/button/demos/taro/demo5.tsx
  src/packages/button/demos/taro/demo8.tsx
  src/packages/button/doc.en-US.md
  src/packages/button/doc.md
  src/packages/button/doc.taro.md
  src/packages/button/doc.zh-TW.md
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/L

#2038 fix(build): 移除构建产物中重复的类型文件
  package.json
  tsconfig.json
Labels: size/XS

#2043 docs(popover): 调整demo
  src/packages/popover/demo.taro.tsx
  src/packages/popover/demo.tsx
  src/packages/popover/demos/h5/demo1.tsx
  src/packages/popover/demos/h5/demo2.tsx
  src/packages/popover/demos/h5/demo3.tsx
  src/packages/popover/demos/h5/demo4.tsx
  src/packages/popover/demos/h5/demo5.tsx
  src/packages/popover/demos/h5/demo6.tsx
  src/packages/popover/demos/h5/demo7.tsx
  src/packages/popover/demos/h5/demo8.tsx
  src/packages/popover/demos/taro/demo1.tsx
  src/packages/popover/demos/taro/demo2.tsx
  src/packages/popover/demos/taro/demo3.tsx
  src/packages/popover/demos/taro/demo4.tsx
  src/packages/popover/demos/taro/demo5.tsx
  src/packages/popover/demos/taro/demo6.tsx
  src/packages/popover/doc.en-US.md
  src/packages/popover/doc.md
  src/packages/popover/doc.taro.md
  src/packages/popover/doc.zh-TW.md
Labels: size/XXL

#2032 fix(Empty): 调整默认图片为jd图片
  src/packages/empty/__test__/__snapshots__/empty.spec.tsx.snap
  src/packages/empty/__test__/empty.spec.tsx
  src/packages/empty/demo.taro.tsx
  src/packages/empty/demo.tsx
  src/packages/empty/demos/h5/demo1.tsx
  src/packages/empty/demos/h5/demo2.tsx
  src/packages/empty/demos/h5/demo3.tsx
  src/packages/empty/demos/h5/demo4.tsx
  src/packages/empty/demos/h5/demo5.tsx
  src/packages/empty/demos/h5/demo6.tsx
  src/packages/empty/demos/taro/demo1.tsx
  src/packages/empty/demos/taro/demo2.tsx
  src/packages/empty/demos/taro/demo3.tsx
  src/packages/empty/demos/taro/demo4.tsx
  src/packages/empty/demos/taro/demo5.tsx
  src/packages/empty/demos/taro/demo6.tsx
  src/packages/empty/doc.en-US.md
  src/packages/empty/doc.md
  src/packages/empty/doc.taro.md
  src/packages/empty/doc.zh-TW.md
  src/packages/empty/empty.taro.tsx
  src/packages/empty/empty.tsx
Labels: size/XXL

#2042 feat(badge): 新增 fill 属性
  src/packages/badge/__test__/badge.spec.tsx
  src/packages/badge/badge.scss
  src/packages/badge/badge.taro.tsx
  src/packages/badge/badge.tsx
  src/packages/badge/demo.taro.tsx
  src/packages/badge/demo.tsx
  src/packages/badge/doc.en-US.md
  src/packages/badge/doc.md
  src/packages/badge/doc.taro.md
  src/packages/badge/doc.zh-TW.md
  src/packages/badge/index.taro.ts
  src/packages/badge/index.ts
  src/packages/tabbar/__tests__/__snapshots__/tabbar.spec.tsx.snap
Labels: size/L

#2033 fix(switch):switch组件demo代码重构。
  src/packages/switch/demo.taro.tsx
  src/packages/switch/demo.tsx
  src/packages/switch/demos/h5/demo1.tsx
  src/packages/switch/demos/h5/demo2.tsx
  src/packages/switch/demos/h5/demo3.tsx
  src/packages/switch/demos/h5/demo4.tsx
  src/packages/switch/demos/h5/demo5.tsx
  src/packages/switch/demos/h5/demo6.tsx
  src/packages/switch/demos/taro/demo1.tsx
  src/packages/switch/demos/taro/demo2.tsx
  src/packages/switch/demos/taro/demo3.tsx
  src/packages/switch/demos/taro/demo4.tsx
  src/packages/switch/demos/taro/demo5.tsx
  src/packages/switch/demos/taro/demo6.tsx
  src/packages/switch/doc.en-US.md
  src/packages/switch/doc.md
  src/packages/switch/doc.taro.md
  src/packages/switch/doc.zh-TW.md
Labels: size/XL

#2030 fix(elevator): demo拆解与规范
  src/packages/elevator/demo.taro.tsx
  src/packages/elevator/demo.tsx
  src/packages/elevator/demos/h5/demo1.tsx
  src/packages/elevator/demos/h5/demo2.tsx
  src/packages/elevator/demos/h5/demo3.tsx
  src/packages/elevator/demos/h5/demo4.tsx
  src/packages/elevator/demos/h5/demo5.tsx
  src/packages/elevator/demos/taro/demo1.tsx
  src/packages/elevator/demos/taro/demo2.tsx
  src/packages/elevator/demos/taro/demo3.tsx
  src/packages/elevator/demos/taro/demo4.tsx
  src/packages/elevator/demos/taro/demo5.tsx
  src/packages/elevator/doc.en-US.md
  src/packages/elevator/doc.md
  src/packages/elevator/doc.taro.md
  src/packages/elevator/doc.zh-TW.md
Labels: size/XXL

#2044 feat(PullToRefresh): 增加 type 属性，支持深色背景设置
  src/packages/pulltorefresh/demo.taro.tsx
  src/packages/pulltorefresh/demo.tsx
  src/packages/pulltorefresh/demos/h5/demo1.tsx
  src/packages/pulltorefresh/demos/h5/demo2.tsx
  src/packages/pulltorefresh/demos/taro/demo1.tsx
  src/packages/pulltorefresh/demos/taro/demo2.tsx
  src/packages/pulltorefresh/demos/taro/demo3.tsx
  src/packages/pulltorefresh/doc.en-US.md
  src/packages/pulltorefresh/doc.md
  src/packages/pulltorefresh/doc.taro.md
  src/packages/pulltorefresh/doc.zh-TW.md
  src/packages/pulltorefresh/index.taro.ts
  src/packages/pulltorefresh/index.ts
  src/packages/pulltorefresh/pulltorefresh.scss
  src/packages/pulltorefresh/pulltorefresh.taro.tsx
  src/packages/pulltorefresh/pulltorefresh.tsx
  src/packages/pulltorefresh/types.ts
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/XL

#2054 chore(row): 优化 className
  src/packages/row/row.taro.tsx
  src/packages/row/row.tsx
Labels: size/S

#2058 fix(sideNavBar): demo拆解与规范
  src/packages/sidenavbar/demo.taro.tsx
  src/packages/sidenavbar/demo.tsx
  src/packages/sidenavbar/demos/h5/demo1.tsx
  src/packages/sidenavbar/demos/h5/demo2.tsx
  src/packages/sidenavbar/demos/taro/demo1.tsx
  src/packages/sidenavbar/demos/taro/demo2.tsx
  src/packages/sidenavbar/doc.en-US.md
  src/packages/sidenavbar/doc.md
  src/packages/sidenavbar/doc.taro.md
  src/packages/sidenavbar/doc.zh-TW.md
Labels: size/XXL

#2048 fix(fixedNav): demo拆解与规范
  src/packages/fixednav/demo.taro.tsx
  src/packages/fixednav/demo.tsx
  src/packages/fixednav/demos/h5/demo1.tsx
  src/packages/fixednav/demos/h5/demo2.tsx
  src/packages/fixednav/demos/h5/demo3.tsx
  src/packages/fixednav/demos/h5/demo4.tsx
  src/packages/fixednav/demos/h5/demo5.tsx
  src/packages/fixednav/demos/taro/demo1.tsx
  src/packages/fixednav/demos/taro/demo2.tsx
  src/packages/fixednav/demos/taro/demo3.tsx
  src/packages/fixednav/demos/taro/demo4.tsx
  src/packages/fixednav/demos/taro/demo5.tsx
  src/packages/fixednav/doc.en-US.md
  src/packages/fixednav/doc.md
  src/packages/fixednav/doc.taro.md
  src/packages/fixednav/doc.zh-TW.md
Labels: size/XXL

#2050 fix(icon): 处理 rtl 部分。
  src/packages/icon/demo.scss
  src/packages/icon/demo.taro.tsx
  src/packages/icon/demo.tsx
  src/packages/icon/demos/h5/demo6.tsx
  src/packages/icon/demos/h5/demo7.tsx
  src/packages/icon/demos/taro/demo6.tsx
  src/packages/icon/demos/taro/demo7.tsx
Labels: size/L

#2024 fix(sticky): demo拆解与规范
  src/packages/sticky/demo.taro.tsx
  src/packages/sticky/demo.tsx
  src/packages/sticky/demos/h5/demo1.tsx
  src/packages/sticky/demos/h5/demo2.tsx
  src/packages/sticky/demos/h5/demo3.tsx
  src/packages/sticky/demos/h5/demo4.tsx
  src/packages/sticky/demos/taro/demo1.tsx
  src/packages/sticky/demos/taro/demo2.tsx
  src/packages/sticky/demos/taro/demo3.tsx
  src/packages/sticky/demos/taro/demo4.tsx
  src/packages/sticky/doc.en-US.md
  src/packages/sticky/doc.md
  src/packages/sticky/doc.taro.md
  src/packages/sticky/doc.zh-TW.md
Labels: size/XL

#2051 feat(backtop): rtl
  src/packages/backtop/backtop.taro.tsx
  src/packages/backtop/backtop.tsx
  src/packages/badge/badge.taro.tsx
  src/packages/badge/badge.tsx
Labels: size/S

#2045 fix(rate): demo拆解与规范
  src/packages/rate/demo.taro.tsx
  src/packages/rate/demo.tsx
  src/packages/rate/demos/h5/demo1.tsx
  src/packages/rate/demos/h5/demo10.tsx
  src/packages/rate/demos/h5/demo11.tsx
  src/packages/rate/demos/h5/demo12.tsx
  src/packages/rate/demos/h5/demo2.tsx
  src/packages/rate/demos/h5/demo3.tsx
  src/packages/rate/demos/h5/demo4.tsx
  src/packages/rate/demos/h5/demo5.tsx
  src/packages/rate/demos/h5/demo6.tsx
  src/packages/rate/demos/h5/demo7.tsx
  src/packages/rate/demos/h5/demo8.tsx
  src/packages/rate/demos/h5/demo9.tsx
  src/packages/rate/demos/taro/demo1.tsx
  src/packages/rate/demos/taro/demo10.tsx
  src/packages/rate/demos/taro/demo11.tsx
  src/packages/rate/demos/taro/demo12.tsx
  src/packages/rate/demos/taro/demo2.tsx
  src/packages/rate/demos/taro/demo3.tsx
  src/packages/rate/demos/taro/demo4.tsx
  src/packages/rate/demos/taro/demo5.tsx
  src/packages/rate/demos/taro/demo6.tsx
  src/packages/rate/demos/taro/demo7.tsx
  src/packages/rate/demos/taro/demo8.tsx
  src/packages/rate/demos/taro/demo9.tsx
  src/packages/rate/doc.en-US.md
  src/packages/rate/doc.md
  src/packages/rate/doc.taro.md
  src/packages/rate/doc.zh-TW.md
Labels: size/XXL

#2059 fix(tabbar): demo拆解与规范&脚本增强
  scripts/doc-demo-extract-replace.js
  src/packages/tabbar/demo.taro.tsx
  src/packages/tabbar/demo.tsx
  src/packages/tabbar/demos/h5/demo1.tsx
  src/packages/tabbar/demos/h5/demo2.tsx
  src/packages/tabbar/demos/h5/demo3.tsx
  src/packages/tabbar/demos/h5/demo4.tsx
  src/packages/tabbar/demos/h5/demo5.tsx
  src/packages/tabbar/demos/h5/demo6.tsx
  src/packages/tabbar/demos/h5/demo7.tsx
  src/packages/tabbar/demos/h5/demo8.tsx
  src/packages/tabbar/demos/h5/demo9.tsx
  src/packages/tabbar/demos/taro/demo1.tsx
  src/packages/tabbar/demos/taro/demo2.tsx
  src/packages/tabbar/demos/taro/demo3.tsx
  src/packages/tabbar/demos/taro/demo4.tsx
  src/packages/tabbar/demos/taro/demo5.tsx
  src/packages/tabbar/demos/taro/demo6.tsx
  src/packages/tabbar/demos/taro/demo7.tsx
  src/packages/tabbar/demos/taro/demo8.tsx
  src/packages/tabbar/demos/taro/demo9.tsx
  src/packages/tabbar/doc.en-US.md
  src/packages/tabbar/doc.md
  src/packages/tabbar/doc.taro.md
  src/packages/tabbar/doc.zh-TW.md
Labels: size/XXL

#2068 fix(address): demo拆解与规范
  src/packages/address/demo.taro.tsx
  src/packages/address/demo.tsx
  src/packages/address/demos/h5/demo1.tsx
  src/packages/address/demos/h5/demo2.tsx
  src/packages/address/demos/h5/demo3.tsx
  src/packages/address/demos/h5/demo4.tsx
  src/packages/address/demos/h5/demo5.tsx
  src/packages/address/demos/h5/demo6.tsx
  src/packages/address/demos/taro/demo1.tsx
  src/packages/address/demos/taro/demo2.tsx
  src/packages/address/demos/taro/demo3.tsx
  src/packages/address/demos/taro/demo4.tsx
  src/packages/address/demos/taro/demo5.tsx
  src/packages/address/demos/taro/demo6.tsx
  src/packages/address/doc.en-US.md
  src/packages/address/doc.md
  src/packages/address/doc.taro.md
  src/packages/address/doc.zh-TW.md
Labels: size/XXL

#2071 fix(avatar): demo规范与调整
  src/packages/avatar/demo.taro.tsx
  src/packages/avatar/demo.tsx
  src/packages/avatar/demos/h5/demo1.tsx
  src/packages/avatar/demos/h5/demo2.tsx
  src/packages/avatar/demos/h5/demo3.tsx
  src/packages/avatar/demos/h5/demo4.tsx
  src/packages/avatar/demos/h5/demo5.tsx
  src/packages/avatar/demos/h5/demo6.tsx
  src/packages/avatar/demos/h5/demo7.tsx
  src/packages/avatar/demos/h5/demo8.tsx
  src/packages/avatar/demos/h5/demo9.tsx
  src/packages/avatar/demos/taro/demo1.tsx
  src/packages/avatar/demos/taro/demo2.tsx
  src/packages/avatar/demos/taro/demo3.tsx
  src/packages/avatar/demos/taro/demo4.tsx
  src/packages/avatar/demos/taro/demo5.tsx
  src/packages/avatar/demos/taro/demo6.tsx
  src/packages/avatar/demos/taro/demo7.tsx
  src/packages/avatar/demos/taro/demo8.tsx
  src/packages/avatar/demos/taro/demo9.tsx
  src/packages/avatar/doc.en-US.md
  src/packages/avatar/doc.md
  src/packages/avatar/doc.taro.md
  src/packages/avatar/doc.zh-TW.md
Labels: size/XXL

#2064 fix(SearchBar): demo拆解与规范
  src/packages/searchbar/demo.taro.tsx
  src/packages/searchbar/demo.tsx
  src/packages/searchbar/demos/h5/demo1.tsx
  src/packages/searchbar/demos/h5/demo2.tsx
  src/packages/searchbar/demos/h5/demo3.tsx
  src/packages/searchbar/demos/h5/demo4.tsx
  src/packages/searchbar/demos/h5/demo5.tsx
  src/packages/searchbar/demos/h5/demo6.tsx
  src/packages/searchbar/demos/h5/demo7.tsx
  src/packages/searchbar/demos/taro/demo1.tsx
  src/packages/searchbar/demos/taro/demo2.tsx
  src/packages/searchbar/demos/taro/demo3.tsx
  src/packages/searchbar/demos/taro/demo4.tsx
  src/packages/searchbar/demos/taro/demo5.tsx
  src/packages/searchbar/demos/taro/demo6.tsx
  src/packages/searchbar/demos/taro/demo7.tsx
  src/packages/searchbar/doc.en-US.md
  src/packages/searchbar/doc.md
  src/packages/searchbar/doc.taro.md
  src/packages/searchbar/doc.zh-TW.md
Labels: size/XXL

#2075 fix(trendarrow): demo拆解与规范
  src/packages/trendarrow/demo.taro.tsx
  src/packages/trendarrow/demo.tsx
  src/packages/trendarrow/demos/h5/demo1.tsx
  src/packages/trendarrow/demos/h5/demo2.tsx
  src/packages/trendarrow/demos/h5/demo3.tsx
  src/packages/trendarrow/demos/h5/demo4.tsx
  src/packages/trendarrow/demos/h5/demo5.tsx
  src/packages/trendarrow/demos/h5/demo6.tsx
  src/packages/trendarrow/demos/h5/demo7.tsx
  src/packages/trendarrow/demos/h5/demo8.tsx
  src/packages/trendarrow/demos/taro/demo1.tsx
  src/packages/trendarrow/demos/taro/demo2.tsx
  src/packages/trendarrow/demos/taro/demo3.tsx
  src/packages/trendarrow/demos/taro/demo4.tsx
  src/packages/trendarrow/demos/taro/demo5.tsx
  src/packages/trendarrow/demos/taro/demo6.tsx
  src/packages/trendarrow/demos/taro/demo7.tsx
  src/packages/trendarrow/demos/taro/demo8.tsx
  src/packages/trendarrow/doc.en-US.md
  src/packages/trendarrow/doc.md
  src/packages/trendarrow/doc.taro.md
  src/packages/trendarrow/doc.zh-TW.md
Labels: size/XXL

#2060 fix(badge): demo拆解与规范
  src/packages/badge/demo.taro.tsx
  src/packages/badge/demo.tsx
  src/packages/badge/demos/h5/demo1.tsx
  src/packages/badge/demos/h5/demo2.tsx
  src/packages/badge/demos/h5/demo3.tsx
  src/packages/badge/demos/h5/demo4.tsx
  src/packages/badge/demos/h5/demo5.tsx
  src/packages/badge/demos/h5/demo6.tsx
  src/packages/badge/demos/h5/demo7.tsx
  src/packages/badge/demos/h5/demo8.tsx
  src/packages/badge/demos/taro/demo1.tsx
  src/packages/badge/demos/taro/demo2.tsx
  src/packages/badge/demos/taro/demo3.tsx
  src/packages/badge/demos/taro/demo4.tsx
  src/packages/badge/demos/taro/demo5.tsx
  src/packages/badge/demos/taro/demo6.tsx
  src/packages/badge/demos/taro/demo7.tsx
  src/packages/badge/demos/taro/demo8.tsx
  src/packages/badge/doc.en-US.md
  src/packages/badge/doc.md
  src/packages/badge/doc.taro.md
  src/packages/badge/doc.zh-TW.md
Labels: size/XXL

#2047 fix(skeleton): demo拆解与规范
  src/packages/skeleton/demo.taro.tsx
  src/packages/skeleton/demo.tsx
  src/packages/skeleton/demos/h5/demo1.tsx
  src/packages/skeleton/demos/h5/demo2.tsx
  src/packages/skeleton/demos/h5/demo3.tsx
  src/packages/skeleton/demos/h5/demo4.tsx
  src/packages/skeleton/demos/h5/demo5.tsx
  src/packages/skeleton/demos/taro/demo1.tsx
  src/packages/skeleton/demos/taro/demo2.tsx
  src/packages/skeleton/demos/taro/demo3.tsx
  src/packages/skeleton/demos/taro/demo4.tsx
  src/packages/skeleton/demos/taro/demo5.tsx
  src/packages/skeleton/doc.en-US.md
  src/packages/skeleton/doc.md
  src/packages/skeleton/doc.taro.md
  src/packages/skeleton/doc.zh-TW.md
Labels: size/XL

#2079 fix(pagination): demo拆解与规范
  src/packages/pagination/demo.taro.tsx
  src/packages/pagination/demo.tsx
  src/packages/pagination/demos/h5/demo1.tsx
  src/packages/pagination/demos/h5/demo2.tsx
  src/packages/pagination/demos/h5/demo3.tsx
  src/packages/pagination/demos/h5/demo4.tsx
  src/packages/pagination/demos/h5/demo5.tsx
  src/packages/pagination/demos/h5/demo6.tsx
  src/packages/pagination/demos/taro/demo1.tsx
  src/packages/pagination/demos/taro/demo2.tsx
  src/packages/pagination/demos/taro/demo3.tsx
  src/packages/pagination/demos/taro/demo4.tsx
  src/packages/pagination/demos/taro/demo5.tsx
  src/packages/pagination/demos/taro/demo6.tsx
  src/packages/pagination/doc.en-US.md
  src/packages/pagination/doc.md
  src/packages/pagination/doc.taro.md
  src/packages/pagination/doc.zh-TW.md
Labels: size/XXL

#2082 fix(price): demo拆解与规范
  src/packages/price/demo.taro.tsx
  src/packages/price/demo.tsx
  src/packages/price/demos/h5/demo1.tsx
  src/packages/price/demos/h5/demo2.tsx
  src/packages/price/demos/h5/demo3.tsx
  src/packages/price/demos/h5/demo4.tsx
  src/packages/price/demos/h5/demo5.tsx
  src/packages/price/demos/h5/demo6.tsx
  src/packages/price/demos/h5/demo7.tsx
  src/packages/price/demos/h5/demo8.tsx
  src/packages/price/demos/taro/demo1.tsx
  src/packages/price/demos/taro/demo2.tsx
  src/packages/price/demos/taro/demo3.tsx
  src/packages/price/demos/taro/demo4.tsx
  src/packages/price/demos/taro/demo5.tsx
  src/packages/price/demos/taro/demo6.tsx
  src/packages/price/demos/taro/demo7.tsx
  src/packages/price/demos/taro/demo8.tsx
  src/packages/price/doc.en-US.md
  src/packages/price/doc.md
  src/packages/price/doc.taro.md
  src/packages/price/doc.zh-TW.md
Labels: size/XL

#2055 fix(navBar): demo拆解与规范
  src/packages/navbar/demo.scss
  src/packages/navbar/demo.taro.tsx
  src/packages/navbar/demo.tsx
  src/packages/navbar/demos/h5/demo1.tsx
  src/packages/navbar/demos/h5/demo2.tsx
  src/packages/navbar/demos/h5/demo3.tsx
  src/packages/navbar/demos/taro/demo1.tsx
  src/packages/navbar/demos/taro/demo2.tsx
  src/packages/navbar/demos/taro/demo3.tsx
  src/packages/navbar/doc.en-US.md
  src/packages/navbar/doc.md
  src/packages/navbar/doc.taro.md
  src/packages/navbar/doc.zh-TW.md
Labels: size/XXL

#2080 fix: update copy-docs-h5-or-taro.js
  scripts/copy-docs-h5-or-taro.js
Labels: size/XS

#2061 fix(Swiper): rtl
  src/packages/swiper/swiper.tsx
Labels: size/XS

#2072 fix(Card): demo拆解与规范
  src/packages/card/demo.taro.tsx
  src/packages/card/demo.tsx
  src/packages/card/demos/h5/demo1.tsx
  src/packages/card/demos/h5/demo2.tsx
  src/packages/card/demos/h5/demo3.tsx
  src/packages/card/demos/h5/demo4.tsx
  src/packages/card/demos/h5/demo5.tsx
  src/packages/card/demos/taro/demo1.tsx
  src/packages/card/demos/taro/demo2.tsx
  src/packages/card/demos/taro/demo3.tsx
  src/packages/card/demos/taro/demo4.tsx
  src/packages/card/demos/taro/demo5.tsx
  src/packages/card/doc.en-US.md
  src/packages/card/doc.md
  src/packages/card/doc.taro.md
  src/packages/card/doc.zh-TW.md
Labels: size/XXL

#2063 fix(calendarcard): 修复受控模式
  src/packages/calendarcard/calendarcard.taro.tsx
  src/packages/calendarcard/calendarcard.tsx
Labels: size/M

#2083 fix(watermark): demo拆解与规范
  src/packages/watermark/demo.taro.tsx
  src/packages/watermark/demo.tsx
  src/packages/watermark/demos/h5/demo1.tsx
  src/packages/watermark/demos/h5/demo2.tsx
  src/packages/watermark/demos/taro/demo1.tsx
  src/packages/watermark/demos/taro/demo2.tsx
  src/packages/watermark/doc.en-US.md
  src/packages/watermark/doc.md
  src/packages/watermark/doc.taro.md
  src/packages/watermark/doc.zh-TW.md
Labels: size/L

#2069 fix(dialog): demo拆解与规范
  src/packages/dialog/demo.taro.tsx
  src/packages/dialog/demo.tsx
  src/packages/dialog/demos/h5/demo1.tsx
  src/packages/dialog/demos/h5/demo2.tsx
  src/packages/dialog/demos/h5/demo3.tsx
  src/packages/dialog/demos/h5/demo4.tsx
  src/packages/dialog/demos/h5/demo5.tsx
  src/packages/dialog/demos/h5/demo6.tsx
  src/packages/dialog/demos/h5/demo7.tsx
  src/packages/dialog/demos/h5/demo8.tsx
  src/packages/dialog/demos/taro/demo1.tsx
  src/packages/dialog/demos/taro/demo2.tsx
  src/packages/dialog/demos/taro/demo3.tsx
  src/packages/dialog/demos/taro/demo4.tsx
  src/packages/dialog/demos/taro/demo5.tsx
  src/packages/dialog/demos/taro/demo6.tsx
  src/packages/dialog/demos/taro/demo7.tsx
  src/packages/dialog/demos/taro/demo8.tsx
  src/packages/dialog/doc.en-US.md
  src/packages/dialog/doc.md
  src/packages/dialog/doc.taro.md
  src/packages/dialog/doc.zh-TW.md
Labels: size/XXL

#2090 fix(indicator): demo拆解与规范
  src/packages/indicator/demo.taro.tsx
  src/packages/indicator/demo.tsx
  src/packages/indicator/demos/h5/demo1.tsx
  src/packages/indicator/demos/h5/demo2.tsx
  src/packages/indicator/demos/h5/demo3.tsx
  src/packages/indicator/demos/h5/demo4.tsx
  src/packages/indicator/demos/taro/demo1.tsx
  src/packages/indicator/demos/taro/demo2.tsx
  src/packages/indicator/demos/taro/demo3.tsx
  src/packages/indicator/demos/taro/demo4.tsx
  src/packages/indicator/doc.en-US.md
  src/packages/indicator/doc.md
  src/packages/indicator/doc.taro.md
  src/packages/indicator/doc.zh-TW.md
Labels: size/XL

#2035 fix(input): demo拆解与规范
  src/packages/input/demo.taro.tsx
  src/packages/input/demo.tsx
  src/packages/input/demos/h5/demo1.tsx
  src/packages/input/demos/h5/demo10.tsx
  src/packages/input/demos/h5/demo11.tsx
  src/packages/input/demos/h5/demo12.tsx
  src/packages/input/demos/h5/demo13.tsx
  src/packages/input/demos/h5/demo14.tsx
  src/packages/input/demos/h5/demo2.tsx
  src/packages/input/demos/h5/demo3.tsx
  src/packages/input/demos/h5/demo4.tsx
  src/packages/input/demos/h5/demo5.tsx
  src/packages/input/demos/h5/demo6.tsx
  src/packages/input/demos/h5/demo7.tsx
  src/packages/input/demos/h5/demo8.tsx
  src/packages/input/demos/h5/demo9.tsx
  src/packages/input/demos/taro/demo1.tsx
  src/packages/input/demos/taro/demo10.tsx
  src/packages/input/demos/taro/demo11.tsx
  src/packages/input/demos/taro/demo12.tsx
  src/packages/input/demos/taro/demo13.tsx
  src/packages/input/demos/taro/demo14.tsx
  src/packages/input/demos/taro/demo2.tsx
  src/packages/input/demos/taro/demo3.tsx
  src/packages/input/demos/taro/demo4.tsx
  src/packages/input/demos/taro/demo5.tsx
  src/packages/input/demos/taro/demo6.tsx
  src/packages/input/demos/taro/demo7.tsx
  src/packages/input/demos/taro/demo8.tsx
  src/packages/input/demos/taro/demo9.tsx
  src/packages/input/doc.en-US.md
  src/packages/input/doc.md
  src/packages/input/doc.taro.md
  src/packages/input/doc.zh-TW.md
Labels: size/XXL

#2084 fix(pulltorefresh): demo中下拉图标修改为joy logo
  src/packages/pulltorefresh/demos/h5/demo1.tsx
  src/packages/pulltorefresh/demos/h5/demo2.tsx
  src/packages/pulltorefresh/demos/taro/demo1.tsx
  src/packages/pulltorefresh/demos/taro/demo3.tsx
Labels: size/M

#2081 fix(infiniteLoading): demo拆解与规范+增加joy logo的demo
  src/packages/infiniteloading/demo.scss
  src/packages/infiniteloading/demo.taro.tsx
  src/packages/infiniteloading/demo.tsx
  src/packages/infiniteloading/demos/h5/demo1.tsx
  src/packages/infiniteloading/demos/h5/demo2.tsx
  src/packages/infiniteloading/demos/h5/demo3.tsx
  src/packages/infiniteloading/demos/h5/demo4.tsx
  src/packages/infiniteloading/demos/h5/demo5.tsx
  src/packages/infiniteloading/demos/taro/demo1.tsx
  src/packages/infiniteloading/demos/taro/demo2.tsx
  src/packages/infiniteloading/demos/taro/demo3.tsx
  src/packages/infiniteloading/demos/taro/demo4.tsx
  src/packages/infiniteloading/doc.en-US.md
  src/packages/infiniteloading/doc.md
  src/packages/infiniteloading/doc.taro.md
  src/packages/infiniteloading/doc.zh-TW.md
Labels: size/XXL

#2092 fix: 代码块修改为等宽字体
  src/sites/assets/styles/highlight.scss
Labels: size/XS

#2096 fix: test
  src/packages/audio/__test__/__snapshots__/audio.spec.tsx.snap
  src/packages/avatargroup/__tests__/__snapshots__/avatargroup.spec.tsx.snap
  src/packages/backtop/__test__/__snapshots__/backtop.spec.tsx.snap
  src/packages/badge/__test__/__snapshots__/badge.spec.tsx.snap
  src/packages/button/__test__/__snapshots__/button.spec.tsx.snap
  src/packages/card/__test__/__snapshots__/card.spec.tsx.snap
  src/packages/cell/__test__/__snapshots__/cell.spec.tsx.snap
  src/packages/cellgroup/__test__/__snapshots__/cellgroup.spec.tsx.snap
  src/packages/checkbox/__test__/__snapshots__/checkbox.spec.tsx.snap
  src/packages/configprovider/__test__/__snapshots__/configprovider.spec.tsx.snap
  src/packages/divider/__test__/__snapshots__/divider.spec.tsx.snap
  src/packages/grid/__test__/__snapshots__/grid.spec.tsx.snap
  src/packages/icon/__test__/__snapshots__/icon.spec.tsx.snap
  src/packages/image/__test__/__snapshots__/image.spec.tsx.snap
  src/packages/menu/__test__/__snapshots__/menu.spec.tsx.snap
  src/packages/navbar/__test__/__snapshots__/navbar.spec.tsx.snap
  src/packages/overlay/__tests__/__snapshots__/overlay.spec.tsx.snap
  src/packages/pagination/__tests__/__snapshots__/pagination.spec.tsx.snap
  src/packages/progress/__tests__/__snapshots__/progress.spec.tsx.snap
  src/packages/sidenavbaritem/__test__/__snapshots__/sidenavbaritem.spec.tsx.snap
  src/packages/skeleton/__test__/__snapshots__/skeleton.spec.tsx.snap
  src/packages/subsidenavbar/__test__/__snapshots__/subsidenavbar.spec.tsx.snap
  src/packages/tag/__test__/__snapshots__/tag.spec.tsx.snap
  src/packages/textarea/__test__/__snapshots__/textarea.spec.tsx.snap
  src/packages/timeselect/__test__/__snapshots__/timeselect.spec.tsx.snap
  src/packages/video/__tests__/__snapshots__/video.spec.tsx.snap
Labels: size/M

#2078 fix(Ellipsis): 修复小程序环境下给Ellipsis设置字号后工作不正常的问题
  src/packages/ellipsis/ellipsis.taro.tsx
Labels: size/XS

#2095 fix: taro-demo full class
  packages/nutui-taro-demo/src/app.scss
  src/packages/menu/demo.scss
  src/packages/menu/demo.taro.tsx
  src/packages/menu/demo.tsx
Labels: size/S

#2100 fix(barrage): 简化demo
  src/packages/barrage/demos/h5/demo1.tsx
  src/packages/barrage/demos/taro/demo1.tsx
Labels: size/S

#2094 fix(collapse): demo拆解与规范
  src/packages/collapse/demo.taro.tsx
  src/packages/collapse/demo.tsx
  src/packages/collapse/demos/h5/demo1.tsx
  src/packages/collapse/demos/h5/demo2.tsx
  src/packages/collapse/demos/h5/demo3.tsx
  src/packages/collapse/demos/h5/demo4.tsx
  src/packages/collapse/demos/h5/demo5.tsx
  src/packages/collapse/demos/h5/demo6.tsx
  src/packages/collapse/demos/h5/demo7.tsx
  src/packages/collapse/demos/taro/demo1.tsx
  src/packages/collapse/demos/taro/demo2.tsx
  src/packages/collapse/demos/taro/demo3.tsx
  src/packages/collapse/demos/taro/demo4.tsx
  src/packages/collapse/demos/taro/demo5.tsx
  src/packages/collapse/demos/taro/demo6.tsx
  src/packages/collapse/demos/taro/demo7.tsx
  src/packages/collapse/doc.en-US.md
  src/packages/collapse/doc.md
  src/packages/collapse/doc.taro.md
  src/packages/collapse/doc.zh-TW.md
Labels: size/XXL

#2085 fix(animate): demo拆解与规范
  src/packages/animate/demo.taro.tsx
  src/packages/animate/demo.tsx
  src/packages/animate/demos/h5/demo1.tsx
  src/packages/animate/demos/h5/demo2.tsx
  src/packages/animate/demos/taro/demo1.tsx
  src/packages/animate/demos/taro/demo2.tsx
  src/packages/animate/doc.en-US.md
  src/packages/animate/doc.md
  src/packages/animate/doc.taro.md
  src/packages/animate/doc.zh-TW.md
Labels: size/XL

#2088 fix(tag): taro 下自定义icon无法展示
  src/packages/tag/demo.taro.tsx
  src/packages/tag/demo.tsx
  src/packages/tag/demos/h5/demo1.tsx
  src/packages/tag/demos/h5/demo2.tsx
  src/packages/tag/demos/h5/demo3.tsx
  src/packages/tag/demos/h5/demo4.tsx
  src/packages/tag/demos/taro/demo1.tsx
  src/packages/tag/demos/taro/demo2.tsx
  src/packages/tag/demos/taro/demo3.tsx
  src/packages/tag/demos/taro/demo4.tsx
  src/packages/tag/doc.en-US.md
  src/packages/tag/doc.md
  src/packages/tag/doc.taro.md
  src/packages/tag/doc.zh-TW.md
  src/packages/tag/tag.taro.tsx
Labels: size/XL

#2099 fix(signature): demo拆解与规范
  src/packages/signature/demo.taro.tsx
  src/packages/signature/demo.tsx
  src/packages/signature/demos/h5/demo1.tsx
  src/packages/signature/demos/h5/demo2.tsx
  src/packages/signature/demos/taro/demo1.tsx
  src/packages/signature/demos/taro/demo2.tsx
  src/packages/signature/doc.en-US.md
  src/packages/signature/doc.md
  src/packages/signature/doc.taro.md
  src/packages/signature/doc.zh-TW.md
Labels: size/XL

#2066 fix(Tabs): demo拆解与规范
  src/packages/tabs/demo.taro.tsx
  src/packages/tabs/demo.tsx
  src/packages/tabs/demos/h5/demo1.tsx
  src/packages/tabs/demos/h5/demo10.tsx
  src/packages/tabs/demos/h5/demo11.tsx
  src/packages/tabs/demos/h5/demo12.tsx
  src/packages/tabs/demos/h5/demo13.tsx
  src/packages/tabs/demos/h5/demo14.tsx
  src/packages/tabs/demos/h5/demo15.tsx
  src/packages/tabs/demos/h5/demo16.tsx
  src/packages/tabs/demos/h5/demo17.tsx
  src/packages/tabs/demos/h5/demo18.tsx
  src/packages/tabs/demos/h5/demo19.tsx
  src/packages/tabs/demos/h5/demo2.tsx
  src/packages/tabs/demos/h5/demo20.tsx
  src/packages/tabs/demos/h5/demo21.tsx
  src/packages/tabs/demos/h5/demo22.tsx
  src/packages/tabs/demos/h5/demo23.tsx
  src/packages/tabs/demos/h5/demo3.tsx
  src/packages/tabs/demos/h5/demo4.tsx
  src/packages/tabs/demos/h5/demo5.tsx
  src/packages/tabs/demos/h5/demo6.tsx
  src/packages/tabs/demos/h5/demo7.tsx
  src/packages/tabs/demos/h5/demo8.tsx
  src/packages/tabs/demos/h5/demo9.tsx
  src/packages/tabs/demos/taro/demo1.tsx
  src/packages/tabs/demos/taro/demo10.tsx
  src/packages/tabs/demos/taro/demo11.tsx
  src/packages/tabs/demos/taro/demo12.tsx
  src/packages/tabs/demos/taro/demo13.tsx
  src/packages/tabs/demos/taro/demo14.tsx
  src/packages/tabs/demos/taro/demo15.tsx
  src/packages/tabs/demos/taro/demo16.tsx
  src/packages/tabs/demos/taro/demo17.tsx
  src/packages/tabs/demos/taro/demo18.tsx
  src/packages/tabs/demos/taro/demo19.tsx
  src/packages/tabs/demos/taro/demo2.tsx
  src/packages/tabs/demos/taro/demo20.tsx
  src/packages/tabs/demos/taro/demo21.tsx
  src/packages/tabs/demos/taro/demo22.tsx
  src/packages/tabs/demos/taro/demo23.tsx
  src/packages/tabs/demos/taro/demo3.tsx
  src/packages/tabs/demos/taro/demo4.tsx
  src/packages/tabs/demos/taro/demo5.tsx
  src/packages/tabs/demos/taro/demo6.tsx
  src/packages/tabs/demos/taro/demo7.tsx
  src/packages/tabs/demos/taro/demo8.tsx
  src/packages/tabs/demos/taro/demo9.tsx
  src/packages/tabs/doc.en-US.md
  src/packages/tabs/doc.md
  src/packages/tabs/doc.taro.md
  src/packages/tabs/doc.zh-TW.md
Labels: size/XXL

#2087 fix(timeselect): demo拆解与规范
  src/packages/timeselect/demo.taro.tsx
  src/packages/timeselect/demo.tsx
  src/packages/timeselect/demos/h5/demo1.tsx
  src/packages/timeselect/demos/h5/demo2.tsx
  src/packages/timeselect/demos/h5/demo3.tsx
  src/packages/timeselect/demos/h5/demo4.tsx
  src/packages/timeselect/demos/taro/demo1.tsx
  src/packages/timeselect/demos/taro/demo2.tsx
  src/packages/timeselect/demos/taro/demo3.tsx
  src/packages/timeselect/demos/taro/demo4.tsx
  src/packages/timeselect/doc.en-US.md
  src/packages/timeselect/doc.md
  src/packages/timeselect/doc.taro.md
  src/packages/timeselect/doc.zh-TW.md
Labels: size/XXL

#2074 fix(table): demo拆解与规范
  src/packages/table/demo.taro.tsx
  src/packages/table/demo.tsx
  src/packages/table/demos/h5/demo1.tsx
  src/packages/table/demos/h5/demo10.tsx
  src/packages/table/demos/h5/demo11.tsx
  src/packages/table/demos/h5/demo12.tsx
  src/packages/table/demos/h5/demo13.tsx
  src/packages/table/demos/h5/demo2.tsx
  src/packages/table/demos/h5/demo3.tsx
  src/packages/table/demos/h5/demo4.tsx
  src/packages/table/demos/h5/demo5.tsx
  src/packages/table/demos/h5/demo6.tsx
  src/packages/table/demos/h5/demo7.tsx
  src/packages/table/demos/h5/demo8.tsx
  src/packages/table/demos/h5/demo9.tsx
  src/packages/table/demos/taro/demo1.tsx
  src/packages/table/demos/taro/demo10.tsx
  src/packages/table/demos/taro/demo11.tsx
  src/packages/table/demos/taro/demo12.tsx
  src/packages/table/demos/taro/demo13.tsx
  src/packages/table/demos/taro/demo2.tsx
  src/packages/table/demos/taro/demo3.tsx
  src/packages/table/demos/taro/demo4.tsx
  src/packages/table/demos/taro/demo5.tsx
  src/packages/table/demos/taro/demo6.tsx
  src/packages/table/demos/taro/demo7.tsx
  src/packages/table/demos/taro/demo8.tsx
  src/packages/table/demos/taro/demo9.tsx
  src/packages/table/doc.en-US.md
  src/packages/table/doc.md
  src/packages/table/doc.taro.md
  src/packages/table/doc.zh-TW.md
Labels: size/XXL

#2101 fix: vitest
  src/packages/indicator/__test__/__snapshots__/indicator.spec.tsx.snap
  src/packages/price/__test__/__snapshots__/price.spec.tsx.snap
  src/packages/range/__test__/__snapshots__/range.spec.tsx.snap
  src/packages/space/__test__/__snapshots__/space.spec.tsx.snap
Labels: size/XS

#2091 fix(circleprogress): demo拆解与规范
  src/packages/circleprogress/demo.taro.tsx
  src/packages/circleprogress/demo.tsx
  src/packages/circleprogress/demos/h5/demo1.tsx
  src/packages/circleprogress/demos/h5/demo2.tsx
  src/packages/circleprogress/demos/h5/demo3.tsx
  src/packages/circleprogress/demos/h5/demo4.tsx
  src/packages/circleprogress/demos/h5/demo5.tsx
  src/packages/circleprogress/demos/h5/demo6.tsx
  src/packages/circleprogress/demos/taro/demo1.tsx
  src/packages/circleprogress/demos/taro/demo2.tsx
  src/packages/circleprogress/demos/taro/demo3.tsx
  src/packages/circleprogress/demos/taro/demo4.tsx
  src/packages/circleprogress/demos/taro/demo5.tsx
  src/packages/circleprogress/demos/taro/demo6.tsx
  src/packages/circleprogress/doc.en-US.md
  src/packages/circleprogress/doc.md
  src/packages/circleprogress/doc.taro.md
  src/packages/circleprogress/doc.zh-TW.md
Labels: size/XL

#2102 fix(shortpassword): demo拆解与规范
  src/packages/shortpassword/demo.taro.tsx
  src/packages/shortpassword/demo.tsx
  src/packages/shortpassword/demos/h5/demo1.tsx
  src/packages/shortpassword/demos/h5/demo2.tsx
  src/packages/shortpassword/demos/h5/demo3.tsx
  src/packages/shortpassword/demos/h5/demo4.tsx
  src/packages/shortpassword/demos/h5/demo5.tsx
  src/packages/shortpassword/demos/h5/demo6.tsx
  src/packages/shortpassword/demos/taro/demo1.tsx
  src/packages/shortpassword/demos/taro/demo2.tsx
  src/packages/shortpassword/demos/taro/demo3.tsx
  src/packages/shortpassword/demos/taro/demo4.tsx
  src/packages/shortpassword/demos/taro/demo5.tsx
  src/packages/shortpassword/demos/taro/demo6.tsx
  src/packages/shortpassword/doc.en-US.md
  src/packages/shortpassword/doc.md
  src/packages/shortpassword/doc.taro.md
  src/packages/shortpassword/doc.zh-TW.md
Labels: size/XXL

#2086 feat(progress): 支持taro的lazy属性 & demo拆解与规范
  src/packages/progress/demo.taro.tsx
  src/packages/progress/demo.tsx
  src/packages/progress/demos/h5/demo1.tsx
  src/packages/progress/demos/h5/demo2.tsx
  src/packages/progress/demos/h5/demo3.tsx
  src/packages/progress/demos/h5/demo4.tsx
  src/packages/progress/demos/h5/demo5.tsx
  src/packages/progress/demos/h5/demo6.tsx
  src/packages/progress/demos/h5/demo7.tsx
  src/packages/progress/demos/h5/demo8.tsx
  src/packages/progress/demos/taro/demo1.tsx
  src/packages/progress/demos/taro/demo2.tsx
  src/packages/progress/demos/taro/demo3.tsx
  src/packages/progress/demos/taro/demo4.tsx
  src/packages/progress/demos/taro/demo5.tsx
  src/packages/progress/demos/taro/demo6.tsx
  src/packages/progress/demos/taro/demo7.tsx
  src/packages/progress/demos/taro/demo8.tsx
  src/packages/progress/doc.en-US.md
  src/packages/progress/doc.md
  src/packages/progress/doc.taro.md
  src/packages/progress/doc.zh-TW.md
  src/packages/progress/progress.taro.tsx
Labels: size/XXL

#2106 fix(Swipe): 修改demo文案
  src/packages/swipe/demo.taro.tsx
  src/packages/swipe/demo.tsx
  src/packages/swipe/doc.en-US.md
  src/packages/swipe/doc.md
  src/packages/swipe/doc.taro.md
  src/packages/swipe/doc.zh-TW.md
Labels: size/S

#2107 fix: 修复 demo 目录报错
  src/sites/mobile/Links.tsx
Labels: size/XS

#2105 fix(steps): demo拆解与规范
  src/packages/steps/demo.scss
  src/packages/steps/demo.taro.tsx
  src/packages/steps/demo.tsx
  src/packages/steps/demos/h5/demo1.tsx
  src/packages/steps/demos/h5/demo2.tsx
  src/packages/steps/demos/h5/demo3.tsx
  src/packages/steps/demos/h5/demo4.tsx
  src/packages/steps/demos/h5/demo5.tsx
  src/packages/steps/demos/h5/demo6.tsx
  src/packages/steps/demos/h5/demo7.tsx
  src/packages/steps/demos/h5/demo8.tsx
  src/packages/steps/demos/h5/demo9.tsx
  src/packages/steps/demos/taro/demo1.tsx
  src/packages/steps/demos/taro/demo2.tsx
  src/packages/steps/demos/taro/demo3.tsx
  src/packages/steps/demos/taro/demo4.tsx
  src/packages/steps/demos/taro/demo5.tsx
  src/packages/steps/demos/taro/demo6.tsx
  src/packages/steps/demos/taro/demo7.tsx
  src/packages/steps/demos/taro/demo8.tsx
  src/packages/steps/demos/taro/demo9.tsx
  src/packages/steps/doc.en-US.md
  src/packages/steps/doc.md
  src/packages/steps/doc.taro.md
  src/packages/steps/doc.zh-TW.md
Labels: size/XXL

#2103 fix(avatarcropper): demo拆解与规范
  src/packages/avatarcropper/demo.scss
  src/packages/avatarcropper/demo.taro.tsx
  src/packages/avatarcropper/demo.tsx
  src/packages/avatarcropper/demos/h5/demo1.tsx
  src/packages/avatarcropper/demos/h5/demo2.tsx
  src/packages/avatarcropper/demos/h5/demo3.tsx
  src/packages/avatarcropper/demos/taro/demo1.tsx
  src/packages/avatarcropper/demos/taro/demo2.tsx
  src/packages/avatarcropper/demos/taro/demo3.tsx
  src/packages/avatarcropper/doc.en-US.md
  src/packages/avatarcropper/doc.md
  src/packages/avatarcropper/doc.taro.md
  src/packages/avatarcropper/doc.zh-TW.md
Labels: size/XL

#2104 fix(video): demo拆解与规范
  src/packages/video/demo.scss
  src/packages/video/demo.taro.tsx
  src/packages/video/demo.tsx
  src/packages/video/demos/h5/demo1.tsx
  src/packages/video/demos/h5/demo2.tsx
  src/packages/video/demos/h5/demo3.tsx
  src/packages/video/demos/h5/demo4.tsx
  src/packages/video/demos/h5/demo5.tsx
  src/packages/video/demos/h5/demo6.tsx
  src/packages/video/demos/h5/demo7.tsx
  src/packages/video/demos/taro/demo1.tsx
  src/packages/video/demos/taro/demo2.tsx
  src/packages/video/demos/taro/demo3.tsx
  src/packages/video/demos/taro/demo4.tsx
  src/packages/video/demos/taro/demo5.tsx
  src/packages/video/demos/taro/demo6.tsx
  src/packages/video/demos/taro/demo7.tsx
  src/packages/video/doc.en-US.md
  src/packages/video/doc.md
  src/packages/video/doc.taro.md
  src/packages/video/doc.zh-TW.md
Labels: size/XXL

#2109 fix(animatingnumbers): demo拆解与规范
  src/packages/animatingnumbers/demo.taro.tsx
  src/packages/animatingnumbers/demo.tsx
  src/packages/animatingnumbers/demos/h5/demo1.tsx
  src/packages/animatingnumbers/demos/h5/demo2.tsx
  src/packages/animatingnumbers/demos/taro/demo1.tsx
  src/packages/animatingnumbers/demos/taro/demo2.tsx
  src/packages/animatingnumbers/doc.en-US.md
  src/packages/animatingnumbers/doc.md
  src/packages/animatingnumbers/doc.taro.md
  src/packages/animatingnumbers/doc.zh-TW.md
Labels: size/L

#2026 chore(calendarcard): demo 拆解与规范
  src/packages/calendarcard/calendarcard.taro.tsx
  src/packages/calendarcard/calendarcard.tsx
  src/packages/calendarcard/demo.taro.tsx
  src/packages/calendarcard/demo.tsx
  src/packages/calendarcard/demos/h5/demo1.tsx
  src/packages/calendarcard/demos/h5/demo10.tsx
  src/packages/calendarcard/demos/h5/demo11.tsx
  src/packages/calendarcard/demos/h5/demo2.tsx
  src/packages/calendarcard/demos/h5/demo3.tsx
  src/packages/calendarcard/demos/h5/demo4.tsx
  src/packages/calendarcard/demos/h5/demo5.tsx
  src/packages/calendarcard/demos/h5/demo6.tsx
  src/packages/calendarcard/demos/h5/demo7.tsx
  src/packages/calendarcard/demos/h5/demo8.tsx
  src/packages/calendarcard/demos/h5/demo9.tsx
  src/packages/calendarcard/demos/taro/demo1.tsx
  src/packages/calendarcard/demos/taro/demo10.tsx
  src/packages/calendarcard/demos/taro/demo11.tsx
  src/packages/calendarcard/demos/taro/demo2.tsx
  src/packages/calendarcard/demos/taro/demo3.tsx
  src/packages/calendarcard/demos/taro/demo4.tsx
  src/packages/calendarcard/demos/taro/demo5.tsx
  src/packages/calendarcard/demos/taro/demo6.tsx
  src/packages/calendarcard/demos/taro/demo7.tsx
  src/packages/calendarcard/demos/taro/demo8.tsx
  src/packages/calendarcard/demos/taro/demo9.tsx
  src/packages/calendarcard/doc.en-US.md
  src/packages/calendarcard/doc.md
  src/packages/calendarcard/doc.taro.md
  src/packages/calendarcard/doc.zh-TW.md
  src/packages/calendarcard/index.taro.ts
  src/packages/calendarcard/index.ts
  src/packages/calendarcard/types.ts
  src/packages/cascader/__tests__/__snapshots__/cascader.spec.tsx.snap
  src/packages/configprovider/__test__/__snapshots__/configprovider.spec.tsx.snap
  src/packages/dialog/__test__/dialog.spec.tsx
  src/packages/drag/__test__/__snapshots__/drag.spec.tsx.snap
Labels: size/XXL

#2111 fix(audio): demo拆解与规范
  src/packages/audio/demo.scss
  src/packages/audio/demo.taro.tsx
  src/packages/audio/demo.tsx
  src/packages/audio/demos/h5/demo1.tsx
  src/packages/audio/demos/h5/demo2.tsx
  src/packages/audio/demos/h5/demo3.tsx
  src/packages/audio/demos/h5/demo4.tsx
  src/packages/audio/doc.en-US.md
  src/packages/audio/doc.md
  src/packages/audio/doc.zh-TW.md
Labels: size/XL

#2115 fix(swiper): demo拆解与规范
  src/packages/swiper/demo.scss
  src/packages/swiper/demo.taro.tsx
  src/packages/swiper/demo.tsx
  src/packages/swiper/demos/h5/demo1.tsx
  src/packages/swiper/demos/h5/demo2.tsx
  src/packages/swiper/demos/h5/demo3.tsx
  src/packages/swiper/demos/h5/demo4.tsx
  src/packages/swiper/demos/h5/demo5.tsx
  src/packages/swiper/demos/h5/demo6.tsx
  src/packages/swiper/demos/h5/demo7.tsx
  src/packages/swiper/demos/h5/demo8.tsx
  src/packages/swiper/demos/h5/demo9.tsx
  src/packages/swiper/demos/taro/demo1.tsx
  src/packages/swiper/demos/taro/demo2.tsx
  src/packages/swiper/demos/taro/demo3.tsx
  src/packages/swiper/demos/taro/demo4.tsx
  src/packages/swiper/demos/taro/demo5.tsx
  src/packages/swiper/demos/taro/demo6.tsx
  src/packages/swiper/demos/taro/demo7.tsx
  src/packages/swiper/demos/taro/demo8.tsx
  src/packages/swiper/demos/taro/demo9.tsx
  src/packages/swiper/doc.en-US.md
  src/packages/swiper/doc.md
  src/packages/swiper/doc.taro.md
  src/packages/swiper/doc.zh-TW.md
  src/packages/swiper/swiper.taro.tsx
Labels: size/XXL

#2114 fix(Icon): 小程序下展示异常问题修复
  src/packages/icon/demo.taro.tsx
  src/packages/icon/demos/taro/demo1.tsx
  src/packages/icon/demos/taro/demo2.tsx
  src/packages/icon/demos/taro/demo4.tsx
  src/packages/icon/demos/taro/demo5.tsx
  src/packages/icon/demos/taro/demo6.tsx
  src/packages/icon/demos/taro/demo7.tsx
Labels: size/M

#2110 fix: 修复address组件onChange参数透传问题
  src/packages/address/customRender.taro.tsx
  src/packages/address/customRender.tsx
Labels: size/XS

#2116 fix(virtuallist): demo拆解与规范
  packages/nutui-taro-demo/src/pages/index/index.tsx
  src/packages/virtuallist/demo.taro.tsx
  src/packages/virtuallist/demo.tsx
  src/packages/virtuallist/demos/h5/demo1.tsx
  src/packages/virtuallist/demos/h5/demo2.tsx
  src/packages/virtuallist/demos/h5/demo3.tsx
  src/packages/virtuallist/demos/h5/demo4.tsx
  src/packages/virtuallist/demos/taro/demo1.tsx
  src/packages/virtuallist/demos/taro/demo2.tsx
  src/packages/virtuallist/doc.en-US.md
  src/packages/virtuallist/doc.md
  src/packages/virtuallist/doc.taro.md
  src/packages/virtuallist/doc.zh-TW.md
  src/packages/virtuallist/virtuallist.scss
  src/packages/virtuallist/virtuallist.tsx
Labels: size/XXL

#2117 feat(Popover): 新增单条数据的demo展示
  src/packages/popover/demo.taro.tsx
  src/packages/popover/demo.tsx
  src/packages/popover/demos/h5/demo2.tsx
  src/packages/popover/demos/h5/demo4-1.tsx
  src/packages/popover/demos/h5/demo5.tsx
  src/packages/popover/demos/taro/demo2.tsx
  src/packages/popover/demos/taro/demo4-1.tsx
  src/packages/popover/demos/taro/demo5.tsx
  src/packages/popover/doc.en-US.md
  src/packages/popover/doc.md
  src/packages/popover/doc.taro.md
  src/packages/popover/doc.zh-TW.md
  src/packages/popover/popover.scss
Labels: size/L

#2119 fix(noticebar): fix docs
  src/packages/noticebar/doc.en-US.md
  src/packages/noticebar/doc.md
  src/packages/noticebar/doc.taro.md
  src/packages/noticebar/doc.zh-TW.md
Labels: size/L

#2118 fix(dialog): 关闭按钮默认在底部，24px白色图标
  src/packages/dialog/demos/h5/demo6.tsx
  src/packages/dialog/demos/taro/demo6.tsx
  src/packages/dialog/dialog.scss
  src/packages/dialog/dialog.taro.tsx
  src/packages/dialog/dialog.tsx
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/M, break

#2123 fix(numberkeyboard): demo拆解与规范
  src/packages/numberkeyboard/demo.taro.tsx
  src/packages/numberkeyboard/demo.tsx
  src/packages/numberkeyboard/demos/h5/demo1.tsx
  src/packages/numberkeyboard/demos/h5/demo2.tsx
  src/packages/numberkeyboard/demos/h5/demo3.tsx
  src/packages/numberkeyboard/demos/h5/demo4.tsx
  src/packages/numberkeyboard/demos/h5/demo5.tsx
  src/packages/numberkeyboard/demos/h5/demo6.tsx
  src/packages/numberkeyboard/demos/taro/demo1.tsx
  src/packages/numberkeyboard/demos/taro/demo2.tsx
  src/packages/numberkeyboard/demos/taro/demo3.tsx
  src/packages/numberkeyboard/demos/taro/demo4.tsx
  src/packages/numberkeyboard/demos/taro/demo5.tsx
  src/packages/numberkeyboard/demos/taro/demo6.tsx
  src/packages/numberkeyboard/doc.en-US.md
  src/packages/numberkeyboard/doc.md
  src/packages/numberkeyboard/doc.taro.md
  src/packages/numberkeyboard/doc.zh-TW.md
Labels: size/XXL

#2122 fix(popup): demo拆解与规范
  src/packages/popup/demo.taro.tsx
  src/packages/popup/demo.tsx
  src/packages/popup/demos/h5/demo1.tsx
  src/packages/popup/demos/h5/demo2.tsx
  src/packages/popup/demos/h5/demo3.tsx
  src/packages/popup/demos/h5/demo4.tsx
  src/packages/popup/demos/h5/demo5.tsx
  src/packages/popup/demos/h5/demo6.tsx
  src/packages/popup/demos/h5/demo7.tsx
  src/packages/popup/demos/taro/demo1.tsx
  src/packages/popup/demos/taro/demo2.tsx
  src/packages/popup/demos/taro/demo3.tsx
  src/packages/popup/demos/taro/demo4.tsx
  src/packages/popup/demos/taro/demo5.tsx
  src/packages/popup/demos/taro/demo6.tsx
  src/packages/popup/demos/taro/demo7.tsx
  src/packages/popup/demos/taro/demo8.tsx
  src/packages/popup/doc.en-US.md
  src/packages/popup/doc.md
  src/packages/popup/doc.taro.md
  src/packages/popup/doc.zh-TW.md
Labels: size/XXL

#2129 fix(icon): update taro demo
  src/packages/icon/demos/taro/demo6.tsx
Labels: size/S

#2124 fix(actionsheet): demo拆解与规范
  src/packages/actionsheet/demo.taro.tsx
  src/packages/actionsheet/demo.tsx
  src/packages/actionsheet/demos/h5/demo1.tsx
  src/packages/actionsheet/demos/h5/demo2.tsx
  src/packages/actionsheet/demos/h5/demo3.tsx
  src/packages/actionsheet/demos/h5/demo4.tsx
  src/packages/actionsheet/demos/h5/demo5.tsx
  src/packages/actionsheet/demos/h5/demo6.tsx
  src/packages/actionsheet/demos/taro/demo1.tsx
  src/packages/actionsheet/demos/taro/demo2.tsx
  src/packages/actionsheet/demos/taro/demo3.tsx
  src/packages/actionsheet/demos/taro/demo4.tsx
  src/packages/actionsheet/demos/taro/demo5.tsx
  src/packages/actionsheet/demos/taro/demo6.tsx
  src/packages/actionsheet/doc.en-US.md
  src/packages/actionsheet/doc.md
  src/packages/actionsheet/doc.taro.md
  src/packages/actionsheet/doc.zh-TW.md
Labels: size/XXL

#2131 docs(readme): change npm to pnpm in the document
  README.md
  README_ZH.md
Labels: size/S

#2108 feat(progress): Taro新增lazy属性
  packages/nutui-taro-demo/project.config.json
  src/packages/progress/demo.taro.tsx
  src/packages/progress/demo.tsx
  src/packages/progress/demos/h5/demo1.tsx
  src/packages/progress/demos/h5/demo2.tsx
  src/packages/progress/demos/h5/demo3.tsx
  src/packages/progress/demos/h5/demo4.tsx
  src/packages/progress/demos/h5/demo5.tsx
  src/packages/progress/demos/h5/demo6.tsx
  src/packages/progress/demos/h5/demo7.tsx
  src/packages/progress/demos/h5/demo8.tsx
  src/packages/progress/demos/taro/demo1.tsx
  src/packages/progress/demos/taro/demo2.tsx
  src/packages/progress/demos/taro/demo3.tsx
  src/packages/progress/demos/taro/demo4.tsx
  src/packages/progress/demos/taro/demo5.tsx
  src/packages/progress/demos/taro/demo6.tsx
  src/packages/progress/demos/taro/demo7.tsx
  src/packages/progress/demos/taro/demo8.tsx
  src/packages/progress/doc.en-US.md
  src/packages/progress/doc.md
  src/packages/progress/doc.taro.md
  src/packages/progress/doc.zh-TW.md
  src/packages/progress/progress.taro.tsx
  src/packages/progress/progress.tsx
Labels: size/XXL

#2120 feat(Form): rtl
  src/packages/form/form.scss
  src/packages/formitem/formitem.scss
  src/packages/input/__test__/input.spec.tsx
  src/packages/input/input.taro.tsx
  src/packages/input/input.tsx
  src/styles/variables.scss
Labels: size/L

#2128 feat(ellipsis): rtl
  src/packages/ellipsis/__test__/__snapshots__/ellipsis.spec.tsx.snap
  src/packages/ellipsis/__test__/ellipsis.spec.tsx
  src/packages/ellipsis/demo.taro.tsx
  src/packages/ellipsis/demo.tsx
  src/packages/ellipsis/demos/h5/demo1.tsx
  src/packages/ellipsis/demos/h5/demo2.tsx
  src/packages/ellipsis/demos/h5/demo3.tsx
  src/packages/ellipsis/demos/h5/demo4.tsx
  src/packages/ellipsis/demos/h5/demo5.tsx
  src/packages/ellipsis/demos/taro/demo1.tsx
  src/packages/ellipsis/demos/taro/demo2.tsx
  src/packages/ellipsis/demos/taro/demo3.tsx
  src/packages/ellipsis/demos/taro/demo4.tsx
  src/packages/ellipsis/demos/taro/demo5.tsx
  src/packages/ellipsis/demos/taro/demo6.tsx
  src/packages/ellipsis/doc.en-US.md
  src/packages/ellipsis/doc.md
  src/packages/ellipsis/doc.taro.md
  src/packages/ellipsis/doc.zh-TW.md
  src/packages/ellipsis/ellipsis.scss
  src/packages/ellipsis/ellipsis.taro.tsx
  src/packages/ellipsis/ellipsis.tsx
Labels: size/XXL

#2130 fix(tour): demo拆解与规范
  src/packages/tour/demo.taro.tsx
  src/packages/tour/demo.tsx
  src/packages/tour/demos/h5/demo1.tsx
  src/packages/tour/demos/h5/demo2.tsx
  src/packages/tour/demos/h5/demo3.tsx
  src/packages/tour/demos/h5/demo4.tsx
  src/packages/tour/demos/h5/demo5.tsx
  src/packages/tour/demos/taro/demo1.tsx
  src/packages/tour/demos/taro/demo2.tsx
  src/packages/tour/demos/taro/demo3.tsx
  src/packages/tour/demos/taro/demo4.tsx
  src/packages/tour/demos/taro/demo5.tsx
  src/packages/tour/doc.en-US.md
  src/packages/tour/doc.md
  src/packages/tour/doc.taro.md
  src/packages/tour/doc.zh-TW.md
Labels: size/XXL

#2132 fix(textarea): demo拆解与规范
  src/packages/textarea/demo.taro.tsx
  src/packages/textarea/demo.tsx
  src/packages/textarea/demos/h5/demo1.tsx
  src/packages/textarea/demos/h5/demo2.tsx
  src/packages/textarea/demos/h5/demo3.tsx
  src/packages/textarea/demos/h5/demo4.tsx
  src/packages/textarea/demos/h5/demo5.tsx
  src/packages/textarea/demos/h5/demo6.tsx
  src/packages/textarea/demos/h5/demo7.tsx
  src/packages/textarea/demos/h5/demo8.tsx
  src/packages/textarea/demos/taro/demo1.tsx
  src/packages/textarea/demos/taro/demo2.tsx
  src/packages/textarea/demos/taro/demo3.tsx
  src/packages/textarea/demos/taro/demo4.tsx
  src/packages/textarea/demos/taro/demo5.tsx
  src/packages/textarea/demos/taro/demo6.tsx
  src/packages/textarea/demos/taro/demo7.tsx
  src/packages/textarea/demos/taro/demo8.tsx
  src/packages/textarea/doc.en-US.md
  src/packages/textarea/doc.md
  src/packages/textarea/doc.taro.md
  src/packages/textarea/doc.zh-TW.md
Labels: size/XL

#2134 fix(imagepreview): demo拆解与规范
  src/packages/imagepreview/demo.taro.tsx
  src/packages/imagepreview/demo.tsx
  src/packages/imagepreview/demos/h5/demo1.tsx
  src/packages/imagepreview/demos/h5/demo2.tsx
  src/packages/imagepreview/demos/h5/demo3.tsx
  src/packages/imagepreview/demos/h5/demo4.tsx
  src/packages/imagepreview/demos/h5/demo5.tsx
  src/packages/imagepreview/demos/h5/demo6.tsx
  src/packages/imagepreview/demos/h5/demo7.tsx
  src/packages/imagepreview/demos/taro/demo1.tsx
  src/packages/imagepreview/demos/taro/demo2.tsx
  src/packages/imagepreview/demos/taro/demo3.tsx
  src/packages/imagepreview/demos/taro/demo4.tsx
  src/packages/imagepreview/demos/taro/demo5.tsx
  src/packages/imagepreview/demos/taro/demo6.tsx
  src/packages/imagepreview/demos/taro/demo7.tsx
  src/packages/imagepreview/doc.en-US.md
  src/packages/imagepreview/doc.md
  src/packages/imagepreview/doc.taro.md
  src/packages/imagepreview/doc.zh-TW.md
Labels: size/XXL

#2139 fix(range): demo拆解与规范
  src/packages/range/demo.taro.tsx
  src/packages/range/demo.tsx
  src/packages/range/demos/h5/demo1.tsx
  src/packages/range/demos/h5/demo10.tsx
  src/packages/range/demos/h5/demo11.tsx
  src/packages/range/demos/h5/demo12.tsx
  src/packages/range/demos/h5/demo13.tsx
  src/packages/range/demos/h5/demo2.tsx
  src/packages/range/demos/h5/demo3.tsx
  src/packages/range/demos/h5/demo4.tsx
  src/packages/range/demos/h5/demo5.tsx
  src/packages/range/demos/h5/demo6.tsx
  src/packages/range/demos/h5/demo7.tsx
  src/packages/range/demos/h5/demo8.tsx
  src/packages/range/demos/h5/demo9.tsx
  src/packages/range/demos/taro/demo1.tsx
  src/packages/range/demos/taro/demo10.tsx
  src/packages/range/demos/taro/demo11.tsx
  src/packages/range/demos/taro/demo12.tsx
  src/packages/range/demos/taro/demo13.tsx
  src/packages/range/demos/taro/demo2.tsx
  src/packages/range/demos/taro/demo3.tsx
  src/packages/range/demos/taro/demo4.tsx
  src/packages/range/demos/taro/demo5.tsx
  src/packages/range/demos/taro/demo6.tsx
  src/packages/range/demos/taro/demo7.tsx
  src/packages/range/demos/taro/demo8.tsx
  src/packages/range/demos/taro/demo9.tsx
  src/packages/range/doc.en-US.md
  src/packages/range/doc.md
  src/packages/range/doc.taro.md
  src/packages/range/doc.zh-TW.md
Labels: size/XXL

#2135 fix(tabs): 修复 tab 过多时滚动定位不准确的问题
  src/packages/navbar/demos/h5/demo3.tsx
  src/packages/navbar/demos/taro/demo3.tsx
  src/packages/tabs/demo.taro.tsx
  src/packages/tabs/doc.en-US.md
  src/packages/tabs/doc.md
  src/packages/tabs/doc.taro.md
  src/packages/tabs/doc.zh-TW.md
  src/packages/tabs/tabs.scss
  src/packages/tabs/tabs.taro.tsx
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/XL

#2140 fix(uploader): demo拆解与规范
  src/packages/uploader/demo.scss
  src/packages/uploader/demo.taro.tsx
  src/packages/uploader/demo.tsx
  src/packages/uploader/demos/h5/demo1.tsx
  src/packages/uploader/demos/h5/demo10.tsx
  src/packages/uploader/demos/h5/demo11.tsx
  src/packages/uploader/demos/h5/demo12.tsx
  src/packages/uploader/demos/h5/demo13.tsx
  src/packages/uploader/demos/h5/demo2.tsx
  src/packages/uploader/demos/h5/demo3.tsx
  src/packages/uploader/demos/h5/demo4.tsx
  src/packages/uploader/demos/h5/demo5.tsx
  src/packages/uploader/demos/h5/demo6.tsx
  src/packages/uploader/demos/h5/demo7.tsx
  src/packages/uploader/demos/h5/demo8.tsx
  src/packages/uploader/demos/h5/demo9.tsx
  src/packages/uploader/demos/taro/demo1.tsx
  src/packages/uploader/demos/taro/demo10.tsx
  src/packages/uploader/demos/taro/demo11.tsx
  src/packages/uploader/demos/taro/demo12.tsx
  src/packages/uploader/demos/taro/demo13.tsx
  src/packages/uploader/demos/taro/demo2.tsx
  src/packages/uploader/demos/taro/demo3.tsx
  src/packages/uploader/demos/taro/demo4.tsx
  src/packages/uploader/demos/taro/demo5.tsx
  src/packages/uploader/demos/taro/demo6.tsx
  src/packages/uploader/demos/taro/demo7.tsx
  src/packages/uploader/demos/taro/demo8.tsx
  src/packages/uploader/demos/taro/demo9.tsx
  src/packages/uploader/doc.en-US.md
  src/packages/uploader/doc.md
  src/packages/uploader/doc.taro.md
  src/packages/uploader/doc.zh-TW.md
Labels: size/XXL

#2133 fix(DatePicker): demo拆解与规范
  src/packages/datepicker/demo.taro.tsx
  src/packages/datepicker/demo.tsx
  src/packages/datepicker/demos/h5/demo1.tsx
  src/packages/datepicker/demos/h5/demo2.tsx
  src/packages/datepicker/demos/h5/demo3.tsx
  src/packages/datepicker/demos/h5/demo4.tsx
  src/packages/datepicker/demos/h5/demo5.tsx
  src/packages/datepicker/demos/h5/demo6.tsx
  src/packages/datepicker/demos/h5/demo7.tsx
  src/packages/datepicker/demos/h5/demo8.tsx
  src/packages/datepicker/demos/taro/demo1.tsx
  src/packages/datepicker/demos/taro/demo2.tsx
  src/packages/datepicker/demos/taro/demo3.tsx
  src/packages/datepicker/demos/taro/demo4.tsx
  src/packages/datepicker/demos/taro/demo5.tsx
  src/packages/datepicker/demos/taro/demo6.tsx
  src/packages/datepicker/demos/taro/demo7.tsx
  src/packages/datepicker/demos/taro/demo8.tsx
  src/packages/datepicker/doc.en-US.md
  src/packages/datepicker/doc.md
  src/packages/datepicker/doc.taro.md
  src/packages/datepicker/doc.zh-TW.md
  src/packages/datepicker/index.taro.ts
Labels: size/XXL

#2073 fix(Toast): demo拆解与规范
  src/packages/toast/demo.taro.tsx
  src/packages/toast/demo.tsx
  src/packages/toast/demos/h5/demo1.tsx
  src/packages/toast/demos/h5/demo2.tsx
  src/packages/toast/demos/h5/demo3.tsx
  src/packages/toast/demos/h5/demo4.tsx
  src/packages/toast/demos/h5/demo5.tsx
  src/packages/toast/demos/taro/demo1.tsx
  src/packages/toast/demos/taro/demo2.tsx
  src/packages/toast/demos/taro/demo3.tsx
  src/packages/toast/demos/taro/demo4.tsx
  src/packages/toast/demos/taro/demo5.tsx
  src/packages/toast/doc.en-US.md
  src/packages/toast/doc.md
  src/packages/toast/doc.taro.md
  src/packages/toast/doc.zh-TW.md
Labels: size/XXL

#2121 feat(popover): rtl
  src/packages/popover/demos/h5/demo1.tsx
  src/packages/popover/demos/h5/demo2.tsx
  src/packages/popover/demos/h5/demo4-1.tsx
  src/packages/popover/demos/h5/demo6.tsx
  src/packages/popover/demos/h5/demo7.tsx
  src/packages/popover/demos/h5/demo8.tsx
  src/packages/popover/demos/taro/demo1.tsx
  src/packages/popover/demos/taro/demo2.tsx
  src/packages/popover/popover.scss
  src/packages/popover/popover.taro.tsx
  src/packages/popover/popover.tsx
Labels: size/M

#2141 fix(datepicker): 修复 datepicker 类型为hour-minutes/time时选中值无法回显的问题
  src/packages/datepicker/datepicker.taro.tsx
  src/packages/datepicker/datepicker.tsx
Labels: size/M
