Repository jdf2e/nutui-react, pull requests merged in 2024-05, with the labels that each got.

#2224 docs(uploader): 文件上传编码使用提示
  src/packages/uploader/doc.en-US.md
  src/packages/uploader/doc.md
  src/packages/uploader/doc.taro.md
  src/packages/uploader/doc.zh-TW.md
Labels: size/M

#2223 fix: 仅注释button组件RN报错文件
  packages/nutui-taro-demo-rn/nutui-react/config.json
  packages/nutui-taro-demo-rn/nutui-react/packages/button/button.harmony.css
  packages/nutui-taro-demo-rn/nutui-react/packages/button/button.taro.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/button/demo.taro.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/button/demos/taro/demo4.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/nutui.react.taro.ts
  packages/nutui-taro-demo-rn/src/base/pages/button/index.config.ts
  packages/nutui-taro-demo-rn/src/base/pages/button/index.tsx
  src/packages/button/button.harmony.css
  src/packages/button/button.taro.tsx
  src/packages/button/demo.taro.tsx
Labels: size/L

#2228 fix: 新增监听文件
  gulpfile.js
  package.json
Labels: size/M

#2233 fix: 修改cellgrop内部children循环
  src/packages/cellgroup/cellgroup.taro.tsx
  src/packages/cellgroup/cellgroup.tsx
Labels: size/S

#2220 chore(image): demo代码风格优化
  src/packages/image/demos/h5/demo2.tsx
  src/packages/image/demos/h5/demo3.tsx
  src/packages/image/demos/h5/demo4.tsx
  src/packages/image/demos/h5/demo5.tsx
  src/packages/image/demos/h5/demo6.tsx
  src/packages/image/demos/taro/demo2.tsx
  src/packages/image/demos/taro/demo3.tsx
  src/packages/image/demos/taro/demo4.tsx
  src/packages/image/demos/taro/demo6.tsx
  src/packages/image/demos/taro/demo7.tsx
Labels: size/L

#2230 fix: 移除 defaultProps (1)
  src/packages/address/__test__/__snapshots__/address.spec.tsx.snap
  src/packages/backtop/backtop.taro.tsx
  src/packages/backtop/backtop.tsx
  src/packages/cascader/__tests__/__snapshots__/cascader.spec.tsx.snap
  src/packages/cell/cell.taro.tsx
  src/packages/cell/cell.tsx
  src/packages/cellgroup/cellgroup.taro.tsx
  src/packages/cellgroup/cellgroup.tsx
  src/packages/col/col.taro.tsx
  src/packages/col/col.tsx
  src/packages/divider/divider.taro.tsx
  src/packages/divider/divider.tsx
  src/packages/elevator/elevator.taro.tsx
  src/packages/elevator/elevator.tsx
  src/packages/fixednav/fixednav.taro.tsx
  src/packages/fixednav/fixednav.tsx
  src/packages/grid/grid.taro.tsx
  src/packages/grid/grid.tsx
  src/packages/griditem/griditem.taro.tsx
  src/packages/griditem/griditem.tsx
  src/packages/image/image.taro.tsx
  src/packages/image/image.tsx
  src/packages/navbar/navbar.taro.tsx
  src/packages/navbar/navbar.tsx
  src/packages/overlay/overlay.taro.tsx
  src/packages/overlay/overlay.tsx
  src/packages/row/row.taro.tsx
  src/packages/row/row.tsx
  src/packages/safearea/safearea.taro.tsx
  src/packages/safearea/safearea.tsx
  src/packages/sidenavbar/sidenavbar.taro.tsx
  src/packages/sidenavbar/sidenavbar.tsx
  src/packages/space/space.taro.tsx
  src/packages/space/space.tsx
  src/packages/sticky/sticky.taro.tsx
  src/packages/sticky/sticky.tsx
  src/packages/tabbar/tabbar.taro.tsx
  src/packages/tabbar/tabbar.tsx
  src/packages/tabs/tabs.taro.tsx
  src/packages/tabs/tabs.tsx
Labels: size/M

#2222 fix(picker): 修复连续多次打开 picker 时显示值错误
  src/packages/picker/pickerpanel.taro.tsx
Labels: size/XS

#2227 fix(imagePreview): 阻止关闭预览事件对父结构的非必要影响
  src/packages/imagepreview/imagepreview.taro.tsx
  src/packages/imagepreview/imagepreview.tsx
Labels: size/S

#2235 chore: 修改默认的微信基础库版本
  packages/nutui-taro-demo/project.config.json
Labels: size/XS

#2225 feat: indicator rn 适配
  .npmrc
  README.md
  packages/nutui-taro-demo-rn/ReadMe.md
  packages/nutui-taro-demo-rn/package.json
  packages/nutui-taro-demo-rn/src/base/pages/configprovider/index.tsx
  packages/nutui-taro-demo-rn/src/dentry1/pages/rate/index.tsx
  packages/nutui-taro-demo-rn/src/dentry1/pages/textarea/index.tsx
  packages/nutui-taro-demo-rn/styles/demo.scss
  pnpm-lock.yaml
  src/packages/button/button.harmony.css
  src/packages/button/button.scss
  src/packages/configprovider/configprovider.taro.tsx
  src/packages/configprovider/demo.taro.tsx
  src/packages/configprovider/demos/taro/demo1.tsx
  src/packages/configprovider/demos/taro/demo2.tsx
  src/packages/configprovider/demos/taro/demo5.tsx
  src/packages/indicator/demo.taro.tsx
  src/packages/indicator/demos/taro/demo2.tsx
  src/packages/indicator/demos/taro/demo3.tsx
  src/packages/indicator/demos/taro/demo4.tsx
  src/packages/indicator/doc.en-US.md
  src/packages/indicator/doc.md
  src/packages/indicator/doc.taro.md
  src/packages/indicator/doc.zh-TW.md
  src/packages/indicator/indicator.harmony.css
  src/packages/indicator/indicator.scss
  src/packages/indicator/indicator.taro.tsx
  src/packages/indicator/indicator.tsx
  src/packages/rate/demo.taro.tsx
  src/packages/textarea/demo.taro.tsx
  src/packages/textarea/textarea.harmony.css
  src/packages/textarea/textarea.scss
  src/packages/textarea/textarea.taro.tsx
  src/packages/textarea/textarea.tsx
  src/styles/variables.scss
Labels: size/XXL

#2238 fix(countdown): RN和鸿蒙适配
  packages/nutui-harmony/entry/build-profile.json5
  packages/nutui-harmony/hvigor/hvigor-config.json5
  packages/nutui-harmony/oh-package-lock.json5
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/exhibition/pages/countdown/index.config.ts
  packages/nutui-taro-demo-rn/src/exhibition/pages/countdown/index.tsx
  src/packages/button/button.scss
  src/packages/countdown/countdown.taro.tsx
  src/packages/countdown/demo.taro.tsx
  src/packages/countdown/demos/h5/demo8.tsx
  src/packages/countdown/demos/taro/demo8.tsx
  src/packages/countdown/demos/taro/demo9.tsx
Labels: size/L

#2217 Space 组件兼容 JDRN、鸿蒙端
  .npmrc
  packages/nutui-harmony/AppScope/app.json5
  packages/nutui-harmony/AppScope/resources/base/element/string.json
  packages/nutui-harmony/AppScope/resources/base/media/app_icon.png
  packages/nutui-harmony/build-profile.json5
  packages/nutui-harmony/entry/build-profile.json5
  packages/nutui-harmony/entry/src/main/module.json5
  packages/nutui-harmony/entry/src/main/resources/base/media/background.png
  packages/nutui-harmony/entry/src/main/resources/base/media/foreground.png
  packages/nutui-harmony/entry/src/main/resources/base/media/icon.png
  packages/nutui-harmony/entry/src/main/resources/base/media/layered_image.json
  packages/nutui-harmony/entry/src/main/resources/base/media/startIcon.png
  packages/nutui-harmony/entry/src/ohosTest/ets/testability/TestAbility.ets
  packages/nutui-harmony/entry/src/ohosTest/resources/base/media/icon.png
  packages/nutui-harmony/hvigor/hvigor-config.json5
  packages/nutui-harmony/hvigor/hvigor-wrapper.js
  packages/nutui-harmony/oh-package-lock.json5
  packages/nutui-harmony/oh-package.json5
  packages/nutui-taro-demo-rn/src/layout/pages/space/index.tsx
  src/packages/space/demo.taro.tsx
  src/packages/space/demos/taro/demo5.tsx
  src/packages/space/demos/taro/demo6.tsx
  src/packages/space/space.harmony.css
  src/packages/space/space.scss
  src/packages/space/space.taro.tsx
  src/packages/space/space.tsx
Labels: size/L

#2234 feat(empty): 适配 RN、鸿蒙
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/feedback/pages/empty/index.tsx
  src/packages/empty/demo.taro.tsx
  src/packages/empty/demos/taro/demo5.tsx
  src/packages/empty/demos/taro/demo6.tsx
  src/packages/empty/empty.harmony.css
  src/packages/empty/empty.scss
  src/packages/empty/empty.taro.tsx
  src/packages/empty/empty.tsx
Labels: size/L

#2244 chore(image): 官网taro的demo显示与h5不一致
  src/packages/image/demos/h5/demo2.tsx
  src/packages/image/demos/h5/demo3.tsx
  src/packages/image/demos/h5/demo4.tsx
  src/packages/image/demos/taro/demo2.tsx
  src/packages/image/demos/taro/demo3.tsx
  src/packages/image/demos/taro/demo4.tsx
Labels: size/S

#2240 fix(input): 修复特殊场景下自动清除失效问题
  src/packages/input/input.taro.tsx
  src/packages/input/input.tsx
Labels: size/S

#2252 fix(menu): 选项文字很多时右侧箭头展示异常
  src/packages/menu/menu.scss
  src/packages/menuitem/menuitem.scss
  src/packages/menuitem/menuitem.taro.tsx
Labels: size/XS

#2241 fix(table): 修复部分由于场景下width未生效导致的一些问题
  src/packages/table/demos/h5/demo1.tsx
  src/packages/table/demos/h5/demo10.tsx
  src/packages/table/demos/h5/demo11.tsx
  src/packages/table/demos/h5/demo12.tsx
  src/packages/table/demos/h5/demo13.tsx
  src/packages/table/demos/h5/demo2.tsx
  src/packages/table/demos/h5/demo3.tsx
  src/packages/table/demos/h5/demo4.tsx
  src/packages/table/demos/h5/demo5.tsx
  src/packages/table/demos/h5/demo6.tsx
  src/packages/table/demos/h5/demo7.tsx
  src/packages/table/demos/h5/demo8.tsx
  src/packages/table/demos/h5/demo9.tsx
  src/packages/table/demos/taro/demo1.tsx
  src/packages/table/demos/taro/demo10.tsx
  src/packages/table/demos/taro/demo11.tsx
  src/packages/table/demos/taro/demo12.tsx
  src/packages/table/demos/taro/demo13.tsx
  src/packages/table/demos/taro/demo2.tsx
  src/packages/table/demos/taro/demo3.tsx
  src/packages/table/demos/taro/demo4.tsx
  src/packages/table/demos/taro/demo5.tsx
  src/packages/table/demos/taro/demo6.tsx
  src/packages/table/demos/taro/demo7.tsx
  src/packages/table/demos/taro/demo8.tsx
  src/packages/table/demos/taro/demo9.tsx
  src/packages/table/table.scss
Labels: size/L

#2253 fix: 关于checkbox&tabs的doc与demo修改
  src/packages/checkbox/doc.en-US.md
  src/packages/checkbox/doc.md
  src/packages/checkbox/doc.taro.md
  src/packages/checkbox/doc.zh-TW.md
  src/packages/tabs/demos/taro/demo12.tsx
Labels: size/S

#2255 fix(Cell): 鸿蒙适配
  packages/nutui-harmony/hvigorw
  packages/nutui-harmony/hvigorw.bat
  packages/nutui-harmony/oh-package.json5
  packages/nutui-taro-demo-rn/styles/demo.scss
  packages/nutui-taro-demo/src/app.scss
  scripts/rn/copy-file.js
  src/packages/button/button.harmony.css
  src/packages/button/button.scss
  src/packages/cell/cell.harmony.css
  src/packages/cell/cell.scss
  src/packages/cell/cell.taro.tsx
  src/packages/cell/cell.tsx
  src/packages/cell/demos/taro/demo3.tsx
  src/packages/cell/demos/taro/demo6.tsx
  src/packages/cell/doc.en-US.md
  src/packages/cell/doc.md
  src/packages/cell/doc.taro.md
  src/packages/cell/doc.zh-TW.md
  src/packages/cellgroup/cellgroup.harmony.css
  src/packages/cellgroup/cellgroup.scss
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/L

#2249 feat(tag): 适配 RN、鸿蒙
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/exhibition/pages/tag/index.tsx
  src/packages/tag/demo.taro.tsx
  src/packages/tag/demos/h5/demo4.tsx
  src/packages/tag/demos/taro/demo2.tsx
  src/packages/tag/demos/taro/demo4.tsx
  src/packages/tag/tag.harmony.css
  src/packages/tag/tag.scss
  src/packages/tag/tag.taro.tsx
  src/packages/tag/tag.tsx
Labels: size/L

#2261 chore: 增加构建卡点
  .github/workflows/ci.yml
  src/packages/button/button.taro.tsx
  src/packages/card/__test__/__snapshots__/card.spec.tsx.snap
  src/packages/card/__test__/card.spec.tsx
  src/packages/cascader/__tests__/cascader.spec.tsx
  src/packages/cell/__test__/__snapshots__/cell.spec.tsx.snap
  src/packages/cell/cell.taro.tsx
  src/packages/cellgroup/__test__/__snapshots__/cellgroup.spec.tsx.snap
  src/packages/cellgroup/cellgroup.taro.tsx
  src/packages/cellgroup/cellgroup.tsx
  src/packages/configprovider/types.ts
  src/packages/countdown/countdown.taro.tsx
  src/packages/empty/__test__/__snapshots__/empty.spec.tsx.snap
  src/packages/empty/__test__/empty.spec.tsx
  src/packages/formitem/formitem.taro.tsx
  src/packages/indicator/__test__/__snapshots__/indicator.spec.tsx.snap
  src/packages/price/__test__/__snapshots__/price.spec.tsx.snap
  src/packages/space/__test__/__snapshots__/space.spec.tsx.snap
  src/packages/space/__test__/space.spec.tsx
  src/packages/space/space.taro.tsx
  src/packages/tag/__test__/tag.spec.tsx
  src/packages/textarea/__test__/__snapshots__/textarea.spec.tsx.snap
Labels: size/L

#2260 fix(circleprogress): update demo
  src/packages/circleprogress/demos/h5/demo3.tsx
  src/packages/circleprogress/demos/taro/demo3.tsx
Labels: size/XS

#2265 docs(uploader): update
  src/packages/uploader/doc.en-US.md
  src/packages/uploader/doc.md
  src/packages/uploader/doc.taro.md
  src/packages/uploader/doc.zh-TW.md
Labels: size/S

#2266 fix(space): 隐藏 demo4
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  src/packages/space/demo.taro.tsx
Labels: size/XS

#2270 fix: 更新变量文件
  src/styles/theme-default.scss
  src/styles/variables.scss
Labels: size/L

#2279 chore(tag): css样式变量修复
  src/styles/variables.scss
Labels: size/XS

#2274 chore(deps): bump taro to 4.0.0-beta.75
  package.json
  packages/nutui-taro-demo-rn/package.json
  packages/nutui-taro-demo/config/index.js
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
Labels: size/XXL

#2247 fix(FormItem): 修复initialValue属性初始化未被正确加入到Formstore中导致的问题
  src/packages/form/__tests__/form.spec.tsx
  src/packages/formitem/formitem.taro.tsx
  src/packages/formitem/formitem.tsx
Labels: size/M

#2281 fix(imagepreview): 阻止冒泡，防止点击图片关闭
  src/packages/imagepreview/imagepreview.taro.tsx
  src/packages/imagepreview/imagepreview.tsx
Labels: size/XS

#2282 fix(input): placeholder 无法设置空字符串
  src/packages/input/input.taro.tsx
  src/packages/input/input.tsx
Labels: size/S

#2285 fix: ActionSheet 去掉无意义的padding，popup 已不再暴露
  src/packages/actionsheet/actionsheet.scss
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/XS

#2286 fix: ActionSheet 增加安全区处理
  pnpm-lock.yaml
  src/packages/actionsheet/actionsheet.scss
  src/packages/actionsheet/actionsheet.taro.tsx
  src/packages/actionsheet/actionsheet.tsx
Labels: size/XXL

#2288 feat: 签名组件增加当没有签名或已清空的情况下的参数暴露
  src/packages/signature/__test__/__snapshots__/signature.spec.tsx.snap
  src/packages/signature/__test__/signature.spec.tsx
  src/packages/signature/demos/h5/demo1.tsx
  src/packages/signature/demos/taro/demo1.tsx
  src/packages/signature/doc.en-US.md
  src/packages/signature/doc.md
  src/packages/signature/doc.taro.md
  src/packages/signature/doc.zh-TW.md
  src/packages/signature/signature.taro.tsx
  src/packages/signature/signature.tsx
Labels: size/L

#2271 feat(grid): 适配 RN、鸿蒙
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/layout/pages/grid/index.tsx
  src/packages/grid/__test__/__snapshots__/grid.spec.tsx.snap
  src/packages/grid/demo.taro.tsx
  src/packages/grid/demo.tsx
  src/packages/grid/demos/taro/demo1.tsx
  src/packages/grid/demos/taro/demo10.tsx
  src/packages/grid/demos/taro/demo2.tsx
  src/packages/grid/demos/taro/demo3.tsx
  src/packages/grid/demos/taro/demo4.tsx
  src/packages/grid/demos/taro/demo5.tsx
  src/packages/grid/demos/taro/demo6.tsx
  src/packages/grid/demos/taro/demo7.tsx
  src/packages/grid/demos/taro/demo8.tsx
  src/packages/grid/demos/taro/demo9.tsx
  src/packages/grid/grid.harmony.css
  src/packages/grid/grid.scss
  src/packages/grid/grid.taro.tsx
  src/packages/griditem/griditem.harmony.css
  src/packages/griditem/griditem.scss
  src/packages/griditem/griditem.taro.tsx
  src/packages/griditem/griditem.tsx
Labels: size/L

#2275 fix(divider): 适配鸿蒙和RN
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/layout/pages/divider/index.config.ts
  packages/nutui-taro-demo-rn/src/layout/pages/divider/index.tsx
  src/packages/divider/__test__/__snapshots__/divider.spec.tsx.snap
  src/packages/divider/demo.taro.tsx
  src/packages/divider/demo.tsx
  src/packages/divider/demos/h5/demo6.tsx
  src/packages/divider/demos/taro/demo4.tsx
  src/packages/divider/demos/taro/demo5.tsx
  src/packages/divider/demos/taro/demo6.tsx
  src/packages/divider/divider.harmony.css
  src/packages/divider/divider.scss
  src/packages/divider/divider.taro.tsx
  src/packages/divider/divider.tsx
  src/packages/divider/doc.en-US.md
  src/packages/divider/doc.md
  src/packages/divider/doc.taro.md
  src/packages/divider/doc.zh-TW.md
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/L

#2300 chore: fix typos
  src/packages/noticebar/doc.en-US.md
  src/packages/shortpassword/doc.en-US.md
  src/packages/swipe/doc.md
  src/packages/tabbar/doc.en-US.md
  src/packages/table/doc.en-US.md
Labels: size/S

#2297 feat: 新增resultPage组件，四端&v13适配完成
  package.json
  packages/nutui-harmony/entry/src/main/module.json5
  packages/nutui-harmony/entry/src/main/resources/base/profile/main_pages.json
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/app.config.ts
  packages/nutui-taro-demo-rn/src/feedback/pages/resultpage/index.config.ts
  packages/nutui-taro-demo-rn/src/feedback/pages/resultpage/index.tsx
  packages/nutui-taro-demo/src/app.config.ts
  src/config.json
  src/packages/button/button.harmony.css
  src/packages/button/button.scss
  src/packages/configprovider/types.ts
  src/packages/resultpage/__test__/resultpage.spec.tsx
  src/packages/resultpage/demo.taro.tsx
  src/packages/resultpage/demo.tsx
  src/packages/resultpage/demos/h5/demo1.tsx
  src/packages/resultpage/demos/h5/demo2.tsx
  src/packages/resultpage/demos/h5/demo3.tsx
  src/packages/resultpage/demos/h5/demo4.tsx
  src/packages/resultpage/demos/h5/demo5.tsx
  src/packages/resultpage/demos/taro/demo1.tsx
  src/packages/resultpage/demos/taro/demo2.tsx
  src/packages/resultpage/demos/taro/demo3.tsx
  src/packages/resultpage/demos/taro/demo4.tsx
  src/packages/resultpage/demos/taro/demo5.tsx
  src/packages/resultpage/doc.en-US.md
  src/packages/resultpage/doc.md
  src/packages/resultpage/doc.taro.md
  src/packages/resultpage/doc.zh-TW.md
  src/packages/resultpage/index.taro.ts
  src/packages/resultpage/index.ts
  src/packages/resultpage/resultpage.harmony.css
  src/packages/resultpage/resultpage.scss
  src/packages/resultpage/resultpage.taro.tsx
  src/packages/resultpage/resultpage.tsx
  src/packages/resultpage/types.ts
  src/styles/variables.scss
Labels: size/XXL

#2303 fix(empty): 按钮部分实现和resultPage保持一致
  src/packages/empty/demos/h5/demo1.tsx
  src/packages/empty/demos/taro/demo1.tsx
  src/packages/empty/empty.harmony.css
  src/packages/empty/empty.scss
  src/packages/empty/empty.taro.tsx
  src/packages/empty/empty.tsx
  src/packages/empty/types.ts
Labels: size/L

#2304 chore(demo): 更新组件引用方式
  .github/workflows/ci.yml
  src/packages/audio/demo.taro.tsx
  src/packages/avatar/demo.taro.tsx
  src/packages/badge/demo.taro.tsx
  src/packages/button/demo.taro.tsx
  src/packages/circleprogress/demo.taro.tsx
  src/packages/divider/demo.taro.tsx
  src/packages/icon/demo.taro.tsx
  src/packages/icon/demos/taro/demo7.tsx
  src/packages/image/demo.taro.tsx
  src/packages/inputnumber/demo.taro.tsx
  src/packages/overlay/demo.taro.tsx
  src/packages/pagination/demo.taro.tsx
  src/packages/price/demo.taro.tsx
  src/packages/progress/demo.taro.tsx
  src/packages/radio/demo.taro.tsx
  src/packages/rate/demo.taro.tsx
  src/packages/skeleton/demo.taro.tsx
  src/packages/space/demo.taro.tsx
  src/packages/sticky/demo.taro.tsx
  src/packages/swipe/demo.taro.tsx
  src/packages/table/demo.taro.tsx
  src/packages/virtuallist/demo.taro.tsx
Labels: size/M

#2259 fix(picker): 函数调用之前检查 locale 是否已经定义
  src/packages/picker/picker.taro.tsx
  src/packages/picker/picker.tsx
Labels: size/XS

#2302 fix(InputNumber): 扩大点击区域
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/inputnumber/inputnumber.tsx
Labels: size/S

#2293 fix: safearea for ac
  src/packages/actionsheet/actionsheet.scss
Labels: size/XS

#2195 Button Taro版本新增 button原始类型属性支持 Uploader Taro上传组件按钮原始类型设置为type=button
  src/packages/button/button.taro.tsx
  src/packages/uploader/uploader.taro.tsx
Labels: size/S

#2308 fix(cascader): onPathChange is not a function
  src/packages/cascader/cascader.taro.tsx
  src/packages/cascader/cascader.tsx
Labels: size/XS

#2269 fix(notify): RN和鸿蒙适配
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/feedback/pages/notify/index.config.ts
  packages/nutui-taro-demo-rn/src/feedback/pages/notify/index.tsx
  src/packages/notify/demo.taro.tsx
  src/packages/notify/demos/taro/demo2.tsx
  src/packages/notify/demos/taro/demo4.tsx
  src/packages/notify/doc.en-US.md
  src/packages/notify/doc.md
  src/packages/notify/doc.taro.md
  src/packages/notify/doc.zh-TW.md
  src/packages/notify/notify.harmony.css
  src/packages/notify/notify.scss
  src/packages/notify/notify.taro.tsx
  src/styles/variables.scss
  src/utils/platform-taro.ts
Labels: size/L
