Repository jdf2e/nutui-react, pull requests merged in 2024-11, with the labels that each got.

#2685 fix(tabs): clicked tabs should be entirely visible & fix ci install failed
  pnpm-lock.yaml
  src/packages/configprovider/types.ts
  src/packages/range/range.taro.tsx
  src/packages/range/range.tsx
  src/packages/tabs/tabs.taro.tsx
Labels: size/S, 2.x

#2673 feat: add plugin to remove rtl
  packages/nutui-optimize-css/README.md
  packages/nutui-optimize-css/build.config.ts
  packages/nutui-optimize-css/package.json
  packages/nutui-optimize-css/src/index.ts
  packages/nutui-optimize-css/src/postcss-plugins/index.ts
  packages/nutui-optimize-css/test/__snapshots__/remove-rtl.test.ts.snap
  packages/nutui-optimize-css/test/__snapshots__/replace-css-var.test.ts.snap
  packages/nutui-optimize-css/test/remove-rtl.test.ts
  packages/nutui-optimize-css/test/replace-css-var.test.ts
  packages/nutui-optimize-css/test/variables.css
  packages/nutui-optimize-css/test/variables.scss
  packages/nutui-optimize-css/tsconfig.json
  packages/nutui-optimize-css/vitest.config.ts
  packages/nutui-taro-demo/config/index.js
  pnpm-lock.yaml
Labels: size/XXL

#2687 chore: ci auto branch label 【support current repo】
  .github/workflows/ci.yml
Labels: size/L, 2.x

#2689 chore: auto add label in ci process
  .github/workflows/ci.yml
Labels: size/M, 3.x

#2683 fix(infinite): loadingText未居中
  src/packages/infiniteloading/demo.taro.tsx
  src/packages/infiniteloading/infiniteloading.taro.tsx
Labels: size/S, 3.x

#2684 fix(TextArea&Skeleton): 增加disabled样式,调整autosize demo,删除无用样式
  src/packages/skeleton/demos/taro/demo5.tsx
  src/packages/skeleton/skeleton.harmony.css
  src/packages/textarea/demos/h5/demo4.tsx
  src/packages/textarea/demos/taro/demo4.tsx
  src/packages/textarea/textarea.harmony.css
  src/packages/textarea/textarea.scss
  src/packages/textarea/textarea.taro.tsx
Labels: size/L, 3.x

#2690 chore: ci
  .github/workflows/ci.yml
Labels: size/S

#2692 chore: ci optimize
  .github/workflows/ci.yml
Labels: size/M, 2.x

#2698 chore: delete the .git directory to prevent accidental commits
  scripts/harmony/clone-jdharmony.js
Labels: size/XS, 3.x

#2634 docs: 官方主题入口
  src/config.json
Labels: size/XS, 2.x

#2703 chore: jdesign 主题
  packages/nutui-replace-icons/package.json
  packages/nutui-taro-demo/config/prod.js
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
Labels: size/XL, 2.x

#2299 feat: Toast RN & 鸿蒙 适配
  package.json
  pnpm-lock.yaml
  src/config.json
  src/packages/overlay/overlay.harmony.css
  src/packages/toast/Notification.tsx
  src/packages/toast/__test__/toast.spec.tsx
  src/packages/toast/demo.taro.tsx
  src/packages/toast/demos/h5/demo1.tsx
  src/packages/toast/demos/h5/demo5.tsx
  src/packages/toast/demos/taro/demo1.tsx
  src/packages/toast/demos/taro/demo2.tsx
  src/packages/toast/demos/taro/demo5.tsx
  src/packages/toast/toast.harmony.css
  src/packages/toast/toast.scss
  src/packages/toast/toast.taro.tsx
  src/packages/toast/toast.tsx
  src/styles/variables-jrkf.scss
Labels: size/XL, 3.x

#2540 feat(trendarrow): 多端适配
  src/config.json
  src/packages/trendarrow/trendarrow.harmony.css
  src/packages/trendarrow/trendarrow.scss
  src/packages/trendarrow/trendarrow.taro.tsx
Labels: size/S, 3.x

#2712 feat(pagination): update icon
  src/packages/pagination/demos/taro/demo5.tsx
Labels: size/XS, 3.x

#2711 feat(input): update icon
  src/packages/input/demos/taro/demo13.tsx
  src/packages/input/demos/taro/demo6.tsx
  src/packages/input/demos/taro/demo9.tsx
  src/packages/input/input.scss
  src/packages/input/input.taro.tsx
Labels: size/M, 3.x

#2710 feat(grid): update icon
  src/packages/grid/demos/taro/demo1.tsx
  src/packages/grid/demos/taro/demo10.tsx
  src/packages/grid/demos/taro/demo2.tsx
  src/packages/grid/demos/taro/demo3.tsx
  src/packages/grid/demos/taro/demo4.tsx
  src/packages/grid/demos/taro/demo5.tsx
  src/packages/grid/demos/taro/demo6.tsx
  src/packages/grid/demos/taro/demo7.tsx
  src/packages/grid/demos/taro/demo8.tsx
Labels: size/M, 3.x

#2709 feat(button): update icon
  src/packages/button/button.taro.tsx
  src/packages/button/demos/taro/demo4.tsx
  src/packages/button/demos/taro/demo5.tsx
Labels: size/XL, 3.x

#2714 feat(pulltorefresh): update icon
  src/packages/pulltorefresh/pulltorefresh.taro.tsx
Labels: size/XS, 3.x

#2713 feat(tag): update icon
  src/packages/tag/demos/taro/demo2.tsx
  src/packages/tag/tag.taro.tsx
Labels: size/M, 3.x

#2717 fix(hack): show xml
  packages/nutui-taro-demo/src/pages/index/index.tsx
Labels: size/XS, 3.x

#2594 feat(navbar): 多端适配，demo icon使用占位符
  package.json
  pnpm-lock.yaml
  src/config.json
  src/packages/navbar/__test__/__snapshots__/navbar.spec.tsx.snap
  src/packages/navbar/demo.scss
  src/packages/navbar/demos/h5/demo1.tsx
  src/packages/navbar/demos/h5/demo2.tsx
  src/packages/navbar/demos/h5/demo3.tsx
  src/packages/navbar/demos/taro/demo1.tsx
  src/packages/navbar/demos/taro/demo2.tsx
  src/packages/navbar/demos/taro/demo3.tsx
  src/packages/navbar/navbar.harmony.css
  src/packages/navbar/navbar.scss
  src/packages/navbar/navbar.taro.tsx
  src/packages/navbar/navbar.tsx
  src/styles/variables.scss
Labels: size/XL, 3.x

#2720 feat(video): cross-platform compatibility
  packages/nutui-taro-demo/src/pages/index/index.tsx
  pnpm-lock.yaml
  src/config.json
  src/packages/video/demo.taro.tsx
  src/packages/video/demos/taro/demo1.tsx
  src/packages/video/demos/taro/demo2.tsx
  src/packages/video/demos/taro/demo3.tsx
  src/packages/video/demos/taro/demo4.tsx
  src/packages/video/demos/taro/demo5.tsx
  src/packages/video/demos/taro/demo6.tsx
  src/packages/video/demos/taro/demo7.tsx
  src/packages/video/video.taro.tsx
Labels: size/M, 3.x

#2723 chore: icons version
  package.json
  pnpm-lock.yaml
  src/packages/input/input.harmony.css
Labels: size/S, 3.x

#2704 fix: vite5 relative warnings and deprecated usage
  .env
  src/sites/doc/components/demoblock/codeblock.tsx
  src/sites/theme/router.ts
Labels: size/S, 3.x

#2613 feat: auto import css plugin
  .gitignore
  .vite/deps_temp_67a06ddd/package.json
  packages/nutui-auto-import/.editorconfig
  packages/nutui-auto-import/.gitattributes
  packages/nutui-auto-import/.gitignore
  packages/nutui-auto-import/LICENSE
  packages/nutui-auto-import/README.md
  packages/nutui-auto-import/babel.config.json
  packages/nutui-auto-import/package.json
  packages/nutui-auto-import/pnpm-lock.yaml
  packages/nutui-auto-import/src/api.ts
  packages/nutui-auto-import/src/core/options.ts
  packages/nutui-auto-import/src/esbuild.ts
  packages/nutui-auto-import/src/index.ts
  packages/nutui-auto-import/src/rolldown.ts
  packages/nutui-auto-import/src/rollup.ts
  packages/nutui-auto-import/src/rspack.ts
  packages/nutui-auto-import/src/vite.ts
  packages/nutui-auto-import/src/webpack.ts
  packages/nutui-auto-import/tests/__snapshots__/rollup.test.ts.snap
  packages/nutui-auto-import/tests/fixtures/basic.jsx
  packages/nutui-auto-import/tests/rollup.test.ts
  packages/nutui-auto-import/tsconfig.json
  packages/nutui-auto-import/tsup.config.ts
  packages/nutui-auto-import/vitest.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/XXL, 3.x

#2657 fix(searchbar): 多端适配
  src/config.json
  src/packages/searchbar/demo.taro.tsx
  src/packages/searchbar/demos/taro/demo6.tsx
  src/packages/searchbar/demos/taro/demo7.tsx
  src/packages/searchbar/searchbar.harmony.css
  src/packages/searchbar/searchbar.scss
  src/packages/searchbar/searchbar.taro.tsx
Labels: size/L, 3.x

#2725 fix(hoverbutton): 恢复icon,简化demo
  src/packages/hoverbutton/demo.taro.tsx
  src/packages/hoverbutton/demos/taro/demo1-rn.tsx
  src/packages/hoverbutton/demos/taro/demo2-rn.tsx
  src/packages/hoverbutton/demos/taro/demo3-rn.tsx
  src/packages/hoverbutton/demos/taro/demo3.tsx
  src/packages/hoverbutton/demos/taro/demo4-rn.tsx
  src/packages/hoverbutton/demos/taro/demo4.tsx
Labels: size/L, 3.x

#2733 feat(loading): 适配鸿蒙
  src/config.json
Labels: size/XS, 3.x

#2721 feat: radio adaptation
  src/config.json
  src/packages/radio/demos/taro/demo8.tsx
  src/packages/radio/demos/taro/demo9.tsx
  src/packages/radio/index.taro.ts
  src/packages/radio/index.ts
  src/packages/radio/radio.scss
  src/packages/radio/radio.taro.tsx
  src/packages/radio/radio.tsx
  src/packages/radiogroup/radiogroup.taro.tsx
  src/packages/radiogroup/radiogroup.tsx
Labels: size/M, 3.x

#2620 fix(badge): 四端适配
  scripts/rn/copy-file.js
  src/config.json
  src/packages/badge/__test__/__snapshots__/badge.spec.tsx.snap
  src/packages/badge/__test__/badge.spec.tsx
  src/packages/badge/badge.harmony.css
  src/packages/badge/badge.scss
  src/packages/badge/badge.taro.tsx
  src/packages/badge/badge.tsx
  src/packages/badge/demo.taro.tsx
  src/packages/badge/demo.tsx
  src/packages/badge/demos/h5/demo7.tsx
  src/packages/badge/demos/taro/demo1.tsx
  src/packages/badge/demos/taro/demo2.tsx
  src/packages/badge/demos/taro/demo3.tsx
  src/packages/badge/demos/taro/demo4.tsx
  src/packages/badge/demos/taro/demo5.tsx
  src/packages/badge/demos/taro/demo6.tsx
  src/packages/badge/demos/taro/demo7.tsx
  src/packages/badge/demos/taro/demo8.tsx
  src/styles/variables.scss
Labels: size/XL, 3.x

#2728 feat(image): support icon demo
  src/packages/image/demo.taro.tsx
  src/packages/image/demos/taro/demo1.tsx
  src/packages/image/demos/taro/demo2.tsx
  src/packages/image/demos/taro/demo3.tsx
  src/packages/image/demos/taro/demo4.tsx
  src/packages/image/demos/taro/demo5.tsx
  src/packages/image/demos/taro/demo6.tsx
  src/packages/image/demos/taro/demo7.tsx
  src/packages/image/image.taro.tsx
Labels: size/L, 3.x

#2735 fix: radio type
  src/packages/radio/radio.taro.tsx
  src/packages/radio/radio.tsx
  src/packages/radiogroup/radiogroup.taro.tsx
Labels: size/S, 3.x

#2724 fix(backtop): 恢复icon
  src/packages/backtop/demo.taro.tsx
  src/packages/backtop/demos/taro/demo1.tsx
  src/packages/backtop/demos/taro/demo5.tsx
Labels: size/M, 3.x

#2742 chore: fix icon svg
  .gitignore
  package.json
  packages/nutui-taro-demo/config/index.js
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
Labels: size/XXL, 3.x

#2745 fix(safearea): harmony适配
  src/config.json
  src/packages/safearea/demos/taro/demo1.tsx
  src/packages/safearea/safearea.harmony.css
  src/packages/safearea/safearea.scss
Labels: size/S, 3.x

#2749 fix: taro demo build failed
  packages/nutui-taro-demo/package.json
  packages/nutui-taro-demo/yarn.lock
  src/packages/popup/index.rn.ts
  src/packages/popup/popup.rn.tsx
Labels: size/XXL, 3.x

#2753 chore: ci optimization
  .github/workflows/ci.yml
Labels: size/XS, 3.x

#2752 feat(v14): pagination
  .github/workflows/ci.yml
  gulpfile.js
  packages/nutui-taro-demo/scripts/taro/generate-nutui-taro.js
  scripts/taro/generate-nutui-taro.js
  src/config.json
  src/packages/pagination/pagination.scss
  src/packages/pagination/pagination.taro.tsx
  src/packages/pagination/pagination.tsx
  src/styles/variables.scss
Labels: size/L, 3.x

#2756 chore: ci update
  .github/workflows/add-label.yml
  .github/workflows/ci.yml
Labels: size/M, 3.x

#2748 fix(textarea): handle undefined placeholder explicitly
  src/packages/textarea/textarea.taro.tsx
  src/packages/textarea/textarea.tsx
Labels: size/XS, 2.x

#2761 fix(tag): modify svg color
  src/packages/tag/tag.scss
Labels: size/XS, 3.x

#2754 fix(rate): 多端适配
  src/config.json
  src/packages/configprovider/demos/taro/demo1.tsx
  src/packages/configprovider/demos/taro/demo2.tsx
  src/packages/rate/demo.taro.tsx
  src/packages/rate/rate.harmony.css
  src/packages/rate/rate.scss
Labels: size/L, 3.x

#2737 feat(v14): button adaptation
  src/packages/button/button.scss
  src/packages/button/doc.en-US.md
  src/packages/button/doc.md
  src/packages/button/doc.taro.md
  src/packages/button/doc.zh-TW.md
  src/styles/variables.scss
Labels: size/L, 3.x

#2730 feat: checkbox adaptation
  src/config.json
  src/packages/checkbox/checkbox.taro.tsx
  src/packages/checkbox/checkbox.tsx
  src/packages/checkbox/demos/h5/demo2.tsx
  src/packages/checkbox/demos/h5/demo3.tsx
  src/packages/checkbox/demos/taro/demo1.tsx
  src/packages/checkbox/demos/taro/demo13.tsx
  src/packages/checkbox/demos/taro/demo2.tsx
  src/packages/checkbox/demos/taro/demo3.tsx
  src/packages/checkbox/demos/taro/demo8.tsx
  src/packages/checkbox/demos/taro/demo9.tsx
  src/packages/checkbox/index.taro.ts
  src/packages/checkbox/index.ts
  src/packages/checkboxgroup/checkboxgroup.scss
Labels: size/L, 3.x

#2770 docs(infiniteLoading): optimize target description
  src/packages/infiniteloading/doc.en-US.md
  src/packages/infiniteloading/doc.md
  src/packages/infiniteloading/doc.taro.md
  src/packages/infiniteloading/doc.zh-TW.md
Labels: size/L, 2.x

#2775 fix(toast): svg color
  src/packages/toast/demos/taro/demo2.tsx
Labels: size/XS, 3.x

#2769 fix(pagination): color of icon
  src/packages/pagination/pagination.taro.tsx
  src/utils/add-color-for-harmony.ts
Labels: size/M, 3.x

#2778 fix(Ellipsis): Correction of text（纠正错别字）
  scripts/properties.json
  src/packages/ellipsis/doc.md
  src/packages/ellipsis/doc.taro.md
Labels: size/XS, 3.x

#2777 fix(avatar): svg color
  src/packages/avatar/avatar.taro.tsx
  src/packages/avatar/demos/taro/demo6.tsx
Labels: size/XS, 3.x

#2773 fix(popup): display should not trigger the scrollview to update
  src/packages/popup/popup.taro.tsx
Labels: size/S, 2.x

#2700 fix(AnimatingNumbers): 多端适配
  src/config.json
  src/packages/animatingnumbers/__tests__/animatingnumbers.spec.tsx
  src/packages/animatingnumbers/animatingnumbers.harmony.css
  src/packages/animatingnumbers/countup.scss
  src/packages/animatingnumbers/countup.taro.tsx
  src/packages/animatingnumbers/countup.tsx
Labels: size/L, 3.x

#2781 fix: modify ts
  src/packages/animatingnumbers/countup.taro.tsx
Labels: size/XS, 3.x

#2783 feat(Tabbar): harmony adaptation
  src/config.json
  src/packages/tabbaritem/tabbaritem.scss
  src/packages/tabbaritem/tabbaritem.taro.tsx
  src/utils/add-color-for-harmony.ts
Labels: size/M, 3.x

#2788 feat(Icon): icon harmony adaptation
  package.json
  pnpm-lock.yaml
  src/config.json
  src/packages/icon/demo.taro.tsx
  src/packages/icon/demos/taro/demo1.tsx
  src/packages/icon/demos/taro/demo2.tsx
  src/packages/icon/demos/taro/demo3.tsx
  src/packages/icon/demos/taro/demo4.tsx
  src/packages/icon/demos/taro/demo5.tsx
  src/packages/icon/demos/taro/demo6.tsx
  src/packages/icon/demos/taro/demo7.tsx
Labels: size/XXL, 3.x

#2790 feat(Dialog): harmony adaptation
  src/config.json
  src/packages/dialog/demos/h5/demo6.tsx
  src/packages/dialog/demos/taro/demo6.tsx
  src/packages/dialog/demos/taro/demo7.tsx
  src/packages/dialog/dialog.scss
Labels: size/M, 3.x

#2701 fix(countdown): 适配v14 && type增加text类型
  packages/nutui-taro-demo/src/app.config.ts
  src/config.json
  src/packages/countdown/__test__/__snapshots__/countdown.spec.tsx.snap
  src/packages/countdown/__test__/countdown.spec.tsx
  src/packages/countdown/countdown.scss
  src/packages/countdown/countdown.taro.tsx
  src/packages/countdown/countdown.tsx
  src/packages/countdown/demos/h5/demo1.tsx
  src/packages/countdown/demos/h5/demo3.tsx
  src/packages/countdown/demos/h5/demo4.tsx
  src/packages/countdown/demos/taro/demo1.tsx
  src/packages/countdown/demos/taro/demo3.tsx
  src/packages/countdown/demos/taro/demo4.tsx
  src/packages/countdown/doc.en-US.md
  src/packages/countdown/doc.md
  src/packages/countdown/doc.taro.md
  src/packages/countdown/doc.zh-TW.md
  src/packages/countdown/index.taro.ts
  src/packages/countdown/index.ts
  src/packages/countdown/types.ts
  src/styles/variables.scss
Labels: size/XL, 3.x

#2791 feat(imagepreview): harmony adaptation
  packages/nutui-taro-demo/src/app.config.ts
  src/config.json
  src/packages/imagepreview/demos/taro/demo1.tsx
  src/packages/imagepreview/demos/taro/demo2.tsx
  src/packages/imagepreview/demos/taro/demo3.tsx
  src/packages/imagepreview/demos/taro/demo4.tsx
  src/packages/imagepreview/demos/taro/demo5.tsx
  src/packages/imagepreview/demos/taro/demo6.tsx
  src/packages/imagepreview/demos/taro/demo7.tsx
  src/packages/imagepreview/imagepreview.scss
Labels: size/L

#2798 refactor: add global scss
  packages/nutui-taro-demo/src/app.scss
  scripts/build-taro.mjs
  scripts/build.mjs
  src/sites/mobile/App.scss
  src/styles/jd-font.scss
Labels: size/M, 3.x

#2801 docs(infiniteloading): remove deprecated usage
  src/packages/infiniteloading/doc.en-US.md
  src/packages/infiniteloading/doc.md
  src/packages/infiniteloading/doc.taro.md
  src/packages/infiniteloading/doc.zh-TW.md
Labels: size/XS, 2.x

#2789 fix(Table): 给个默认背景色，解决在小程序中固定列与滚动内列混合
  src/packages/table/table.scss
Labels: size/XS, 2.x

#2741 fix(resultpage): 适配 V14
  src/config.json
  src/packages/resultpage/__test__/__snapshots__/resultpage.spec.tsx.snap
  src/packages/resultpage/demo.taro.tsx
  src/packages/resultpage/demos/h5/demo1.tsx
  src/packages/resultpage/demos/h5/demo2.tsx
  src/packages/resultpage/demos/h5/demo3.tsx
  src/packages/resultpage/demos/h5/demo4.tsx
  src/packages/resultpage/demos/taro/demo1.tsx
  src/packages/resultpage/demos/taro/demo2.tsx
  src/packages/resultpage/demos/taro/demo3.tsx
  src/packages/resultpage/demos/taro/demo4.tsx
  src/packages/resultpage/doc.en-US.md
  src/packages/resultpage/doc.md
  src/packages/resultpage/doc.taro.md
  src/packages/resultpage/doc.zh-TW.md
  src/packages/resultpage/resultpage.scss
  src/packages/resultpage/resultpage.taro.tsx
  src/packages/resultpage/resultpage.tsx
  src/packages/resultpage/types.ts
  src/styles/variables.scss
Labels: size/L, 3.x

#2771 feat(grid): v14
  src/config.json
  src/packages/animatingnumbers/countup.taro.tsx
  src/packages/grid/__test__/__snapshots__/grid.spec.tsx.snap
  src/packages/grid/__test__/grid.spec.tsx
  src/packages/grid/demo.taro.tsx
  src/packages/grid/demo.tsx
  src/packages/grid/demos/h5/demo1.tsx
  src/packages/grid/demos/h5/demo10.tsx
  src/packages/grid/demos/h5/demo2.tsx
  src/packages/grid/demos/h5/demo3.tsx
  src/packages/grid/demos/h5/demo4.tsx
  src/packages/grid/demos/h5/demo5.tsx
  src/packages/grid/demos/h5/demo6.tsx
  src/packages/grid/demos/h5/demo7.tsx
  src/packages/grid/demos/h5/demo8.tsx
  src/packages/grid/demos/h5/demo9.tsx
  src/packages/grid/demos/taro/demo1.tsx
  src/packages/grid/demos/taro/demo10.tsx
  src/packages/grid/demos/taro/demo2.tsx
  src/packages/grid/demos/taro/demo3.tsx
  src/packages/grid/demos/taro/demo4.tsx
  src/packages/grid/demos/taro/demo5.tsx
  src/packages/grid/demos/taro/demo6.tsx
  src/packages/grid/demos/taro/demo7.tsx
  src/packages/grid/demos/taro/demo8.tsx
  src/packages/grid/demos/taro/demo9.tsx
  src/packages/grid/doc.en-US.md
  src/packages/grid/doc.md
  src/packages/grid/doc.taro.md
  src/packages/grid/doc.zh-TW.md
  src/packages/grid/grid.scss
  src/packages/grid/grid.taro.tsx
  src/packages/grid/grid.tsx
  src/packages/griditem/griditem.scss
  src/packages/griditem/griditem.taro.tsx
  src/packages/griditem/griditem.tsx
  src/styles/variables.scss
Labels: size/XL, 3.x

#2800 fix(card): harmony适配
  src/config.json
  src/packages/card/card.scss
  src/packages/card/card.taro.tsx
  src/packages/card/demos/h5/demo2.tsx
  src/packages/card/demos/taro/demo1.tsx
  src/packages/card/demos/taro/demo2.tsx
  src/packages/card/demos/taro/demo3.tsx
  src/packages/card/demos/taro/demo4.tsx
  src/packages/card/demos/taro/demo5.tsx
  src/packages/card/demos/taro/demo6.tsx
Labels: size/L, 3.x
