Repository jdf2e/nutui-react, pull requests merged in 2024-07, with the labels that each got.

#2401 chore: 删除有依赖的 demo
  src/packages/avatar/demos/taro/demo5.tsx
  src/packages/configprovider/demos/taro/demo1.tsx
  src/packages/configprovider/demos/taro/demo2.tsx
  src/packages/empty/demos/taro/demo4.tsx
  src/packages/hoverbutton/demos/taro/demo3-rn.tsx
  src/packages/hoverbutton/demos/taro/demo3.tsx
  src/packages/hoverbutton/demos/taro/demo4-rn.tsx
  src/packages/hoverbutton/demos/taro/demo4.tsx
  src/packages/input/demos/taro/demo12.tsx
  src/packages/layout/demo.scss
  src/packages/layout/demos/taro/demo1.tsx
  src/packages/layout/demos/taro/demo2.tsx
  src/packages/layout/demos/taro/demo3.tsx
  src/packages/swipe/demos/taro/demo9.tsx
Labels: size/L

#2400 fix(form): setFieldsValue未能触发校验
  src/packages/form/useform.taro.ts
  src/packages/form/useform.ts
Labels: size/XS

#2364 fix(avatarcropper): 修复taro下avatarCropper对象为空的错误
  src/packages/avatarcropper/avatarcropper.taro.tsx
Labels: size/XS

#2410 fix(uploader): 京东小程序中可上传时可选择图片和视频
  src/packages/uploader/uploader.taro.tsx
Labels: size/XS

#2406 fix(form): validator 中的 value 类型更新为 any
  src/packages/form/demos/h5/demo1.tsx
  src/packages/form/demos/taro/demo1.tsx
  src/packages/formitem/types.ts
Labels: size/S

#2411 feat: add pagination whether to show pages in imagepreview
  pnpm-lock.yaml
  src/packages/imagepreview/doc.en-US.md
  src/packages/imagepreview/doc.md
  src/packages/imagepreview/doc.taro.md
  src/packages/imagepreview/doc.zh-TW.md
  src/packages/imagepreview/imagepreview.taro.tsx
  src/packages/imagepreview/imagepreview.tsx
Labels: size/XXL

#2415 fix(taro-form-demo): 点击演示demo表单内的重置会触发提交表单事件bug修复
  src/packages/form/demos/taro/demo1.tsx
  src/packages/form/demos/taro/demo2.tsx
  src/packages/form/demos/taro/demo4.tsx
  src/packages/form/demos/taro/demo7.tsx
Labels: size/S

#2416 fix(uploader): pre-upload pmage preview bug
  src/packages/uploader/uploader.taro.tsx
  src/packages/uploader/uploader.tsx
Labels: size/S

#2418 feat(drag): add the ability to support onDrag, onDragStart, onDragEnd callbacks
  src/packages/drag/demos/h5/demo1.tsx
  src/packages/drag/demos/taro/demo1.tsx
  src/packages/drag/doc.en-US.md
  src/packages/drag/doc.md
  src/packages/drag/doc.taro.md
  src/packages/drag/doc.zh-TW.md
  src/packages/drag/drag.taro.tsx
  src/packages/drag/drag.tsx
Labels: size/L

#2422 fix(layout): 使用 utils 中的 px 转换函数
  src/packages/layout/demos/taro/demo1.tsx
  src/packages/layout/demos/taro/demo2.tsx
  src/packages/layout/demos/taro/demo3.tsx
Labels: size/XS

#2424 fix: 重新安装依赖会出现依赖包的错误
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#2425 Feat/rn css variables
  package.json
  packages/nutui-taro-demo-rn/config/index.js
  scripts/rn/copy-file.js
Labels: size/M

#2430 fix(tag): 设置按钮字号
  src/packages/tag/tag.harmony.css
  src/packages/tag/tag.scss
  src/packages/tag/tag.taro.tsx
Labels: size/XS

#2421 fix(imagepreview): 无法在预期情景正确关闭图片的异常
  src/packages/imagepreview/imagepreview.taro.tsx
  src/packages/imagepreview/imagepreview.tsx
Labels: size/M

#2409 fix(Calendar): IOS中，日历组件滚动到顶部时会短暂出现白屏
  src/packages/calendaritem/calendaritem.taro.tsx
  src/packages/calendaritem/calendaritem.tsx
Labels: size/XS

#2431 feat: tabs滚动条兼容火狐浏览器
  src/packages/tabs/tabs.scss
Labels: size/XS

#2433 fix(formItem): validateTrigger无法正确触发校验
  src/packages/form/useform.taro.ts
  src/packages/form/useform.ts
Labels: size/XS

#2450 fix(form): 在FromInstance增加validateFields方法的定义
  src/packages/form/types.ts
Labels: size/XS

#2437 fix(form): 兼容校验时机
  src/packages/form/useform.taro.ts
  src/packages/form/useform.ts
  src/packages/formitem/formitem.taro.tsx
  src/packages/formitem/formitem.tsx
Labels: size/S

#2441 feat(infiniteLoading): 继承 scrollView 的 props 类型
  src/packages/infiniteloading/infiniteloading.taro.tsx
Labels: size/S

#2451 feat(empty): add css variable nutui-empty-background-color
  src/packages/empty/doc.en-US.md
  src/packages/empty/doc.md
  src/packages/empty/doc.taro.md
  src/packages/empty/doc.zh-TW.md
  src/packages/empty/empty.scss
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/L

#2443 feat(menuitem): add css classnames to enhance custom style abilities
  src/packages/menuitem/menuitem.taro.tsx
  src/packages/menuitem/menuitem.tsx
Labels: size/S

#2459 chore: 只在鸿蒙下使用 pxtransform
  src/utils/px-transform.ts
Labels: size/XS

#2454 fix(swiper): display abnormal when dir = 'rtl'
  src/packages/swiper/effects/default.tsx
  src/packages/swiper/effects/focus.tsx
Labels: size/S

#2435 fix(cascader): 初始化设置value未成功选中
  src/packages/cascader/__tests__/cascader.spec.tsx
  src/packages/cascader/cascader.taro.tsx
  src/packages/cascader/cascader.tsx
  src/packages/cascader/demos/h5/demo1.tsx
  src/packages/cascader/demos/h5/demo2.tsx
  src/packages/cascader/demos/h5/demo5.tsx
  src/packages/cascader/demos/taro/demo1.tsx
  src/packages/cascader/demos/taro/demo2.tsx
  src/packages/cascader/demos/taro/demo5.tsx
Labels: size/M

#2460 chore: 鸿蒙 pxtransform 支持 radix
  src/utils/px-transform.ts
Labels: size/XS

#2461 chore: 修复 pxTransform 类型导致构建错误
  src/utils/px-transform.ts
Labels: size/XS

#2436 fix: 修复日历进行快捷选择日期时 点击确认获取的是上一次的日期
  src/packages/calendaritem/calendaritem.taro.tsx
  src/packages/calendaritem/calendaritem.tsx
Labels: size/S

#2458 fix: 简化RN开发流程+优化同步脚本
  gulpfile.js
  package.json
  packages/nutui-harmony/entry/src/main/resources/base/profile/main_pages.json
  packages/nutui-taro-demo-rn/babel.config.js
  packages/nutui-taro-demo-rn/config/dev.js
  packages/nutui-taro-demo-rn/config/index.js
  packages/nutui-taro-demo-rn/package.json
  packages/nutui-taro-demo-rn/project.config.json
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/scripts/taro/generate-nutui-taro.js
  packages/nutui-taro-demo-rn/src/app.scss
  packages/nutui-taro-demo-rn/src/app.ts
  packages/nutui-taro-demo-rn/src/dataentry/pages/range/index.config.ts
  packages/nutui-taro-demo-rn/src/dataentry/pages/switch/index.tsx
  packages/nutui-taro-demo-rn/src/dataentry/pages/textarea/index.tsx
  packages/nutui-taro-demo-rn/src/layout/pages/space/index.tsx
  packages/nutui-taro-demo-rn/src/pages/index/index.scss
  packages/nutui-taro-demo-rn/src/pages/index/index.tsx
  packages/nutui-taro-demo-rn/yarn.lock
  pnpm-lock.yaml
  scripts/rn/copy-file.js
Labels: size/XXL

#2374 Feat/backtop 适配 JDRN、鸿蒙端
  packages/nutui-taro-demo-rn/src/nav/pages/backtop/index.config.ts
  packages/nutui-taro-demo-rn/src/nav/pages/backtop/index.tsx
  src/config.json
  src/packages/backtop/backtop.harmony.css
  src/packages/backtop/backtop.scss
  src/packages/backtop/backtop.taro.tsx
  src/packages/backtop/backtop.tsx
  src/packages/backtop/demo.taro.tsx
  src/packages/backtop/demos/taro/demo1.tsx
  src/packages/backtop/demos/taro/demo5.tsx
  src/packages/backtop/doc.en-US.md
  src/packages/backtop/doc.taro.md
  src/packages/backtop/doc.zh-TW.md
Labels: size/L

#2448 fix(uploader): images should display when they've been successfully uploaded
  src/packages/uploader/uploader.taro.tsx
  src/packages/uploader/uploader.tsx
Labels: size/M

#2342 feat(pulltorefresh): 适配鸿蒙、RN、小程序、H5; RN scrollview 默认事件无法阻止
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/app.config.ts
  packages/nutui-taro-demo-rn/src/feedback/pages/pulltorefresh/index.config.ts
  packages/nutui-taro-demo-rn/src/feedback/pages/pulltorefresh/index.tsx
  src/config.json
  src/packages/pulltorefresh/demo.taro.tsx
  src/packages/pulltorefresh/demos/taro/demo1.tsx
  src/packages/pulltorefresh/demos/taro/demo2.tsx
  src/packages/pulltorefresh/demos/taro/demo3.tsx
  src/packages/pulltorefresh/pulltorefresh.harmony.css
  src/packages/pulltorefresh/pulltorefresh.scss
  src/packages/pulltorefresh/pulltorefresh.taro.tsx
  src/packages/pulltorefresh/pulltorefresh.tsx
  src/utils/typings.ts
Labels: size/L

#2468 refactor: sticky
  src/packages/sticky/sticky.taro.tsx
  src/packages/sticky/sticky.tsx
  src/utils/get-scroll-parent.ts
Labels: size/L

#2474 fix(infiniteLoading): rest 导致事件无法触发
  src/packages/infiniteloading/demos/taro/demo1.tsx
  src/packages/infiniteloading/infiniteloading.taro.tsx
Labels: size/XS

#2475 fix(uploader): image 居中展示
  src/packages/uploader/uploader.scss
Labels: size/XS

#2480 feat(menu): allow custom classnames for Menu and dynamic titles
  src/packages/menu/menu.taro.tsx
  src/packages/menu/menu.tsx
Labels: size/S

#2481 chore: update snapshot
  src/packages/cascader/__tests__/__snapshots__/cascader.spec.tsx.snap
  src/packages/ellipsis/__test__/__snapshots__/ellipsis.spec.tsx.snap
  src/packages/menu/__test__/__snapshots__/menu.spec.tsx.snap
Labels: size/L

#2473 refactor: table
  src/packages/table/demos/h5/demo14.tsx
  src/packages/table/demos/taro/demo14.tsx
  src/packages/table/table.taro.tsx
  src/packages/table/table.tsx
Labels: size/M

#2482 fix: move defaultprops
  src/packages/animatingnumbers/countup.taro.tsx
  src/packages/animatingnumbers/countup.tsx
  src/packages/audio/audio.taro.tsx
  src/packages/audio/audio.tsx
  src/packages/checkboxgroup/checkboxgroup.taro.tsx
  src/packages/checkboxgroup/checkboxgroup.tsx
  src/packages/datepicker/datepicker.taro.tsx
  src/packages/datepicker/datepicker.tsx
  src/packages/dialog/dialog.taro.tsx
  src/packages/dialog/dialog.tsx
  src/packages/dialog/dialogwrap.tsx
  src/packages/notify/notify.taro.tsx
  src/packages/pulltorefresh/pulltorefresh.taro.tsx
  src/packages/pulltorefresh/pulltorefresh.tsx
  src/packages/radio/radio.taro.tsx
  src/packages/radio/radio.tsx
  src/packages/radiogroup/radiogroup.taro.tsx
  src/packages/radiogroup/radiogroup.tsx
  src/packages/swipe/swipe.taro.tsx
  src/packages/swipe/swipe.tsx
  src/packages/swiper/swiper.taro.tsx
  src/packages/swiper/swiper.tsx
  src/packages/swiperitem/swiperitem.taro.tsx
  src/packages/swiperitem/swiperitem.tsx
  src/packages/toast/toast.taro.tsx
Labels: size/L

#2493 fix(swiper): correct onChange ts type
  src/packages/swiper/demos/taro/demo1.tsx
  src/packages/swiper/doc.taro.md
  src/packages/swiper/swiper.taro.tsx
Labels: size/S

#2496 chore(cell): unify ts type & docs
  src/packages/cell/cell.taro.tsx
  src/packages/cell/cell.tsx
  src/packages/cell/doc.en-US.md
  src/packages/cell/doc.md
  src/packages/cell/doc.taro.md
  src/packages/cell/doc.zh-TW.md
Labels: size/S

#2504 docs(card): correct doc
  src/packages/card/doc.taro.md
Labels: size/XS
