Repository jdf2e/nutui-react, pull requests merged in 2024-12, with the labels that each got.

#2793 feat(imagepreview): use nutui image
  packages/nutui-taro-demo/src/pages/index/index.tsx
  src/packages/imagepreview/imagepreview.scss
  src/packages/imagepreview/imagepreview.taro.tsx
Labels: size/S, 3.x

#2808 chore: add v1-to-v2 & official-theme docs on 3x
  .github/workflows/sync-migrate.yml
  src/config.json
Labels: size/S, 3.x

#2806 fix(timeselect): harmony适配
  src/config.json
  src/packages/timedetail/timedetail.scss
Labels: size/XS, 3.x

#2811 chore: update deps
  package.json
  packages/nutui-taro-demo/package.json
  packages/nutui-taro-demo/yarn.lock
  pnpm-lock.yaml
  scripts/harmony/clone-jdharmony.js
Labels: size/XL, 3.x

#2812 fix: change scss import path
  scripts/build.mjs
  scripts/demo.js
  scripts/harmony/clone-jdharmony.js
  scripts/rn/copy-file.js
  scripts/taro/replace-taro-types-alias.js
  scripts/update-v2.js
  src/packages/overlay/demo.taro.tsx
  src/packages/skeleton/demo.taro.tsx
Labels: size/S, 3.x

#2813 chore: update deps
  packages/nutui-taro-demo/package.json
  packages/nutui-taro-demo/yarn.lock
Labels: size/S, 3.x

#2760 feat(Empty): V14
  src/config.json
  src/packages/calendarcard/calendarcard.scss
  src/packages/empty/__test__/empty.spec.tsx
  src/packages/empty/demos/h5/demo1.tsx
  src/packages/empty/demos/h5/demo2.tsx
  src/packages/empty/demos/h5/demo3.tsx
  src/packages/empty/demos/h5/demo4.tsx
  src/packages/empty/demos/h5/demo6.tsx
  src/packages/empty/demos/taro/demo1.tsx
  src/packages/empty/demos/taro/demo2.tsx
  src/packages/empty/demos/taro/demo3.tsx
  src/packages/empty/demos/taro/demo4.tsx
  src/packages/empty/demos/taro/demo6.tsx
  src/packages/empty/doc.en-US.md
  src/packages/empty/doc.md
  src/packages/empty/doc.taro.md
  src/packages/empty/doc.zh-TW.md
  src/packages/empty/empty.scss
  src/packages/empty/empty.taro.tsx
  src/packages/empty/empty.tsx
  src/styles/variables.scss
Labels: size/L, 3.x

#2819 fix(empty): correct css margin and docs
  src/packages/empty/doc.en-US.md
  src/packages/empty/doc.md
  src/packages/empty/doc.taro.md
  src/packages/empty/doc.zh-TW.md
  src/packages/empty/empty.scss
  src/styles/variables.scss
Labels: size/S, 3.x

#2822 fix: Uploade 组件无法预览图片
  src/packages/uploader/uploader.scss
Labels: size/XS, 2.x

#2817 fix: space harmony
  packages/nutui-taro-demo/src/pages/index/index.tsx
  src/packages/space/demo.taro.tsx
  src/packages/space/demo.tsx
  src/packages/space/demos/h5/demo1.tsx
  src/packages/space/demos/h5/demo2.tsx
  src/packages/space/demos/h5/demo3.tsx
  src/packages/space/demos/h5/demo4.tsx
  src/packages/space/demos/h5/demo5.tsx
  src/packages/space/demos/h5/demo6.tsx
  src/packages/space/demos/taro/demo1.tsx
  src/packages/space/demos/taro/demo2.tsx
  src/packages/space/demos/taro/demo3.tsx
  src/packages/space/demos/taro/demo4.tsx
  src/packages/space/demos/taro/demo5.tsx
  src/packages/space/demos/taro/demo6.tsx
Labels: size/L, 3.x

#2825 chore(uploader): use scss variable
  src/packages/uploader/uploader.scss
Labels: size/XS, 2.x

#2795 feat(toast): v14
  src/config.json
  src/packages/toast/Notification.tsx
  src/packages/toast/demos/h5/demo1.tsx
  src/packages/toast/demos/taro/demo1.tsx
  src/packages/toast/doc.en-US.md
  src/packages/toast/doc.md
  src/packages/toast/doc.taro.md
  src/packages/toast/doc.zh-TW.md
  src/packages/toast/toast.scss
  src/packages/toast/toast.taro.tsx
  src/styles/variables.scss
Labels: size/L, 3.x

#2824 fix: jd white screen
  package.json
  pnpm-lock.yaml
  src/styles/theme-dark.scss
  src/styles/theme-default.scss
Labels: size/L, 3.x

#2797 feat(rate): v14
  migrate-from-v2.md
  src/config.json
  src/packages/rate/__test__/__snapshots__/rate.spec.tsx.snap
  src/packages/rate/__test__/rate.spec.tsx
  src/packages/rate/demos/h5/demo1.tsx
  src/packages/rate/demos/h5/demo2.tsx
  src/packages/rate/demos/h5/demo5.tsx
  src/packages/rate/demos/taro/demo1.tsx
  src/packages/rate/demos/taro/demo2.tsx
  src/packages/rate/demos/taro/demo5.tsx
  src/packages/rate/doc.en-US.md
  src/packages/rate/doc.md
  src/packages/rate/doc.taro.md
  src/packages/rate/doc.zh-TW.md
  src/packages/rate/index.taro.ts
  src/packages/rate/index.ts
  src/packages/rate/rate.scss
  src/packages/rate/rate.taro.tsx
  src/packages/rate/rate.tsx
  src/packages/rate/types.ts
  src/styles/theme-dark.scss
  src/styles/theme-default.scss
  src/styles/variables.scss
Labels: size/L, 3.x

#2779 feat(switch): v14&代码重构
  migrate-from-v2.md
  src/config.json
  src/packages/switch/__test__/switch.spec.tsx
  src/packages/switch/demo.taro.tsx
  src/packages/switch/demo.tsx
  src/packages/switch/demos/h5/demo3.tsx
  src/packages/switch/demos/h5/demo4.tsx
  src/packages/switch/demos/h5/demo5.tsx
  src/packages/switch/demos/h5/demo6.tsx
  src/packages/switch/demos/h5/demo7.tsx
  src/packages/switch/demos/taro/demo2.tsx
  src/packages/switch/demos/taro/demo3.tsx
  src/packages/switch/demos/taro/demo4.tsx
  src/packages/switch/demos/taro/demo5.tsx
  src/packages/switch/demos/taro/demo6.tsx
  src/packages/switch/demos/taro/demo7.tsx
  src/packages/switch/doc.en-US.md
  src/packages/switch/doc.md
  src/packages/switch/doc.taro.md
  src/packages/switch/doc.zh-TW.md
  src/packages/switch/switch.scss
  src/packages/switch/switch.taro.tsx
  src/packages/switch/switch.tsx
  src/styles/variables.scss
Labels: size/XL, 3.x

#2807 fix(uploader): 修复选择多个文件上传只会上传一个文件的问题 Fixes #2549
  src/packages/uploader/uploader.taro.tsx
  src/packages/uploader/uploader.tsx
Labels: size/S, 2.x

#2810 feat(hoverbutton): v14
  src/packages/configprovider/types.ts
  src/packages/hoverbutton/__test__/__snapshots__/hoverbutton.spec.tsx.snap
  src/packages/hoverbutton/__test__/hoverbutton.spec.tsx
  src/packages/hoverbutton/demo.scss
  src/packages/hoverbutton/demo.taro.tsx
  src/packages/hoverbutton/demo.tsx
  src/packages/hoverbutton/demos/h5/demo2.tsx
  src/packages/hoverbutton/demos/h5/demo6.tsx
  src/packages/hoverbutton/demos/taro/demo2.tsx
  src/packages/hoverbutton/demos/taro/demo6.tsx
  src/packages/hoverbutton/doc.en-US.md
  src/packages/hoverbutton/doc.md
  src/packages/hoverbutton/doc.taro.md
  src/packages/hoverbutton/doc.zh-TW.md
  src/packages/hoverbutton/hoverbutton.taro.tsx
  src/packages/hoverbutton/hoverbutton.tsx
  src/packages/hoverbutton/utils.ts
  src/packages/hoverbuttonitem/hoverbuttonitem.scss
  src/packages/hoverbuttonitem/hoverbuttonitem.taro.tsx
  src/packages/hoverbuttonitem/hoverbuttonitem.tsx
  src/packages/hoverbuttonitem/utils.ts
  src/styles/variables.scss
Labels: size/L, 3.x

#2762 feat(segmented): v14
  src/config.json
  src/packages/segmented/__tests__/segmented.spec.tsx
  src/packages/segmented/demo.taro.tsx
  src/packages/segmented/demo.tsx
  src/packages/segmented/demos/h5/demo1.tsx
  src/packages/segmented/demos/h5/demo2.tsx
  src/packages/segmented/demos/h5/demo3.tsx
  src/packages/segmented/demos/taro/demo1.tsx
  src/packages/segmented/demos/taro/demo2.tsx
  src/packages/segmented/demos/taro/demo3.tsx
  src/packages/segmented/doc.en-US.md
  src/packages/segmented/doc.md
  src/packages/segmented/doc.taro.md
  src/packages/segmented/doc.zh-TW.md
  src/packages/segmented/index.taro.ts
  src/packages/segmented/index.ts
  src/packages/segmented/segmented.scss
  src/packages/segmented/segmented.taro.tsx
  src/packages/segmented/segmented.tsx
  src/packages/segmented/types.ts
  src/styles/variables.scss
Labels: size/XL, 3.x

#2830 chore: update timeDetail version
  src/config.json
Labels: size/XS, 3.x

#2832 fix: 解决微信小程序滚动报错问题
  src/packages/elevator/demos/taro/demo2.tsx
  src/packages/elevator/demos/taro/demo3.tsx
  src/packages/elevator/demos/taro/demo4.tsx
  src/packages/elevator/demos/taro/demo5.tsx
Labels: size/XS, 3.x

#2833 fix: 解决微信小程序滚动报错问题
  src/packages/elevator/demos/taro/demo2.tsx
  src/packages/elevator/demos/taro/demo3.tsx
  src/packages/elevator/demos/taro/demo4.tsx
  src/packages/elevator/demos/taro/demo5.tsx
Labels: size/XS, 2.x

#2834 fix(elevator): 采用唯一ID，避免未传入 className 导致的报错
  src/packages/elevator/elevator.taro.tsx
Labels: size/S, 2.x

#2835 fix(elevator): 采用唯一ID，避免未传入 className 导致的报错
  src/packages/elevator/elevator.taro.tsx
Labels: size/S, 3.x

#2772 feat(form): add validateTrigger, setFieldValue and disabled
  src/packages/form/__tests__/form.spec.tsx
  src/packages/form/doc.en-US.md
  src/packages/form/doc.md
  src/packages/form/doc.taro.md
  src/packages/form/doc.zh-TW.md
  src/packages/form/form.scss
  src/packages/form/form.taro.tsx
  src/packages/form/form.tsx
  src/packages/form/types.ts
  src/packages/form/useform.taro.ts
  src/packages/form/useform.ts
  src/packages/formitem/formitem.scss
  src/packages/formitem/formitem.taro.tsx
  src/packages/formitem/formitem.tsx
  src/utils/merge.ts
  src/utils/to-array.ts
Labels: size/XL, 2.x

#2757 docs: components can be searched
  packages/nutui-taro-demo/config/index.js
  packages/nutui-taro-demo/src/pages/index/index.tsx
Labels: size/S, 3.x

#2838 chore: update tag from v14 to v15
  src/config.json
Labels: size/S, 3.x

#2842 chore: support pnpm workspace
  .gitignore
  .pnpmfile.cjs
  README.md
  README_ZH.md
  package.json
  packages/nutui-taro-demo/config/index.js
  packages/nutui-taro-demo/package.json
  packages/nutui-taro-demo/yarn.lock
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/XXL, 3.x

#2849 fix(overlay): 鸿蒙demo
  src/packages/overlay/demo.taro.tsx
Labels: size/M, 3.x

#2848 feat: support open more entries in update-taro-entry
  scripts/rn/update-taro-entry.js
Labels: size/XS, 3.x

#2740 chore: e2e test & CI integration
  .github/workflows/cypress.yml
  cypress.config.ts
  cypress/component/Actionsheet.cy.jsx
  cypress/component/Button.cy.jsx
  cypress/component/Cell.cy.jsx
  cypress/e2e/common/pageWhiteTest.cy.js
  cypress/e2e/h5/base.cy.js
  cypress/e2e/h5/bussiness.cy.js
  cypress/e2e/h5/dentry.cy.js
  cypress/e2e/h5/exhibition.cy.js
  cypress/e2e/h5/feedback.cy.js
  cypress/e2e/h5/index.cy.js
  cypress/e2e/h5/layout.cy.js
  cypress/e2e/h5/nav.cy.js
  cypress/e2e/index.cy.js
  cypress/e2e/taro/base.cy.js
  cypress/e2e/taro/dentry.cy.js
  cypress/e2e/taro/index.cy.js
  cypress/e2e/taro/layout.cy.js
  cypress/e2e/taro/nav.cy.js
  cypress/e2e/utils/visit-demo.cy.js
  cypress/screenshots/index.cy.js/layout components test -- Switch successfully passes (failed).png
  cypress/screenshots/taro/dentry.cy.js/layout components test -- Switch successfully passes (failed).png
  package.json
  pnpm-lock.yaml
Labels: size/XXL, 3.x

#2823 feat(inputNumber): v14 multi-platform adaption
  src/packages/inputnumber/demos/taro/demo3.tsx
  src/packages/inputnumber/demos/taro/demo8.tsx
  src/packages/inputnumber/demos/taro/demo9.tsx
  src/packages/inputnumber/doc.en-US.md
  src/packages/inputnumber/doc.md
  src/packages/inputnumber/doc.taro.md
  src/packages/inputnumber/doc.zh-TW.md
  src/packages/inputnumber/inputnumber.scss
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/inputnumber/inputnumber.tsx
  src/styles/variables.scss
Labels: size/XL, 3.x

#2843 fix(countdown): update the v15 style
  src/packages/countdown/countdown.scss
  src/packages/countdown/countdown.taro.tsx
  src/styles/theme-dark.scss
  src/styles/theme-default.scss
  src/styles/variables.scss
Labels: size/M, 3.x

#2850 fix: dark 模式下arrow 未配置
  src/packages/popover/popover.scss
Labels: size/S, 2.x

#2853 fix(Animate): 支持 button block
  src/packages/animate/animate.scss
  src/packages/animate/demos/h5/demo1.tsx
  src/packages/animate/demos/h5/demo2.tsx
  src/packages/animate/demos/taro/demo1.tsx
  src/packages/animate/demos/taro/demo2.tsx
Labels: size/L, 2.x

#2854 fix(empty): actions add support for events
  src/packages/empty/demo.taro.tsx
  src/packages/empty/demo.tsx
  src/packages/empty/demos/h5/demo7.tsx
  src/packages/empty/demos/taro/demo7.tsx
  src/packages/empty/doc.en-US.md
  src/packages/empty/doc.md
  src/packages/empty/doc.taro.md
  src/packages/empty/doc.zh-TW.md
  src/packages/empty/empty.taro.tsx
  src/packages/empty/empty.tsx
  src/packages/empty/types.ts
  src/packages/empty/utils.ts
Labels: size/L, 2.x

#2851 feat(popover): 增加最大宽度设置，支持文本超过最大宽度时，换行展示。
  src/packages/popover/doc.en-US.md
  src/packages/popover/doc.md
  src/packages/popover/doc.taro.md
  src/packages/popover/doc.zh-TW.md
  src/packages/popover/popover.scss
  src/styles/variables.scss
Labels: size/S, 2.x

#2852 feat(Video): web h5 下支持 ref 调用
  src/packages/video/__tests__/video.spec.tsx
  src/packages/video/demo.tsx
  src/packages/video/demos/h5/demo2.tsx
  src/packages/video/doc.en-US.md
  src/packages/video/doc.md
  src/packages/video/doc.zh-TW.md
  src/packages/video/video.tsx
Labels: size/L, 2.x

#2836 fix(elevator): harmony适配
  src/packages/elevator/elevator.scss
  src/packages/elevator/elevator.taro.tsx
Labels: size/M, 3.x

#2856 chore: update to support taro e2e test
  .github/workflows/cypress.yml
  cypress/e2e/taro/index.cy.js
  package.json
  scripts/rn/update-taro-entry.js
Labels: size/S, 3.x

#2869 fix(countup): 分隔符文字颜色支持css变量修改
  src/packages/animatingnumbers/countup.scss
  src/packages/animatingnumbers/demos/h5/demo2.tsx
  src/packages/animatingnumbers/demos/taro/demo2.tsx
  src/packages/animatingnumbers/doc.en-US.md
  src/packages/animatingnumbers/doc.md
  src/packages/animatingnumbers/doc.taro.md
  src/packages/animatingnumbers/doc.zh-TW.md
  src/styles/variables.scss
Labels: size/S, 2.x

#2871 fix(countup): 分隔符文字颜色支持css变量修改
  src/packages/animatingnumbers/countup.scss
  src/packages/animatingnumbers/demos/h5/demo2.tsx
  src/packages/animatingnumbers/demos/taro/demo2.tsx
  src/packages/animatingnumbers/doc.en-US.md
  src/packages/animatingnumbers/doc.md
  src/packages/animatingnumbers/doc.taro.md
  src/packages/animatingnumbers/doc.zh-TW.md
  src/styles/variables.scss
Labels: size/S, 3.x

#2855 fix: 修改小程序下自动吸边计算逻辑&&解决部分小程序写法不支持问题
  src/packages/drag/demos/taro/demo4.tsx
  src/packages/drag/drag.scss
  src/packages/drag/drag.taro.tsx
Labels: size/M, 2.x

#2826 feat(badge): v15适配
  migrate-from-v2.md
  src/config.json
  src/packages/badge/__test__/__snapshots__/badge.spec.tsx.snap
  src/packages/badge/__test__/badge.spec.tsx
  src/packages/badge/badge.scss
  src/packages/badge/badge.taro.tsx
  src/packages/badge/badge.tsx
  src/packages/badge/demos/h5/demo1.tsx
  src/packages/badge/demos/h5/demo2.tsx
  src/packages/badge/demos/h5/demo3.tsx
  src/packages/badge/demos/h5/demo4.tsx
  src/packages/badge/demos/h5/demo5.tsx
  src/packages/badge/demos/h5/demo6.tsx
  src/packages/badge/demos/h5/demo7.tsx
  src/packages/badge/demos/h5/demo8.tsx
  src/packages/badge/demos/taro/demo1.tsx
  src/packages/badge/demos/taro/demo2.tsx
  src/packages/badge/demos/taro/demo3.tsx
  src/packages/badge/demos/taro/demo4.tsx
  src/packages/badge/demos/taro/demo5.tsx
  src/packages/badge/demos/taro/demo6.tsx
  src/packages/badge/demos/taro/demo7.tsx
  src/packages/badge/demos/taro/demo8.tsx
  src/packages/badge/doc.en-US.md
  src/packages/badge/doc.md
  src/packages/badge/doc.taro.md
  src/packages/badge/doc.zh-TW.md
  src/packages/badge/index.taro.ts
  src/packages/badge/index.ts
  src/packages/badge/types.ts
  src/packages/tabbar/__tests__/__snapshots__/tabbar.spec.tsx.snap
  src/styles/variables.scss
Labels: size/XL, 3.x

#2872 fix(form): 修复label字号的css变量
  src/packages/formitem/formitem.scss
Labels: size/XS, 2.x

#2866 feat(Backtop): refactor backtop using hoverbutton and v15 adaption
  migrate-from-v2.md
  src/config.json
  src/packages/backtop/__test__/__snapshots__/backtop.spec.tsx.snap
  src/packages/backtop/__test__/backtop.spec.tsx
  src/packages/backtop/backtop.scss
  src/packages/backtop/backtop.taro.tsx
  src/packages/backtop/backtop.tsx
  src/packages/backtop/demo.taro.tsx
  src/packages/backtop/demo.tsx
  src/packages/backtop/demos/h5/demo1.tsx
  src/packages/backtop/demos/h5/demo2.tsx
  src/packages/backtop/demos/h5/demo3.tsx
  src/packages/backtop/demos/h5/demo4.tsx
  src/packages/backtop/demos/h5/demo5.tsx
  src/packages/backtop/demos/taro/demo1.tsx
  src/packages/backtop/demos/taro/demo2.tsx
  src/packages/backtop/demos/taro/demo3.tsx
  src/packages/backtop/demos/taro/demo4.tsx
  src/packages/backtop/demos/taro/demo5.tsx
  src/packages/hoverbutton/demos/taro/demo4.tsx
  src/packages/hoverbuttonitem/hoverbuttonitem.scss
  src/styles/variables.scss
Labels: size/L, 3.x

#2841 feat: infiniteloading v15 adaption
  src/config.json
  src/packages/infiniteloading/demos/h5/demo1.tsx
  src/packages/infiniteloading/demos/h5/demo2.tsx
  src/packages/infiniteloading/infiniteloading.scss
Labels: size/S, 3.x

#2879 feat(radio): v15
  src/config.json
  src/packages/radio/radio.scss
Labels: size/XS, 3.x

#2880 feat(checkbox): v15
  src/config.json
  src/packages/checkbox/checkbox.scss
Labels: size/XS, 3.x

#2660 refactor(uploader): Upoader 3.0 重构 & 多端适配
  migrate-from-v2.md
  pnpm-lock.yaml
  src/config.json
  src/packages/uploader/__tests__/uploader.spec.tsx
  src/packages/uploader/demo.taro.tsx
  src/packages/uploader/demo.tsx
  src/packages/uploader/demos/h5/demo1.tsx
  src/packages/uploader/demos/h5/demo10.tsx
  src/packages/uploader/demos/h5/demo11.tsx
  src/packages/uploader/demos/h5/demo12.tsx
  src/packages/uploader/demos/h5/demo13.tsx
  src/packages/uploader/demos/h5/demo14.tsx
  src/packages/uploader/demos/h5/demo2.tsx
  src/packages/uploader/demos/h5/demo3.tsx
  src/packages/uploader/demos/h5/demo4.tsx
  src/packages/uploader/demos/h5/demo5.tsx
  src/packages/uploader/demos/h5/demo6.tsx
  src/packages/uploader/demos/h5/demo7.tsx
  src/packages/uploader/demos/h5/demo8.tsx
  src/packages/uploader/demos/h5/demo9.tsx
  src/packages/uploader/demos/taro/demo1.tsx
  src/packages/uploader/demos/taro/demo10.tsx
  src/packages/uploader/demos/taro/demo11.tsx
  src/packages/uploader/demos/taro/demo12.tsx
  src/packages/uploader/demos/taro/demo13.tsx
  src/packages/uploader/demos/taro/demo14.tsx
  src/packages/uploader/demos/taro/demo2.tsx
  src/packages/uploader/demos/taro/demo3.tsx
  src/packages/uploader/demos/taro/demo4.tsx
  src/packages/uploader/demos/taro/demo5.tsx
  src/packages/uploader/demos/taro/demo6.tsx
  src/packages/uploader/demos/taro/demo7.tsx
  src/packages/uploader/demos/taro/demo8.tsx
  src/packages/uploader/demos/taro/demo9.tsx
  src/packages/uploader/doc.en-US.md
  src/packages/uploader/doc.md
  src/packages/uploader/doc.taro.md
  src/packages/uploader/doc.zh-TW.md
  src/packages/uploader/file-item.taro.ts
  src/packages/uploader/file-item.ts
  src/packages/uploader/index.taro.ts
  src/packages/uploader/index.ts
  src/packages/uploader/preview.taro.tsx
  src/packages/uploader/preview.tsx
  src/packages/uploader/types.ts
  src/packages/uploader/uploader.taro.tsx
  src/packages/uploader/uploader.tsx
  src/packages/uploader/utils.ts
Labels: size/XXL, 3.x

#2865 fix: update backtop demos
  src/packages/backtop/demo.tsx
  src/packages/backtop/demos/h5/demo3.tsx
  src/packages/backtop/demos/h5/demo5.tsx
  src/packages/backtop/demos/taro/demo1.tsx
  src/packages/backtop/demos/taro/demo2.tsx
  src/packages/backtop/demos/taro/demo3.tsx
  src/packages/backtop/demos/taro/demo4.tsx
Labels: size/M, 2.x

#2844 feat: v15 popup
  src/config.json
  src/packages/address/__test__/__snapshots__/address.spec.tsx.snap
  src/packages/address/__test__/address.spec.tsx
  src/packages/address/address.tsx
  src/packages/cascader/cascader.taro.tsx
  src/packages/overlay/overlay.scss
  src/packages/popup/__tests__/popup.spec.tsx
  src/packages/popup/demo.taro.tsx
  src/packages/popup/demos/h5/demo1.tsx
  src/packages/popup/demos/h5/demo2.tsx
  src/packages/popup/demos/taro/demo1.tsx
  src/packages/popup/demos/taro/demo2.tsx
  src/packages/popup/demos/taro/demo8.tsx
  src/packages/popup/popup.scss
  src/packages/popup/popup.taro.tsx
  src/packages/popup/popup.tsx
  src/packages/timeselect/__test__/__snapshots__/timeselect.spec.tsx.snap
  src/packages/timeselect/__test__/timeselect.spec.tsx
  src/packages/timeselect/demos/taro/demo1.tsx
  src/packages/timeselect/demos/taro/demo2.tsx
  src/packages/timeselect/demos/taro/demo3.tsx
  src/packages/timeselect/timeselect.taro.tsx
  src/packages/timeselect/timeselect.tsx
  src/styles/variables.scss
Labels: size/XL, 3.x

#2886 fix: 解决skeleton引入switch按钮尺寸过大
  src/packages/skeleton/demos/h5/demo5.tsx
  src/packages/skeleton/demos/taro/demo5.tsx
  src/packages/switch/switch.scss
Labels: size/S, 3.x

#2847 fix: 构建全量 css 文件
  scripts/build-taro.mjs
  scripts/build.mjs
Labels: size/L, 3.x

#2881 feat(navbar): v15
  migrate-from-v2.md
  src/config.json
  src/packages/navbar/__test__/__snapshots__/navbar.spec.tsx.snap
  src/packages/navbar/demos/h5/demo1.tsx
  src/packages/navbar/demos/h5/demo2.tsx
  src/packages/navbar/demos/h5/demo3.tsx
  src/packages/navbar/demos/taro/demo1.tsx
  src/packages/navbar/demos/taro/demo2.tsx
  src/packages/navbar/demos/taro/demo3.tsx
  src/packages/navbar/doc.en-US.md
  src/packages/navbar/doc.md
  src/packages/navbar/doc.taro.md
  src/packages/navbar/doc.zh-TW.md
  src/packages/navbar/navbar.scss
  src/packages/navbar/navbar.taro.tsx
  src/packages/navbar/navbar.tsx
Labels: size/XL, 3.x

#2887 feat: textarea v15
  migrate-from-v2.md
  src/config.json
  src/packages/textarea/__test__/__snapshots__/textarea.spec.tsx.snap
  src/packages/textarea/demo.taro.tsx
  src/packages/textarea/demo.tsx
  src/packages/textarea/demos/h5/demo1.tsx
  src/packages/textarea/demos/h5/demo9.tsx
  src/packages/textarea/demos/taro/demo1.tsx
  src/packages/textarea/demos/taro/demo9.tsx
  src/packages/textarea/doc.en-US.md
  src/packages/textarea/doc.md
  src/packages/textarea/doc.taro.md
  src/packages/textarea/doc.zh-TW.md
  src/packages/textarea/textarea.scss
  src/packages/textarea/textarea.taro.tsx
  src/packages/textarea/textarea.tsx
  src/styles/variables.scss
Labels: size/L, 3.x

#2889 feat: intput v15
  migrate-from-v2.md
  src/config.json
  src/packages/formitem/formitem.scss
  src/packages/input/demos/h5/demo1.tsx
  src/packages/input/demos/h5/demo10.tsx
  src/packages/input/demos/h5/demo11.tsx
  src/packages/input/demos/h5/demo13.tsx
  src/packages/input/demos/h5/demo4.tsx
  src/packages/input/demos/h5/demo5.tsx
  src/packages/input/demos/h5/demo6.tsx
  src/packages/input/demos/h5/demo7.tsx
  src/packages/input/demos/h5/demo8.tsx
  src/packages/input/demos/h5/demo9.tsx
  src/packages/input/demos/taro/demo1.tsx
  src/packages/input/demos/taro/demo10.tsx
  src/packages/input/demos/taro/demo11.tsx
  src/packages/input/demos/taro/demo12.tsx
  src/packages/input/demos/taro/demo13.tsx
  src/packages/input/demos/taro/demo14.tsx
  src/packages/input/demos/taro/demo2.tsx
  src/packages/input/demos/taro/demo3.tsx
  src/packages/input/demos/taro/demo4.tsx
  src/packages/input/demos/taro/demo5.tsx
  src/packages/input/demos/taro/demo6.tsx
  src/packages/input/demos/taro/demo7.tsx
  src/packages/input/demos/taro/demo8.tsx
  src/packages/input/demos/taro/demo9.tsx
  src/packages/input/input.scss
  src/packages/input/input.taro.tsx
  src/packages/input/input.tsx
  src/styles/variables.scss
Labels: size/XL, 3.x

#2746 feat(v15): indicator adaptation
  migrate-from-v2.md
  src/config.json
  src/packages/indicator/__test__/__snapshots__/indicator.spec.tsx.snap
  src/packages/indicator/__test__/indicator.spec.tsx
  src/packages/indicator/demo.taro.tsx
  src/packages/indicator/demo.tsx
  src/packages/indicator/demos/h5/demo1.tsx
  src/packages/indicator/demos/h5/demo4.tsx
  src/packages/indicator/demos/h5/demo5.tsx
  src/packages/indicator/demos/h5/demo6.tsx
  src/packages/indicator/demos/taro/demo1.tsx
  src/packages/indicator/demos/taro/demo4.tsx
  src/packages/indicator/demos/taro/demo5.tsx
  src/packages/indicator/demos/taro/demo6.tsx
  src/packages/indicator/doc.en-US.md
  src/packages/indicator/doc.md
  src/packages/indicator/doc.taro.md
  src/packages/indicator/doc.zh-TW.md
  src/packages/indicator/indicator.scss
  src/packages/indicator/indicator.taro.tsx
  src/packages/indicator/indicator.tsx
  src/styles/variables.scss
Labels: size/XL, 3.x

#2885 feat(price): v15
  migrate-from-v2.md
  src/config.json
  src/packages/card/__test__/__snapshots__/card.spec.tsx.snap
  src/packages/cell/cell.taro.tsx
  src/packages/cell/cell.tsx
  src/packages/cell/index.taro.ts
  src/packages/cell/index.ts
  src/packages/cell/types.ts
  src/packages/price/__test__/__snapshots__/price.spec.tsx.snap
  src/packages/price/__test__/price.spec.tsx
  src/packages/price/demo.taro.tsx
  src/packages/price/demo.tsx
  src/packages/price/demos/h5/demo1.tsx
  src/packages/price/demos/h5/demo2.tsx
  src/packages/price/demos/h5/demo3.tsx
  src/packages/price/demos/h5/demo4.tsx
  src/packages/price/demos/h5/demo5.tsx
  src/packages/price/demos/h5/demo6.tsx
  src/packages/price/demos/h5/demo7.tsx
  src/packages/price/demos/h5/demo8.tsx
  src/packages/price/demos/h5/demo9.tsx
  src/packages/price/demos/taro/demo1.tsx
  src/packages/price/demos/taro/demo2.tsx
  src/packages/price/demos/taro/demo3.tsx
  src/packages/price/demos/taro/demo4.tsx
  src/packages/price/demos/taro/demo5.tsx
  src/packages/price/demos/taro/demo6.tsx
  src/packages/price/demos/taro/demo7.tsx
  src/packages/price/demos/taro/demo8.tsx
  src/packages/price/demos/taro/demo9.tsx
  src/packages/price/doc.en-US.md
  src/packages/price/doc.md
  src/packages/price/doc.taro.md
  src/packages/price/doc.zh-TW.md
  src/packages/price/index.taro.ts
  src/packages/price/index.ts
  src/packages/price/price.scss
  src/packages/price/price.taro.tsx
  src/packages/price/price.tsx
  src/packages/price/types.ts
  src/styles/jd-font.scss
  src/styles/variables.scss
Labels: size/XL, 3.x

#2893 fix: button v15 调整
  src/packages/button/button.scss
  src/packages/button/demos/h5/demo8.tsx
  src/packages/button/demos/taro/demo10.tsx
  src/packages/button/demos/taro/demo2.tsx
  src/packages/button/demos/taro/demo3.tsx
  src/packages/button/demos/taro/demo4.tsx
  src/packages/button/demos/taro/demo5.tsx
  src/packages/button/demos/taro/demo6.tsx
  src/packages/button/demos/taro/demo7.tsx
  src/packages/button/demos/taro/demo8.tsx
  src/styles/variables.scss
Labels: size/L, 3.x

#2897 chore(sidenavbar): deprecated component suggestions
  src/packages/sidenavbar/doc.en-US.md
  src/packages/sidenavbar/doc.md
  src/packages/sidenavbar/doc.taro.md
  src/packages/sidenavbar/doc.zh-TW.md
  src/packages/sidenavbar/sidenavbar.taro.tsx
  src/packages/sidenavbar/sidenavbar.tsx
Labels: size/M, 3.x

#2867 feat(lottie): new component
  package.json
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
  src/config.json
  src/packages/configprovider/types.ts
  src/packages/loading/__test__/loading.spec.tsx
  src/packages/loading/demos/h5/demo1.tsx
  src/packages/loading/demos/taro/demo1.tsx
  src/packages/loading/demos/taro/demo8.tsx
  src/packages/loading/doc.en-US.md
  src/packages/loading/doc.md
  src/packages/loading/doc.taro.md
  src/packages/loading/doc.zh-TW.md
  src/packages/loading/index.taro.ts
  src/packages/loading/index.ts
  src/packages/loading/loading.scss
  src/packages/loading/loading.taro.tsx
  src/packages/loading/loading.tsx
  src/packages/loading/types.ts
  src/packages/lottie/animation/dark/global.gif
  src/packages/lottie/animation/dark/global.json
  src/packages/lottie/animation/dark/loading.gif
  src/packages/lottie/animation/dark/loading.json
  src/packages/lottie/animation/dark/pulltorefresh-white.gif
  src/packages/lottie/animation/dark/pulltorefresh-white.json
  src/packages/lottie/animation/dark/pulltorefresh.gif
  src/packages/lottie/animation/dark/pulltorefresh.json
  src/packages/lottie/animation/light/global.gif
  src/packages/lottie/animation/light/global.json
  src/packages/lottie/animation/light/loading.gif
  src/packages/lottie/animation/light/loading.json
  src/packages/lottie/animation/light/pulltorefresh.gif
  src/packages/lottie/animation/light/pulltorefresh.json
  src/packages/lottie/demo.taro.tsx
  src/packages/lottie/demo.tsx
  src/packages/lottie/demos/h5/demo1.tsx
  src/packages/lottie/demos/h5/demo2.tsx
  src/packages/lottie/demos/h5/demo3.tsx
  src/packages/lottie/demos/taro/demo1.tsx
  src/packages/lottie/demos/taro/demo2.tsx
  src/packages/lottie/demos/taro/demo3.tsx
  src/packages/lottie/doc.en-US.md
  src/packages/lottie/doc.md
  src/packages/lottie/doc.taro.md
  src/packages/lottie/doc.zh-TW.md
  src/packages/lottie/index.taro.ts
  src/packages/lottie/index.ts
  src/packages/lottie/lottie.scss
  src/packages/lottie/mp.taro.tsx
  src/packages/lottie/types.ts
  src/packages/lottie/web.taro.tsx
  src/packages/lottie/web.tsx
  src/styles/variables.scss
  src/utils/platform-taro.ts
  vite.config.ts
  vitest.setup.ts
Labels: size/XXL, 3.x

#2884 feat(Popover): v15 adaption
  package.json
  pnpm-lock.yaml
  src/config.json
  src/packages/address/__test__/__snapshots__/address.spec.tsx.snap
  src/packages/audio/__test__/__snapshots__/audio.spec.tsx.snap
  src/packages/backtop/__test__/__snapshots__/backtop.spec.tsx.snap
  src/packages/badge/__test__/__snapshots__/badge.spec.tsx.snap
  src/packages/cascader/__tests__/__snapshots__/cascader.spec.tsx.snap
  src/packages/checkbox/__test__/__snapshots__/checkbox.spec.tsx.snap
  src/packages/collapse/__test__/__snapshots__/collapse.spec.tsx.snap
  src/packages/grid/__test__/__snapshots__/grid.spec.tsx.snap
  src/packages/hoverbutton/__test__/__snapshots__/hoverbutton.spec.tsx.snap
  src/packages/image/__test__/__snapshots__/image.spec.tsx.snap
  src/packages/menu/__test__/__snapshots__/menu.spec.tsx.snap
  src/packages/noticebar/__test__/__snapshots__/noticebar.spec.tsx.snap
  src/packages/numberkeyboard/_test_/__snapshots__/index.spec.tsx.snap
  src/packages/popover/__tests__/__snapshots__/popover.spec.tsx.snap
  src/packages/popover/__tests__/popover.spec.tsx
  src/packages/popover/demos/h5/demo1.tsx
  src/packages/popover/demos/h5/demo2.tsx
  src/packages/popover/demos/h5/demo4.tsx
  src/packages/popover/demos/taro/demo1.tsx
  src/packages/popover/demos/taro/demo4.tsx
  src/packages/popover/popover.scss
  src/packages/popover/popover.taro.tsx
  src/packages/popover/popover.tsx
  src/packages/rate/__test__/__snapshots__/rate.spec.tsx.snap
  src/packages/resultpage/__test__/__snapshots__/resultpage.spec.tsx.snap
  src/packages/tabbar/__tests__/__snapshots__/tabbar.spec.tsx.snap
  src/packages/timeselect/__test__/__snapshots__/timeselect.spec.tsx.snap
  src/styles/variables.scss
Labels: size/L, 3.x

#2892 chore: adjust codecov patch judge standard
  codecov.yml
Labels: size/S, 3.x

#2899 chore: add dd prop to judge whether to adapt multiplatform
  cypress/e2e/common/pageWhiteTest.cy.js
  gulpfile.js
  packages/nutui-taro-demo/scripts/taro/generate-nutui-taro.js
  packages/nutui-taro-demo/src/pages/index/index.tsx
  scripts/rn/copy-file.js
  scripts/rn/update-taro-entry.js
  scripts/sync-to-taro-playground.js
  scripts/taro/generate-taro-pages.js
  src/config.json
Labels: size/L, 3.x

#2902 feat(uploader): suppport chooseMedia in web
  src/packages/uploader/doc.taro.md
  src/packages/uploader/uploader.taro.tsx
Labels: size/XS, 2.x

#2868 feat(sidebar): develop new component
  migrate-from-v2.md
  src/config.json
  src/packages/sidebar/_test_/sidebar.spec.tsx
  src/packages/sidebar/demo.taro.tsx
  src/packages/sidebar/demo.tsx
  src/packages/sidebar/demos/h5/demo1.tsx
  src/packages/sidebar/demos/h5/demo2.tsx
  src/packages/sidebar/demos/h5/demo3.tsx
  src/packages/sidebar/demos/h5/demo4.tsx
  src/packages/sidebar/demos/h5/demo5.tsx
  src/packages/sidebar/demos/h5/demo6.tsx
  src/packages/sidebar/demos/taro/demo1.tsx
  src/packages/sidebar/demos/taro/demo2.tsx
  src/packages/sidebar/demos/taro/demo3.tsx
  src/packages/sidebar/demos/taro/demo4.tsx
  src/packages/sidebar/demos/taro/demo5.tsx
  src/packages/sidebar/demos/taro/demo6.tsx
  src/packages/sidebar/doc.en-US.md
  src/packages/sidebar/doc.md
  src/packages/sidebar/doc.taro.md
  src/packages/sidebar/doc.zh-TW.md
  src/packages/sidebar/index.taro.ts
  src/packages/sidebar/index.ts
  src/packages/sidebar/sidebar.scss
  src/packages/sidebar/sidebar.taro.tsx
  src/packages/sidebar/sidebar.tsx
  src/packages/sidebar/types.ts
  src/packages/sidebar/utils.ts
  src/packages/sidebaritem/index.taro.ts
  src/packages/sidebaritem/index.ts
  src/packages/sidebaritem/sidebaritem.scss
  src/packages/sidebaritem/sidebaritem.taro.tsx
  src/packages/sidebaritem/sidebaritem.tsx
  src/styles/variables.scss
Labels: size/XXL, 3.x

#2900 feat: dialog v15 adaption
  migrate-from-v2.md
  src/config.json
  src/packages/button/button.scss
  src/packages/button/doc.en-US.md
  src/packages/button/doc.md
  src/packages/button/doc.taro.md
  src/packages/button/doc.zh-TW.md
  src/packages/dialog/demos/taro/demo2.tsx
  src/packages/dialog/dialog.scss
  src/packages/dialog/dialog.taro.tsx
  src/packages/dialog/dialog.tsx
  src/packages/dialog/doc.en-US.md
  src/packages/dialog/doc.md
  src/packages/dialog/doc.taro.md
  src/packages/dialog/doc.zh-TW.md
  src/styles/variables.scss
Labels: size/L, 3.x

#2901 fix: v15 调整radius
  src/styles/variables.scss
Labels: size/XS, 3.x

#2903 feat: tabbar v15 适配
  src/packages/tabbar/__tests__/__snapshots__/tabbar.spec.tsx.snap
  src/packages/tabbar/demos/h5/demo1.tsx
  src/packages/tabbar/demos/h5/demo2.tsx
  src/packages/tabbar/demos/h5/demo4.tsx
  src/packages/tabbar/demos/h5/demo5.tsx
  src/packages/tabbar/demos/h5/demo6.tsx
  src/packages/tabbar/demos/h5/demo7.tsx
  src/packages/tabbar/demos/h5/demo8.tsx
  src/packages/tabbar/demos/h5/demo9.tsx
  src/packages/tabbar/demos/taro/demo1.tsx
  src/packages/tabbar/demos/taro/demo2.tsx
  src/packages/tabbar/demos/taro/demo4.tsx
  src/packages/tabbar/demos/taro/demo6.tsx
  src/packages/tabbar/demos/taro/demo7.tsx
  src/packages/tabbar/demos/taro/demo9.tsx
  src/packages/tabbaritem/tabbaritem.scss
  src/packages/tabbaritem/tabbaritem.taro.tsx
  src/packages/tabbaritem/tabbaritem.tsx
Labels: size/L, 3.x

#2898 feat(pulltorefresh): v15
  src/packages/pulltorefresh/demos/h5/demo1.tsx
  src/packages/pulltorefresh/demos/h5/demo2.tsx
  src/packages/pulltorefresh/demos/taro/demo1.tsx
  src/packages/pulltorefresh/demos/taro/demo3.tsx
  src/packages/pulltorefresh/pulltorefresh.scss
  src/packages/pulltorefresh/pulltorefresh.taro.tsx
  src/packages/pulltorefresh/pulltorefresh.tsx
Labels: size/M, 3.x

#2896 feat: v15 适配demo页面
  packages/nutui-taro-demo/src/pages/index/index.scss
  packages/nutui-taro-demo/src/pages/index/index.tsx
  scripts/taro/generate-taro-pages.js
  src/config.json
  src/sites/mobile/Links.scss
Labels: size/M, 3.x

#2904 fix: rate 的自定义处理
  src/config.json
  src/packages/configprovider/demos/h5/demo2.tsx
  src/packages/configprovider/demos/taro/demo2.tsx
  src/packages/overlay/demos/h5/demo5.tsx
  src/styles/variables.scss
Labels: size/S, 3.x

#2906 fix: cp taro
  src/packages/address/address.taro.tsx
  src/packages/address/existRender.taro.tsx
  src/packages/audio/audio.taro.tsx
  src/packages/avatarcropper/avatarcropper.taro.tsx
  src/packages/backtop/backtop.scss
  src/packages/calendar/calendar.taro.tsx
  src/packages/calendarcard/calendarcard.taro.tsx
  src/packages/calendaritem/calendaritem.taro.tsx
  src/packages/cascader/cascader.taro.tsx
  src/packages/fixednav/fixednav.taro.tsx
  src/packages/infiniteloading/infiniteloading.taro.tsx
  src/packages/inputnumber/demos/taro/demo9.tsx
  src/packages/numberkeyboard/numberkeyboard.taro.tsx
  src/packages/picker/picker.taro.tsx
  src/packages/searchbar/searchbar.taro.tsx
  src/packages/table/table.taro.tsx
  src/packages/textarea/textarea.taro.tsx
  src/packages/timeselect/timeselect.taro.tsx
  src/packages/tour/tour.taro.tsx
  src/packages/uploader/uploader.taro.tsx
Labels: size/M, 3.x

#2908 chore: update alias
  package.json
  packages/nutui-taro-demo/config/index.js
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
  src/config.json
  src/packages/configprovider/types.ts
  src/packages/loading/demos/h5/demo1.tsx
  src/packages/loading/demos/taro/demo1.tsx
  src/packages/lottie/demos/h5/demo1.tsx
  src/packages/lottie/demos/h5/demo2.tsx
  src/packages/lottie/demos/taro/demo1.tsx
  src/packages/lottie/demos/taro/demo2.tsx
  src/packages/lottie/demos/taro/demo3.tsx
  vite.config.site.ts
  vite.config.ts
Labels: size/XL, 3.x

#2905 fix(pulltorefresh): 真机体验优化
  src/packages/loading/demos/taro/demo1.tsx
  src/packages/lottie/mp.taro.tsx
  src/packages/pulltorefresh/pulltorefresh.taro.tsx
Labels: size/S, 3.x
