Repository jdf2e/nutui-react, pull requests merged in 2024-04, with the labels that each got.

#2144 chore(cascader): demo拆解与规范
  src/packages/cascader/demo.taro.tsx
  src/packages/cascader/demo.tsx
  src/packages/cascader/demos/h5/demo1.tsx
  src/packages/cascader/demos/h5/demo2.tsx
  src/packages/cascader/demos/h5/demo3.tsx
  src/packages/cascader/demos/h5/demo4.tsx
  src/packages/cascader/demos/h5/demo5.tsx
  src/packages/cascader/demos/h5/demo6.tsx
  src/packages/cascader/demos/taro/demo1.tsx
  src/packages/cascader/demos/taro/demo2.tsx
  src/packages/cascader/demos/taro/demo3.tsx
  src/packages/cascader/demos/taro/demo4.tsx
  src/packages/cascader/demos/taro/demo5.tsx
  src/packages/cascader/demos/taro/demo6.tsx
  src/packages/cascader/doc.en-US.md
  src/packages/cascader/doc.md
  src/packages/cascader/doc.taro.md
  src/packages/cascader/doc.zh-TW.md
Labels: size/XXL

#2147 chore(countdown): demo拆解与规范
  src/packages/countdown/demo.taro.tsx
  src/packages/countdown/demo.tsx
  src/packages/countdown/demos/h5/demo1.tsx
  src/packages/countdown/demos/h5/demo2.tsx
  src/packages/countdown/demos/h5/demo3.tsx
  src/packages/countdown/demos/h5/demo4.tsx
  src/packages/countdown/demos/h5/demo5.tsx
  src/packages/countdown/demos/h5/demo6.tsx
  src/packages/countdown/demos/h5/demo7.tsx
  src/packages/countdown/demos/h5/demo8.tsx
  src/packages/countdown/demos/h5/demo9.tsx
  src/packages/countdown/demos/taro/demo1.tsx
  src/packages/countdown/demos/taro/demo2.tsx
  src/packages/countdown/demos/taro/demo3.tsx
  src/packages/countdown/demos/taro/demo4.tsx
  src/packages/countdown/demos/taro/demo5.tsx
  src/packages/countdown/demos/taro/demo6.tsx
  src/packages/countdown/demos/taro/demo7.tsx
  src/packages/countdown/demos/taro/demo8.tsx
  src/packages/countdown/demos/taro/demo9.tsx
  src/packages/countdown/doc.en-US.md
  src/packages/countdown/doc.md
  src/packages/countdown/doc.taro.md
  src/packages/countdown/doc.zh-TW.md
Labels: size/XXL

#2150 fix(calendarcard): 直接抛出ondayclick
  src/packages/calendarcard/__tests__/calendarcard.spec.tsx
  src/packages/calendarcard/calendarcard.taro.tsx
  src/packages/calendarcard/calendarcard.tsx
Labels: size/S

#2148 chore(form): demo拆解与规范
  src/packages/form/demo.taro.tsx
  src/packages/form/demo.tsx
  src/packages/form/demos/h5/demo1.tsx
  src/packages/form/demos/h5/demo2.tsx
  src/packages/form/demos/h5/demo3.tsx
  src/packages/form/demos/h5/demo4.tsx
  src/packages/form/demos/h5/demo5.tsx
  src/packages/form/demos/h5/demo6.tsx
  src/packages/form/demos/h5/demo7.tsx
  src/packages/form/demos/taro/demo1.tsx
  src/packages/form/demos/taro/demo2.tsx
  src/packages/form/demos/taro/demo3.tsx
  src/packages/form/demos/taro/demo4.tsx
  src/packages/form/demos/taro/demo5.tsx
  src/packages/form/demos/taro/demo6.tsx
  src/packages/form/demos/taro/demo7.tsx
  src/packages/form/doc.en-US.md
  src/packages/form/doc.md
  src/packages/form/doc.taro.md
  src/packages/form/doc.zh-TW.md
Labels: size/XXL

#2154 feat: Input组件的onFocus方法入参增加键盘高度
  src/packages/input/doc.md
  src/packages/input/input.taro.tsx
Labels: size/XS

#2151 chore(notify): demo拆解与规范
  src/packages/notify/demo.taro.tsx
  src/packages/notify/demo.tsx
  src/packages/notify/demos/h5/demo1.tsx
  src/packages/notify/demos/h5/demo2.tsx
  src/packages/notify/demos/h5/demo3.tsx
  src/packages/notify/demos/h5/demo4.tsx
  src/packages/notify/demos/taro/demo1.tsx
  src/packages/notify/demos/taro/demo2.tsx
  src/packages/notify/demos/taro/demo3.tsx
  src/packages/notify/demos/taro/demo4.tsx
  src/packages/notify/doc.en-US.md
  src/packages/notify/doc.md
  src/packages/notify/doc.taro.md
  src/packages/notify/doc.zh-TW.md
Labels: size/XXL

#2155 chore(loading): demo拆解与规范
  src/packages/loading/demo.taro.tsx
  src/packages/loading/demo.tsx
  src/packages/loading/demos/h5/demo1.tsx
  src/packages/loading/demos/h5/demo2.tsx
  src/packages/loading/demos/h5/demo3.tsx
  src/packages/loading/demos/h5/demo4.tsx
  src/packages/loading/demos/h5/demo5.tsx
  src/packages/loading/demos/h5/demo6.tsx
  src/packages/loading/demos/h5/demo7.tsx
  src/packages/loading/demos/h5/demo8.tsx
  src/packages/loading/demos/taro/demo1.tsx
  src/packages/loading/demos/taro/demo2.tsx
  src/packages/loading/demos/taro/demo3.tsx
  src/packages/loading/demos/taro/demo4.tsx
  src/packages/loading/demos/taro/demo5.tsx
  src/packages/loading/demos/taro/demo6.tsx
  src/packages/loading/demos/taro/demo7.tsx
  src/packages/loading/demos/taro/demo8.tsx
  src/packages/loading/doc.en-US.md
  src/packages/loading/doc.md
  src/packages/loading/doc.taro.md
  src/packages/loading/doc.zh-TW.md
Labels: size/XXL

#2153 chore(menu): demo拆解与规范
  src/packages/menu/demo.taro.tsx
  src/packages/menu/demo.tsx
  src/packages/menu/demos/h5/demo1.tsx
  src/packages/menu/demos/h5/demo2.tsx
  src/packages/menu/demos/h5/demo3.tsx
  src/packages/menu/demos/h5/demo4.tsx
  src/packages/menu/demos/h5/demo5.tsx
  src/packages/menu/demos/h5/demo6.tsx
  src/packages/menu/demos/h5/demo7.tsx
  src/packages/menu/demos/h5/demo8.tsx
  src/packages/menu/demos/taro/demo1.tsx
  src/packages/menu/demos/taro/demo2.tsx
  src/packages/menu/demos/taro/demo3.tsx
  src/packages/menu/demos/taro/demo4.tsx
  src/packages/menu/demos/taro/demo5.tsx
  src/packages/menu/demos/taro/demo6.tsx
  src/packages/menu/demos/taro/demo7.tsx
  src/packages/menu/demos/taro/demo8.tsx
  src/packages/menu/doc.en-US.md
  src/packages/menu/doc.md
  src/packages/menu/doc.taro.md
  src/packages/menu/doc.zh-TW.md
Labels: size/XXL

#2158 chore(radio): demo拆解与规范
  src/packages/radio/demo.taro.tsx
  src/packages/radio/demo.tsx
  src/packages/radio/demos/h5/demo1.tsx
  src/packages/radio/demos/h5/demo10.tsx
  src/packages/radio/demos/h5/demo11.tsx
  src/packages/radio/demos/h5/demo12.tsx
  src/packages/radio/demos/h5/demo2.tsx
  src/packages/radio/demos/h5/demo3.tsx
  src/packages/radio/demos/h5/demo4.tsx
  src/packages/radio/demos/h5/demo5.tsx
  src/packages/radio/demos/h5/demo6.tsx
  src/packages/radio/demos/h5/demo7.tsx
  src/packages/radio/demos/h5/demo8.tsx
  src/packages/radio/demos/h5/demo9.tsx
  src/packages/radio/demos/taro/demo1.tsx
  src/packages/radio/demos/taro/demo10.tsx
  src/packages/radio/demos/taro/demo11.tsx
  src/packages/radio/demos/taro/demo12.tsx
  src/packages/radio/demos/taro/demo2.tsx
  src/packages/radio/demos/taro/demo3.tsx
  src/packages/radio/demos/taro/demo4.tsx
  src/packages/radio/demos/taro/demo5.tsx
  src/packages/radio/demos/taro/demo6.tsx
  src/packages/radio/demos/taro/demo7.tsx
  src/packages/radio/demos/taro/demo8.tsx
  src/packages/radio/demos/taro/demo9.tsx
  src/packages/radio/doc.en-US.md
  src/packages/radio/doc.md
  src/packages/radio/doc.taro.md
  src/packages/radio/doc.zh-TW.md
Labels: size/XXL

#2157 chore(picker): demo拆解与规范
  src/packages/picker/demo.taro.tsx
  src/packages/picker/demo.tsx
  src/packages/picker/demos/h5/demo1.tsx
  src/packages/picker/demos/h5/demo2.tsx
  src/packages/picker/demos/h5/demo3.tsx
  src/packages/picker/demos/h5/demo4.tsx
  src/packages/picker/demos/h5/demo5.tsx
  src/packages/picker/demos/h5/demo6.tsx
  src/packages/picker/demos/h5/demo7.tsx
  src/packages/picker/demos/h5/demo8.tsx
  src/packages/picker/demos/taro/demo1.tsx
  src/packages/picker/demos/taro/demo2.tsx
  src/packages/picker/demos/taro/demo3.tsx
  src/packages/picker/demos/taro/demo4.tsx
  src/packages/picker/demos/taro/demo5.tsx
  src/packages/picker/demos/taro/demo6.tsx
  src/packages/picker/demos/taro/demo7.tsx
  src/packages/picker/demos/taro/demo8.tsx
  src/packages/picker/doc.en-US.md
  src/packages/picker/doc.en.ts
  src/packages/picker/doc.md
  src/packages/picker/doc.taro.md
  src/packages/picker/doc.zh-TW.md
Labels: size/XXL

#2162 fix(form): 可定义 fontsize
  src/packages/form/form.scss
Labels: size/XS

#2163 fix(drag): demo拆解与规范
  src/packages/drag/demo.taro.tsx
  src/packages/drag/demo.tsx
  src/packages/drag/demos/h5/demo1.tsx
  src/packages/drag/demos/h5/demo2.tsx
  src/packages/drag/demos/h5/demo3.tsx
  src/packages/drag/demos/h5/demo4.tsx
  src/packages/drag/demos/taro/demo1.tsx
  src/packages/drag/demos/taro/demo2.tsx
  src/packages/drag/demos/taro/demo3.tsx
  src/packages/drag/demos/taro/demo4.tsx
  src/packages/drag/doc.en-US.md
  src/packages/drag/doc.md
  src/packages/drag/doc.taro.md
  src/packages/drag/doc.zh-TW.md
Labels: size/XL

#2167 fix(swiper): fix the issue that indicators fail to render during async loading in Taro
  src/packages/swiper/swiper.taro.tsx
Labels: size/S

#2178 fix(site): png url error & key duplicate
  src/sites/doc/components/header/header.scss
  src/sites/doc/components/nav/nav.tsx
Labels: size/XS

#2176 fix(CellGroup): 去掉CellGroup组件未单独使用的style属性的参数结构
  src/packages/cellgroup/cellgroup.taro.tsx
  src/packages/cellgroup/cellgroup.tsx
Labels: size/XS

#2181 Update fixednav.scss
  src/packages/fixednav/fixednav.scss
Labels: size/XS

#2164 style(badge): jmapp style
  src/packages/badge/badge.scss
  src/packages/badge/doc.en-US.md
  src/packages/badge/doc.md
  src/packages/badge/doc.taro.md
  src/packages/badge/doc.zh-TW.md
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/S

#2188 fix(inputnumber): 修复设置`InputNumber`组件className不生效的问题
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/inputnumber/inputnumber.tsx
Labels: size/XS

#2189 style(CellGroup): 给`CellGroup`组件新增外边距样式变量，使得使用者可以自由控制该外边距。
  src/packages/cell/doc.en-US.md
  src/packages/cell/doc.md
  src/packages/cell/doc.taro.md
  src/packages/cell/doc.zh-TW.md
  src/packages/cellgroup/cellgroup.scss
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/S

#2200 fix(ellipsis): 部分场景下的ref报错
  src/packages/ellipsis/ellipsis.taro.tsx
Labels: size/XS

#2194 fix: 批量调整 div 为 View
  packages/nutui-taro-demo/src/app.scss
  src/packages/animate/animate.taro.tsx
  src/packages/avatar/avatar.taro.tsx
  src/packages/avatargroup/avatargroup.taro.tsx
  src/packages/backtop/backtop.taro.tsx
  src/packages/cell/cell.taro.tsx
  src/packages/cellgroup/cellgroup.taro.tsx
  src/packages/configprovider/configprovider.taro.tsx
  src/packages/countdown/countdown.taro.tsx
  src/packages/dialog/content.taro.tsx
  src/packages/empty/empty.taro.tsx
  src/packages/indicator/indicator.taro.tsx
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/layout/demo.taro.tsx
  src/packages/layout/layout.taro.tsx
  src/packages/notify/notify.taro.tsx
  src/packages/popup/popup.taro.tsx
  src/packages/price/price.taro.tsx
  src/packages/pulltorefresh/pulltorefresh.taro.tsx
  src/packages/radio/radio.taro.tsx
  src/packages/rate/rate.taro.tsx
  src/packages/row/row.taro.tsx
  src/packages/safearea/safearea.taro.tsx
  src/packages/searchbar/searchbar.taro.tsx
  src/packages/space/space.taro.tsx
  src/packages/swipe/swipe.taro.tsx
  src/packages/swiper/swiper.taro.tsx
  src/packages/tag/tag.taro.tsx
  src/packages/textarea/textarea.taro.tsx
  src/packages/toast/toast.taro.tsx
  src/packages/tour/tour.taro.tsx
Labels: size/L

#2204 docs(tag):修复demo描述错误
  src/packages/tag/doc.taro.md
Labels: size/XS

#2052 style: jmapp style 语义化
  src/packages/navbar/demo.scss
  src/packages/navbar/demos/h5/demo2.tsx
  src/packages/navbar/demos/taro/demo2.tsx
  src/packages/navbar/navbar.scss
  src/styles/theme-jmapp.scss
  src/styles/variables-jmapp.scss
Labels: size/L

#2192 feat(dialog): 优化dialog组件，增加 `确认/取消按钮` 属性设置
  src/packages/dialog/config.ts
  src/packages/dialog/demos/h5/demo1.tsx
  src/packages/dialog/demos/taro/demo2.tsx
  src/packages/dialog/dialog.taro.tsx
  src/packages/dialog/dialog.tsx
  src/packages/dialog/doc.en-US.md
  src/packages/dialog/doc.md
  src/packages/dialog/doc.taro.md
  src/packages/dialog/doc.zh-TW.md
Labels: size/M

#2201 fix(datepicker): 修复受控方式下选项联动更新问题
  src/packages/datepicker/datepicker.taro.tsx
  src/packages/datepicker/datepicker.tsx
  src/packages/datepicker/demos/h5/demo1.tsx
  src/packages/datepicker/demos/taro/demo1.tsx
Labels: size/M

#2205 fix(overlay): RN适配
  packages/nutui-harmony/.gitignore
  packages/nutui-taro-demo-rn/nutui-react/config.json
  packages/nutui-taro-demo-rn/nutui-react/packages/nutui.react.taro.ts
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demo.taro.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demo.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demos/h5/demo1.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demos/h5/demo2.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demos/h5/demo3.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demos/h5/demo4.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demos/h5/demo5.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demos/h5/demo6.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demos/taro/demo1.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demos/taro/demo2.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demos/taro/demo3.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demos/taro/demo4.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demos/taro/demo5.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/demos/taro/demo6.tsx
  packages/nutui-taro-demo-rn/nutui-react/packages/overlay/overlay.taro.tsx
  packages/nutui-taro-demo-rn/src/base/pages/overlay/index.config.ts
  packages/nutui-taro-demo-rn/src/base/pages/overlay/index.tsx
  scripts/rn/copy-file.js
  src/packages/overlay/demo.taro.tsx
  src/packages/overlay/demo.tsx
  src/packages/overlay/demos/h5/demo1.tsx
  src/packages/overlay/demos/h5/demo2.tsx
  src/packages/overlay/demos/h5/demo3.tsx
  src/packages/overlay/demos/h5/demo4.tsx
  src/packages/overlay/demos/h5/demo5.tsx
  src/packages/overlay/demos/h5/demo6.tsx
  src/packages/overlay/demos/taro/demo1.tsx
  src/packages/overlay/demos/taro/demo2.tsx
  src/packages/overlay/demos/taro/demo3.tsx
  src/packages/overlay/demos/taro/demo4.tsx
  src/packages/overlay/demos/taro/demo5.tsx
  src/packages/overlay/demos/taro/demo6.tsx
  src/packages/overlay/overlay.taro.tsx
Labels: size/L

#2211 fix(tabs): 修复特殊场景下 value 设置未生效问题
  src/packages/tabs/tabs.taro.tsx
  src/packages/tabs/tabs.tsx
Labels: size/M

#2210 style(Tabs.Tabpane): 给Tabs.Tabpane新增内边距样式变量，使得使用者可以自由控制该内边距。
  src/packages/tabpane/tabpane.scss
  src/packages/tabs/doc.en-US.md
  src/packages/tabs/doc.md
  src/packages/tabs/doc.taro.md
  src/packages/tabs/doc.zh-TW.md
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/XS

#2214 chore(icon): update demo
  src/packages/icon/demos/h5/demo7.tsx
  src/packages/icon/demos/taro/demo7.tsx
Labels: size/S
