Repository jdf2e/nutui-react, pull requests merged in 2024-01, with the labels that each got.

#1902 fix(ellipsis): 在taro 小程序下尽量展示的平滑舒适
  src/packages/ellipsis/ellipsis.taro.tsx
  src/packages/ellipsis/ellipsis.tsx
Labels: size/M

#1898 feat: radiogroup add shape props
  src/packages/radio/__test__/radio.spec.tsx
  src/packages/radio/demo.taro.tsx
  src/packages/radio/demo.tsx
  src/packages/radio/doc.en-US.md
  src/packages/radio/doc.md
  src/packages/radio/doc.taro.md
  src/packages/radio/doc.zh-TW.md
  src/packages/radio/index.taro.ts
  src/packages/radio/index.ts
  src/packages/radio/radio.taro.tsx
  src/packages/radio/radio.tsx
  src/packages/radio/types.ts
  src/packages/radiogroup/context.ts
  src/packages/radiogroup/index.taro.ts
  src/packages/radiogroup/index.ts
  src/packages/radiogroup/radiogroup.taro.tsx
  src/packages/radiogroup/radiogroup.tsx
  src/packages/radiogroup/types.ts
Labels: size/L

#1887 fix(image): 文档可读性优化
  src/packages/image/demo.taro.tsx
  src/packages/image/demo.tsx
  src/packages/image/doc.en-US.md
  src/packages/image/doc.md
  src/packages/image/doc.taro.md
  src/packages/image/doc.zh-TW.md
  src/packages/overlay/doc.taro.md
Labels: size/XL

#1894 fix(overlay): 文档可读性优化
  src/packages/overlay/demo.taro.tsx
  src/packages/overlay/demo.tsx
  src/packages/overlay/doc.en-US.md
  src/packages/overlay/doc.md
  src/packages/overlay/doc.taro.md
  src/packages/overlay/doc.zh-TW.md
Labels: size/L

#1880 feat(rate): 新增 touchable 属性支持滑动选择
  src/packages/rate/__test__/rate.spec.tsx
  src/packages/rate/demo.taro.tsx
  src/packages/rate/demo.tsx
  src/packages/rate/doc.en-US.md
  src/packages/rate/doc.md
  src/packages/rate/doc.taro.md
  src/packages/rate/doc.zh-TW.md
  src/packages/rate/rate.scss
  src/packages/rate/rate.taro.tsx
  src/packages/rate/rate.tsx
Labels: size/XL

#1882 docs(configprovider): 文档可读性优化
  src/packages/button/doc.md
  src/packages/button/doc.taro.md
  src/packages/button/doc.zh-TW.md
  src/packages/configprovider/demo.taro.tsx
  src/packages/configprovider/demo.tsx
  src/packages/configprovider/doc.en-US.md
  src/packages/configprovider/doc.md
  src/packages/configprovider/doc.taro.md
  src/packages/configprovider/doc.zh-TW.md
Labels: size/L

#1903 docs(grid): 文档可读性优化
  src/packages/grid/demo.taro.tsx
  src/packages/grid/demo.tsx
  src/packages/grid/doc.en-US.md
  src/packages/grid/doc.md
  src/packages/grid/doc.taro.md
  src/packages/grid/doc.zh-TW.md
Labels: size/L

#1905 chore: 修复dev环境下Demo分包体超过2M问题
  packages/nutui-taro-demo/.gitignore
  packages/nutui-taro-demo/src/app.config.ts
  packages/nutui-taro-demo/src/pages/index/index.tsx
  src/config.json
  src/sites/doc/components/nav/nav.tsx
Labels: size/L

#1907 fix: taro.createSelectorQuery not function
  src/packages/avatarcropper/avatarcropper.taro.tsx
  src/packages/collapseitem/collapseitem.taro.tsx
  src/packages/popover/popover.taro.tsx
  src/packages/tabs/tabs.taro.tsx
  src/utils/use-taro-rect.ts
Labels: size/S

#1891 feat(navbar): title区域自适应宽度
  src/packages/navbar/__test__/__snapshots__/navbar.spec.tsx.snap
  src/packages/navbar/demo.scss
  src/packages/navbar/demo.taro.tsx
  src/packages/navbar/demo.tsx
  src/packages/navbar/doc.en-US.md
  src/packages/navbar/doc.md
  src/packages/navbar/doc.taro.md
  src/packages/navbar/doc.zh-TW.md
  src/packages/navbar/navbar.scss
  src/packages/navbar/navbar.taro.tsx
  src/packages/navbar/navbar.tsx
Labels: size/L

#1906 docs(sticky): 文档可读性优化
  src/packages/sticky/demo.taro.tsx
  src/packages/sticky/demo.tsx
  src/packages/sticky/doc.en-US.md
  src/packages/sticky/doc.md
  src/packages/sticky/doc.taro.md
  src/packages/sticky/doc.zh-TW.md
Labels: size/XL

#1909 docs(backtop): 文档可读性优化
  src/packages/backtop/demo.taro.tsx
  src/packages/backtop/demo.tsx
  src/packages/backtop/doc.en-US.md
  src/packages/backtop/doc.md
  src/packages/backtop/doc.taro.md
  src/packages/backtop/doc.zh-TW.md
Labels: size/L

#1904 docs(layout): 文档可读性优化
  src/packages/layout/demo.taro.tsx
  src/packages/layout/demo.tsx
  src/packages/layout/doc.en-US.md
  src/packages/layout/doc.md
  src/packages/layout/doc.taro.md
  src/packages/layout/doc.zh-TW.md
Labels: size/XXL

#1910 fix(textarea): 修复maxlength=-1时无法输入字符的情况
  src/packages/textarea/textarea.taro.tsx
  src/packages/textarea/textarea.tsx
Labels: size/XS

#1916 docs(image): correct the error attribute
  src/packages/image/doc.en-US.md
  src/packages/image/doc.md
  src/packages/image/doc.zh-TW.md
Labels: size/S

#1914 fix(popup): support destroyOnClose
  src/packages/address/__test__/address.spec.tsx
  src/packages/popup/demo.taro.tsx
  src/packages/popup/demo.tsx
  src/packages/popup/popup.scss
  src/packages/popup/popup.taro.tsx
  src/packages/popup/popup.tsx
Labels: size/M

#1917 fix: migrate husky v9
  .husky/pre-commit
  package.json
Labels: size/XS

#1915 docs(navbar): 文档可读性优化
  src/packages/navbar/demo.taro.tsx
  src/packages/navbar/demo.tsx
  src/packages/navbar/doc.en-US.md
  src/packages/navbar/doc.md
  src/packages/navbar/doc.taro.md
  src/packages/navbar/doc.zh-TW.md
Labels: size/XXL

#1919 fix(infiniteloading): 解决infiniteloading触发点击操作后再滑动时，滑动操作异常的问题
  src/packages/infiniteloading/infiniteloading.taro.tsx
  src/packages/infiniteloading/infiniteloading.tsx
Labels: size/XS
