Repository jdf2e/nutui-react, pull requests merged in 2024-06, with the labels that each got.

#2273 feat(image): 适配鸿蒙&RN
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/base/pages/image/index.config.ts
  packages/nutui-taro-demo-rn/src/base/pages/image/index.tsx
  src/packages/image/demo.taro.tsx
  src/packages/image/demos/taro/demo2.tsx
  src/packages/image/demos/taro/demo3.tsx
  src/packages/image/demos/taro/demo4.tsx
  src/packages/image/demos/taro/demo5.tsx
  src/packages/image/demos/taro/demo6.tsx
  src/packages/image/demos/taro/demo7.tsx
  src/packages/image/image.harmony.css
  src/packages/image/image.taro.tsx
Labels: size/L

#2311 fix: 修改image的demo样式，适配 鸿蒙
  src/packages/image/demos/taro/demo1.tsx
  src/packages/image/demos/taro/demo2.tsx
  src/packages/image/demos/taro/demo5.tsx
  src/packages/image/demos/taro/demo6.tsx
  src/packages/image/demos/taro/demo7.tsx
Labels: size/M

#2317 feat(overlay): 适配鸿蒙、RN、小程序、H5
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  src/config.json
  src/packages/overlay/demo.taro.tsx
  src/packages/overlay/demos/taro/demo1.tsx
  src/packages/overlay/demos/taro/demo2.tsx
  src/packages/overlay/demos/taro/demo3.tsx
  src/packages/overlay/demos/taro/demo4.tsx
  src/packages/overlay/demos/taro/demo5.tsx
  src/packages/overlay/demos/taro/demo6.tsx
  src/packages/overlay/overlay.harmony.css
  src/packages/overlay/overlay.scss
  src/packages/overlay/overlay.taro.tsx
Labels: size/L

#2319 feat(swiper): 适配鸿蒙、RN、小程序、H5
  .npmrc
  packages/nutui-taro-demo-rn/package.json
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/exhibition/pages/swiper/index.config.ts
  packages/nutui-taro-demo-rn/src/exhibition/pages/swiper/index.tsx
  packages/nutui-taro-demo/package.json
  src/packages/swiper/demo.taro.tsx
  src/packages/swiper/demos/taro/demo1.tsx
  src/packages/swiper/demos/taro/demo2.tsx
  src/packages/swiper/demos/taro/demo3.tsx
  src/packages/swiper/demos/taro/demo4.tsx
  src/packages/swiper/demos/taro/demo5.tsx
  src/packages/swiper/demos/taro/demo6.tsx
  src/packages/swiper/demos/taro/demo7.tsx
  src/packages/swiper/demos/taro/demo8.tsx
  src/packages/swiper/demos/taro/demo9.tsx
  src/packages/swiper/swiper.harmony.css
  src/packages/swiper/swiper.scss
  src/packages/swiper/swiper.taro.tsx
  src/utils/px-check.ts
  src/utils/px-transform.ts
Labels: size/L

#2296 feat: TextArea RN 适配
  .npmrc
  package.json
  packages/nutui-taro-demo-rn/config/index.js
  packages/nutui-taro-demo-rn/package.json
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo/config/index.js
  packages/nutui-taro-demo/global.d.ts
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
  src/packages/configprovider/configprovider.tsx
  src/packages/textarea/demo.taro.tsx
  src/packages/textarea/demos/taro/demo1.tsx
  src/packages/textarea/textarea.harmony.css
  src/packages/textarea/textarea.scss
  src/packages/textarea/textarea.taro.tsx
  src/packages/textarea/textarea.tsx
Labels: size/XXL

#2306 fix: indicator rn & harmony
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  src/packages/indicator/demo.taro.tsx
  src/packages/indicator/demos/taro/demo2.tsx
  src/packages/indicator/demos/taro/demo3.tsx
  src/packages/indicator/demos/taro/demo4.tsx
Labels: size/M

#2344 fix: 环境判断统一使用platform-taro 中的方法
  src/packages/cell/cell.taro.tsx
  src/packages/cell/demos/taro/demo6.tsx
  src/packages/countdown/countdown.taro.tsx
  src/packages/countdown/demos/taro/demo8.tsx
  src/packages/divider/demos/taro/demo5.tsx
  src/packages/image/demo.taro.tsx
  src/packages/image/demos/taro/demo1.tsx
  src/packages/image/demos/taro/demo2.tsx
  src/packages/image/demos/taro/demo5.tsx
  src/packages/image/demos/taro/demo6.tsx
  src/packages/image/demos/taro/demo7.tsx
  src/packages/image/image.taro.tsx
  src/packages/indicator/demos/taro/demo2.tsx
  src/packages/indicator/demos/taro/demo4.tsx
  src/packages/overlay/demo.taro.tsx
  src/packages/overlay/demos/taro/demo5.tsx
  src/packages/overlay/demos/taro/demo6.tsx
  src/packages/overlay/overlay.taro.tsx
  src/packages/pagination/demos/taro/demo5.tsx
  src/packages/price/demos/taro/demo8.tsx
  src/packages/swiper/demo.taro.tsx
  src/packages/swiper/demos/taro/demo5.tsx
  src/packages/textarea/demos/taro/demo1.tsx
  src/packages/toast/demo.taro.tsx
  src/utils/platform-taro.ts
Labels: size/L

#2262 fix(searchbar): 修复 clear 时未触发 change 的问题
  src/packages/searchbar/__tests__/searchbar.spec.tsx
  src/packages/searchbar/demos/h5/demo7.tsx
  src/packages/searchbar/demos/taro/demo7.tsx
  src/packages/searchbar/searchbar.taro.tsx
  src/packages/searchbar/searchbar.tsx
Labels: size/M

#2345 feat(form): footer 容器增加 className
  src/packages/form/form.taro.tsx
  src/packages/form/form.tsx
Labels: size/XS

#2321 feat: hoverbutton
  packages/nutui-harmony/entry/src/main/resources/base/profile/main_pages.json
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/app.config.ts
  packages/nutui-taro-demo-rn/src/layout/pages/safearea/index.config.ts
  packages/nutui-taro-demo-rn/src/layout/pages/safearea/index.tsx
  packages/nutui-taro-demo-rn/src/nav/pages/hoverbutton/index.config.ts
  packages/nutui-taro-demo-rn/src/nav/pages/hoverbutton/index.tsx
  packages/nutui-taro-demo-rn/src/nav/pages/hoverbuttonitem/index.config.ts
  packages/nutui-taro-demo-rn/src/nav/pages/hoverbuttonitem/index.tsx
  packages/nutui-taro-demo-rn/yarn.lock
  packages/nutui-taro-demo/project.config.json
  packages/nutui-taro-demo/src/app.config.ts
  pnpm-lock.yaml
  src/config.json
  src/packages/configprovider/types.ts
  src/packages/hoverbutton/__test__/__snapshots__/hoverbutton.spec.tsx.snap
  src/packages/hoverbutton/__test__/hoverbutton.spec.tsx
  src/packages/hoverbutton/demo.scss
  src/packages/hoverbutton/demo.taro.tsx
  src/packages/hoverbutton/demo.tsx
  src/packages/hoverbutton/demos/h5/demo1.tsx
  src/packages/hoverbutton/demos/h5/demo2.tsx
  src/packages/hoverbutton/demos/h5/demo3.tsx
  src/packages/hoverbutton/demos/h5/demo4.tsx
  src/packages/hoverbutton/demos/h5/demo5.tsx
  src/packages/hoverbutton/demos/taro/demo1-rn.tsx
  src/packages/hoverbutton/demos/taro/demo1.tsx
  src/packages/hoverbutton/demos/taro/demo2-rn.tsx
  src/packages/hoverbutton/demos/taro/demo2.tsx
  src/packages/hoverbutton/demos/taro/demo3-rn.tsx
  src/packages/hoverbutton/demos/taro/demo3.tsx
  src/packages/hoverbutton/demos/taro/demo4-rn.tsx
  src/packages/hoverbutton/demos/taro/demo4.tsx
  src/packages/hoverbutton/demos/taro/demo5.tsx
  src/packages/hoverbutton/doc.en-US.md
  src/packages/hoverbutton/doc.md
  src/packages/hoverbutton/doc.taro.md
  src/packages/hoverbutton/doc.zh-TW.md
  src/packages/hoverbutton/hoverbutton.harmony.css
  src/packages/hoverbutton/hoverbutton.scss
  src/packages/hoverbutton/hoverbutton.taro.tsx
  src/packages/hoverbutton/hoverbutton.tsx
  src/packages/hoverbutton/index.taro.ts
  src/packages/hoverbutton/index.ts
  src/packages/hoverbuttonitem/hoverbuttonitem.harmony.css
  src/packages/hoverbuttonitem/hoverbuttonitem.scss
  src/packages/hoverbuttonitem/hoverbuttonitem.taro.tsx
  src/packages/hoverbuttonitem/hoverbuttonitem.tsx
  src/packages/hoverbuttonitem/index.taro.ts
  src/packages/hoverbuttonitem/index.ts
  src/packages/resultpage/__test__/__snapshots__/resultpage.spec.tsx.snap
  src/packages/safearea/demo.taro.tsx
  src/packages/safearea/demos/taro/demo1.tsx
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/XXL

#2352 fix(Cell): 调整cell的行高，适配rn
  src/packages/cell/cell.harmony.css
  src/packages/cell/cell.scss
Labels: size/S

#2330 fix: 解决Drag组件拖拽后会在原地留一个遮挡元素问题+解决weapp/taro-h5多个demo拖拽位置不正确问题
  src/packages/drag/__test__/__snapshots__/drag.spec.tsx.snap
  src/packages/drag/demo.taro.tsx
  src/packages/drag/demos/taro/demo1.tsx
  src/packages/drag/demos/taro/demo2.tsx
  src/packages/drag/demos/taro/demo3.tsx
  src/packages/drag/demos/taro/demo4.tsx
  src/packages/drag/drag.scss
  src/packages/drag/drag.taro.tsx
  src/packages/drag/drag.tsx
Labels: size/M

#2309 feat: skeleton RN & Harmony
  packages/nutui-harmony/entry/src/main/resources/base/profile/main_pages.json
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/feedback/pages/skeleton/index.tsx
  src/config.json
  src/packages/skeleton/demo.scss
  src/packages/skeleton/demo.taro.tsx
  src/packages/skeleton/demo.tsx
  src/packages/skeleton/demos/h5/demo5.tsx
  src/packages/skeleton/demos/taro/demo5.tsx
  src/packages/skeleton/skeleton.harmony.css
  src/packages/skeleton/skeleton.scss
  src/packages/skeleton/skeleton.taro.tsx
  src/packages/skeleton/skeleton.tsx
Labels: size/L

#2347 fix(configprovider): demo 适配 rn & harmony, 调整 cell rtl 样式
  packages/nutui-harmony/entry/src/main/resources/base/profile/main_pages.json
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  src/config.json
  src/packages/cell/cell.harmony.css
  src/packages/cell/cell.scss
  src/packages/configprovider/demos/h5/demo5.tsx
  src/packages/configprovider/demos/taro/demo1.tsx
  src/packages/configprovider/demos/taro/demo2.tsx
  src/packages/configprovider/demos/taro/demo5.tsx
Labels: size/M

#2338 feat(input): 适配鸿蒙、小程序、H5、RN; 鸿蒙下无法隐藏密码Icon
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/app.config.ts
  packages/nutui-taro-demo-rn/src/dentry/pages/input/index.config.ts
  packages/nutui-taro-demo-rn/src/dentry/pages/input/index.tsx
  src/config.json
  src/packages/input/demo.taro.tsx
  src/packages/input/demos/taro/demo1.tsx
  src/packages/input/demos/taro/demo10.tsx
  src/packages/input/demos/taro/demo11.tsx
  src/packages/input/demos/taro/demo12.tsx
  src/packages/input/demos/taro/demo13.tsx
  src/packages/input/demos/taro/demo14.tsx
  src/packages/input/demos/taro/demo2.tsx
  src/packages/input/demos/taro/demo3.tsx
  src/packages/input/demos/taro/demo4.tsx
  src/packages/input/demos/taro/demo5.tsx
  src/packages/input/demos/taro/demo6.tsx
  src/packages/input/demos/taro/demo7.tsx
  src/packages/input/demos/taro/demo8.tsx
  src/packages/input/demos/taro/demo9.tsx
  src/packages/input/input.harmony.css
  src/packages/input/input.scss
  src/packages/input/input.taro.tsx
Labels: size/L

#2362 refactor: pxtransform 中的判断条件采用公共方法
  src/utils/px-transform.ts
Labels: size/S

#2363 feat: 增加 react native 下获取元素布局信息的逻辑
  src/utils/get-rect-by-taro.ts
Labels: size/S

#2353 fix(inputnumber): 适配RN和鸿蒙，加减按钮icon在RN和鸿蒙暂不展示
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/dentry/pages/inputnumber/index.tsx
  src/config.json
  src/packages/inputnumber/demo.taro.tsx
  src/packages/inputnumber/demo.tsx
  src/packages/inputnumber/demos/h5/demo1.tsx
  src/packages/inputnumber/demos/h5/demo2.tsx
  src/packages/inputnumber/demos/h5/demo3.tsx
  src/packages/inputnumber/demos/h5/demo4.tsx
  src/packages/inputnumber/demos/h5/demo5.tsx
  src/packages/inputnumber/demos/h5/demo7.tsx
  src/packages/inputnumber/demos/h5/demo8.tsx
  src/packages/inputnumber/demos/taro/demo1.tsx
  src/packages/inputnumber/demos/taro/demo2.tsx
  src/packages/inputnumber/demos/taro/demo3.tsx
  src/packages/inputnumber/demos/taro/demo4.tsx
  src/packages/inputnumber/demos/taro/demo5.tsx
  src/packages/inputnumber/demos/taro/demo6.tsx
  src/packages/inputnumber/demos/taro/demo7.tsx
  src/packages/inputnumber/demos/taro/demo8.tsx
  src/packages/inputnumber/demos/taro/demo9.tsx
  src/packages/inputnumber/inputnumber.harmony.css
  src/packages/inputnumber/inputnumber.scss
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/inputnumber/inputnumber.tsx
  src/styles/variables.scss
Labels: size/L

#2366 feat(tabpane): 增添修改tabpane背景色的主题变量
  src/packages/tabpane/tabpane.scss
  src/packages/tabs/doc.en-US.md
  src/packages/tabs/doc.md
  src/packages/tabs/doc.taro.md
  src/packages/tabs/doc.zh-TW.md
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/S

#2343 feat(avatar): rn 适配
  packages/nutui-harmony/build-profile.json5
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/exhibition/pages/avatar/index.tsx
  pnpm-lock.yaml
  scripts/rn/copy-file.js
  src/config.json
  src/packages/avatar/avatar.harmony.css
  src/packages/avatar/avatar.scss
  src/packages/avatar/avatar.taro.tsx
  src/packages/avatar/avatar.tsx
  src/packages/avatar/demo.scss
  src/packages/avatar/demo.taro.tsx
  src/packages/avatar/demo.tsx
  src/packages/avatar/demos/h5/demo1.tsx
  src/packages/avatar/demos/h5/demo2.tsx
  src/packages/avatar/demos/h5/demo3.tsx
  src/packages/avatar/demos/h5/demo4.tsx
  src/packages/avatar/demos/h5/demo5.tsx
  src/packages/avatar/demos/h5/demo7.tsx
  src/packages/avatar/demos/h5/demo8.tsx
  src/packages/avatar/demos/h5/demo9.tsx
  src/packages/avatar/demos/taro/demo1.tsx
  src/packages/avatar/demos/taro/demo2.tsx
  src/packages/avatar/demos/taro/demo3.tsx
  src/packages/avatar/demos/taro/demo4.tsx
  src/packages/avatar/demos/taro/demo5.tsx
  src/packages/avatar/demos/taro/demo6.tsx
  src/packages/avatar/demos/taro/demo7.tsx
  src/packages/avatar/demos/taro/demo8.tsx
  src/packages/avatar/demos/taro/demo9.tsx
  src/packages/avatar/doc.taro.md
  src/packages/avatargroup/avatargroup.harmony.css
  src/packages/avatargroup/avatargroup.scss
  src/packages/avatargroup/avatargroup.taro.tsx
  src/packages/image/image.scss
  src/packages/image/image.taro.tsx
  src/packages/image/image.tsx
Labels: size/XXL

#2326 chore(swipe): 适配鸿蒙、小程序、H5
  packages/nutui-harmony/entry/src/main/resources/base/profile/main_pages.json
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/app.config.ts
  packages/nutui-taro-demo-rn/src/feedback/pages/swipe/index.config.ts
  packages/nutui-taro-demo-rn/src/feedback/pages/swipe/index.tsx
  src/packages/swipe/demo.taro.tsx
  src/packages/swipe/demo.tsx
  src/packages/swipe/demos/h5/demo1.tsx
  src/packages/swipe/demos/h5/demo2.tsx
  src/packages/swipe/demos/h5/demo3.tsx
  src/packages/swipe/demos/h5/demo4.tsx
  src/packages/swipe/demos/h5/demo5.tsx
  src/packages/swipe/demos/h5/demo6.tsx
  src/packages/swipe/demos/h5/demo7.tsx
  src/packages/swipe/demos/h5/demo8.tsx
  src/packages/swipe/demos/h5/demo9.tsx
  src/packages/swipe/demos/taro/demo1.tsx
  src/packages/swipe/demos/taro/demo2.tsx
  src/packages/swipe/demos/taro/demo3.tsx
  src/packages/swipe/demos/taro/demo4.tsx
  src/packages/swipe/demos/taro/demo5.tsx
  src/packages/swipe/demos/taro/demo6.tsx
  src/packages/swipe/demos/taro/demo7.tsx
  src/packages/swipe/demos/taro/demo8.tsx
  src/packages/swipe/demos/taro/demo9.tsx
  src/packages/swipe/swipe.harmony.css
  src/packages/swipe/swipe.scss
  src/packages/swipe/swipe.taro.tsx
  src/utils/use-touch.ts
Labels: size/XXL

#2357 Feat/range 适配 JDRN、鸿蒙端
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  packages/nutui-taro-demo-rn/src/app.config.ts
  packages/nutui-taro-demo-rn/src/dentry1/pages/range/index.config.ts
  packages/nutui-taro-demo-rn/src/dentry1/pages/range/index.tsx
  src/config.json
  src/packages/range/demos/h5/demo11.tsx
  src/packages/range/demos/taro/demo1.tsx
  src/packages/range/demos/taro/demo10.tsx
  src/packages/range/demos/taro/demo11.tsx
  src/packages/range/demos/taro/demo12.tsx
  src/packages/range/demos/taro/demo13.tsx
  src/packages/range/demos/taro/demo2.tsx
  src/packages/range/demos/taro/demo3.tsx
  src/packages/range/demos/taro/demo4.tsx
  src/packages/range/demos/taro/demo5.tsx
  src/packages/range/demos/taro/demo6.tsx
  src/packages/range/demos/taro/demo7.tsx
  src/packages/range/demos/taro/demo8.tsx
  src/packages/range/demos/taro/demo9.tsx
  src/packages/range/range.harmony.css
  src/packages/range/range.scss
  src/packages/range/range.taro.tsx
  src/packages/range/range.tsx
  src/utils/use-touch.ts
Labels: size/XXL

#2368 fix: umd 中替换环境变量
  package.json
  pnpm-lock.yaml
  vite.config.build.ts
Labels: size/M

#2369 fix(tabs): 修复tabs异步设置titles滚动失效（#2351）
  src/packages/tabs/tabs.tsx
Labels: size/XS

#2376 feat: cell引入cellgroup样式文件
  src/packages/cell/cell.harmony.css
  src/packages/cell/cell.scss
Labels: size/S

#2377 fix: 修改同步内容,删除config.json
  scripts/sync-to-taro-playground.js
Labels: size/S

#2375 fix: button css 简化 和 Demo 调整
  src/packages/button/button.harmony.css
  src/packages/button/button.scss
  src/packages/button/button.taro.tsx
  src/packages/button/demo.taro.tsx
  src/packages/button/demos/h5/demo2.tsx
  src/packages/button/demos/taro/demo1.tsx
  src/packages/button/demos/taro/demo10.tsx
  src/packages/button/demos/taro/demo2.tsx
  src/packages/button/demos/taro/demo3.tsx
  src/packages/button/demos/taro/demo4.tsx
  src/packages/button/demos/taro/demo5.tsx
  src/packages/button/demos/taro/demo6.tsx
  src/packages/button/demos/taro/demo7.tsx
  src/packages/button/demos/taro/demo8.tsx
  src/packages/button/demos/taro/demo9.tsx
  src/styles/variables.scss
Labels: size/XL

#2371 fix: layout无背景色、swiper 分页器不居中
  packages/nutui-taro-demo-rn/src/base/pages/cell/index.config.ts
  src/packages/indicator/indicator.harmony.css
  src/packages/indicator/indicator.scss
  src/packages/layout/demos/taro/demo2.tsx
  src/packages/layout/demos/taro/demo3.tsx
Labels: size/XS

#2382 fix(Button): RN & 鸿蒙适配
  src/config.json
  src/packages/button/button.harmony.css
  src/packages/button/button.scss
  src/packages/button/button.taro.tsx
  src/packages/button/button.tsx
  src/packages/button/demo.taro.tsx
  src/packages/button/demos/taro/demo10.tsx
  src/packages/button/demos/taro/demo2.tsx
  src/packages/button/demos/taro/demo3.tsx
  src/packages/button/demos/taro/demo4.tsx
  src/packages/button/demos/taro/demo5.tsx
  src/packages/button/demos/taro/demo6.tsx
  src/packages/button/demos/taro/demo7.tsx
  src/packages/button/demos/taro/demo8.tsx
Labels: size/XL

#2387 fix(resultPage): demo增加header
  src/packages/resultpage/demo.taro.tsx
Labels: size/XS

#2392 fix: 修复image宽高处理函数,调整swipe版本号
  packages/nutui-taro-demo-rn/scripts/taro/adapted.js
  src/config.json
  src/packages/image/image.taro.tsx
  src/packages/image/image.tsx
Labels: size/S

#2390 feat(table): table新增自定义行
  src/packages/table/demo.taro.tsx
  src/packages/table/demo.tsx
  src/packages/table/demos/h5/demo14.tsx
  src/packages/table/demos/taro/demo14.tsx
  src/packages/table/index.taro.ts
  src/packages/table/index.ts
  src/packages/table/table.taro.tsx
  src/packages/table/table.tsx
Labels: size/L

#2378 feat: 一键修改包名
  packages/nutui-codemod/README.md
  packages/nutui-codemod/bin/cli.js
  packages/nutui-codemod/bin/config/index.js
  packages/nutui-codemod/transforms/package-name-migration.js
  packages/nutui-codemod/transforms/utils/find-importDeclaration.js
Labels: size/M

#2396 fix(countdown): taro不区分四端实现方式
  scripts/rn/copy-file.js
  src/packages/countdown/countdown.taro.tsx
Labels: size/M

#2391 fix(fixednav): 可拖拽元素样式缺失
  src/packages/fixednav/fixednav.scss
Labels: size/XS
