Repository jdf2e/nutui-react, pull requests merged in 2024-10, with the labels that each got.

#2626 chore(demo): display 'bound dispatchSetState' message in demo8 of table demos
  src/packages/table/demos/h5/demo8.tsx
  src/packages/table/demos/taro/demo8.tsx
Labels: size/M

#2628 fix: usecallback to fix render too many times, button,animatingnumbers,avatar,audio; and fix avatargroup when length > maxsize
  src/packages/animatingnumbers/countup.taro.tsx
  src/packages/animatingnumbers/countup.tsx
  src/packages/animatingnumbers/demos/h5/demo2.tsx
  src/packages/animatingnumbers/demos/taro/demo2.tsx
  src/packages/audio/audio.taro.tsx
  src/packages/avatar/avatar.taro.tsx
  src/packages/avatar/avatar.tsx
  src/packages/button/button.taro.tsx
  src/packages/button/button.tsx
Labels: size/L

#2632 fix(navbar): safearea displays abnormal when safeAreaInsetTop has been set true
  src/packages/navbar/navbar.scss
  src/packages/navbar/navbar.taro.tsx
  src/packages/navbar/navbar.tsx
Labels: size/S

#2629 feat(popup): lockscroll 增加可选值 strict, 用于支持 iOS12
  src/packages/overlay/doc.en-US.md
  src/packages/overlay/doc.md
  src/packages/overlay/doc.zh-TW.md
  src/packages/overlay/overlay.tsx
  src/packages/popup/doc.en-US.md
  src/packages/popup/doc.md
  src/packages/popup/doc.zh-TW.md
  src/packages/popup/popup.tsx
Labels: size/M

#2635 fix(radio): lint fixed
  src/packages/radio/radio.taro.tsx
  src/packages/radio/radio.tsx
  src/packages/radiogroup/radiogroup.taro.tsx
  src/packages/radiogroup/radiogroup.tsx
Labels: size/L

#2637 fix(range): refactor & lint fixed
  src/packages/range/range.taro.tsx
  src/packages/range/range.tsx
Labels: size/L

#2636 fix: taro async warning in taro-h5 env
  packages/nutui-taro-demo/config/index.js
Labels: size/XS

#2633 fix(backtop & menu): lint, code simplification, deprecated pageYOffset removed
  src/packages/backtop/__test__/backtop.spec.tsx
  src/packages/backtop/backtop.taro.tsx
  src/packages/backtop/backtop.tsx
  src/packages/menu/__test__/__snapshots__/menu.spec.tsx.snap
  src/packages/menu/__test__/menu.spec.tsx
  src/packages/menu/menu.taro.tsx
  src/packages/menu/menu.tsx
  src/packages/menuitem/menuitem.taro.tsx
  src/packages/menuitem/menuitem.tsx
  src/utils/raf.ts
Labels: size/L

#2638 fix(range): usememo
  src/packages/range/__test__/__snapshots__/range.spec.tsx.snap
  src/packages/range/__test__/range.spec.tsx
  src/packages/range/demos/h5/demo5.tsx
  src/packages/range/range.scss
  src/packages/range/range.taro.tsx
  src/packages/range/range.tsx
Labels: size/L

#2639 fix(dialog): remove defaultprops
  src/packages/dialog/dialogwrap.tsx
Labels: size/XS

#2646 feat: 接入 harmony cpp 版本
  .gitignore
  .npmrc
  package.json
  packages/nutui-taro-demo/config/index.js
  packages/nutui-taro-demo/package.json
  scripts/harmony/clone-jdharmony.js
Labels: size/M

#2647 fix: sass warning in consle after updating
  src/sites/assets/styles/md-style.scss
  vite.config.ts
Labels: size/XS

#2648 fix: 引入错误
  src/packages/avatarcropper/avatarcropper.tsx
  src/packages/calendarcard/calendarcard.tsx
  src/packages/calendaritem/calendaritem.tsx
  src/packages/cascader/cascader.tsx
Labels: size/XS

#2644 feat(calendar): support deleteIcon props
  src/packages/calendar/calendar.taro.tsx
  src/packages/calendar/calendar.tsx
  src/packages/calendar/demos/h5/demo1.tsx
  src/packages/calendar/demos/taro/demo1.tsx
  src/packages/calendar/doc.en-US.md
  src/packages/calendar/doc.md
  src/packages/calendar/doc.taro.md
  src/packages/calendar/doc.zh-TW.md
Labels: size/S

#2645 feat(calendar): support renderBottomButton props
  src/packages/calendar/calendar.taro.tsx
  src/packages/calendar/calendar.tsx
  src/packages/calendar/doc.en-US.md
  src/packages/calendar/doc.md
  src/packages/calendar/doc.taro.md
  src/packages/calendar/doc.zh-TW.md
  src/packages/calendaritem/calendaritem.taro.tsx
  src/packages/calendaritem/calendaritem.tsx
Labels: size/M

#2631 fix(overlay): tour position offset in tour.taro
  src/packages/overlay/overlay.scss
Labels: size/XS

#2651 fix: @nutui/icons-react changed to @nutui/icons-react-taro
  src/packages/calendar/demos/taro/demo1.tsx
Labels: size/XS

#2656 fix: make taro h5 & miniprogram run successfully
  jdtaro-plugin-platform-jdrn-1.0.9.tgz
  packages/nutui-taro-demo/config/index.js
  packages/nutui-taro-demo/package.json
  packages/nutui-taro-demo/yarn.lock
  pnpm-lock.yaml
Labels: size/XL

#2642 添加inputNumber组件的全选中文本可配置
  src/packages/inputnumber/demo.taro.tsx
  src/packages/inputnumber/demo.tsx
  src/packages/inputnumber/demos/h5/demo10.tsx
  src/packages/inputnumber/demos/taro/demo10.tsx
  src/packages/inputnumber/doc.en-US.md
  src/packages/inputnumber/doc.md
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/inputnumber/inputnumber.tsx
Labels: size/XL

#2663 feat(progress): adaption in harmonycpp
  src/packages/progress/progress.taro.tsx
Labels: size/XS

#2668 chore: Auto UI test based on cypress
  cypress.config.ts
  cypress/component/Actionsheet.cy.jsx
  cypress/component/Button.cy.jsx
  cypress/component/Cell.cy.jsx
  cypress/e2e/index.cy.js
  cypress/e2e/taro/base.cy.js
  cypress/e2e/taro/dentry.cy.js
  cypress/e2e/taro/layout.cy.js
  cypress/e2e/taro/nav.cy.js
  cypress/fixtures/example.json
  cypress/screenshots/index.cy.js/layout components test -- Switch successfully passes (failed).png
  cypress/screenshots/taro/dentry.cy.js/layout components test -- Switch successfully passes (failed).png
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  cypress/support/e2e.ts
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#2671 feat: add plugin to replace icons
  packages/nutui-replace-icons/.gitignore
  packages/nutui-replace-icons/README.md
  packages/nutui-replace-icons/package.json
  packages/nutui-replace-icons/rollup.config.js
  packages/nutui-replace-icons/src/index.ts
  packages/nutui-replace-icons/src/replace-icons.ts
  packages/nutui-replace-icons/src/type.ts
  packages/nutui-replace-icons/test/__snapshots__/replace-case.test.ts.snap
  packages/nutui-replace-icons/test/replace-case.test.ts
  packages/nutui-replace-icons/tsconfig.json
  pnpm-lock.yaml
Labels: size/XXL

#2672 feat(replace icon): 替换jmapp icon
  .npmrc
  package.json
  packages/nutui-taro-demo/babel.config.js
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
Labels: size/XXL

#2674 feat: 新增jrkf样式配置
  package.json
  src/styles/font-jrkf/config.json
  src/styles/font-jrkf/demo.css
  src/styles/font-jrkf/demo_index.html
  src/styles/font-jrkf/iconfont.css
  src/styles/font-jrkf/iconfont.eot
  src/styles/font-jrkf/iconfont.js
  src/styles/font-jrkf/iconfont.json
  src/styles/font-jrkf/iconfont.svg
  src/styles/font-jrkf/iconfont.ttf
  src/styles/font-jrkf/iconfont.woff
  src/styles/font-jrkf/iconfont.woff2
  src/styles/theme-jrkf.scss
  src/styles/variables-jrkf.scss
Labels: size/XXL

#2664 fix: 优化 divider 垂直类型写法
  src/packages/divider/demos/h5/demo6.tsx
  src/packages/divider/demos/taro/demo6.tsx
  src/packages/divider/divider.scss
  src/packages/divider/doc.en-US.md
  src/packages/divider/doc.md
  src/packages/divider/doc.taro.md
  src/packages/divider/doc.zh-TW.md
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/M

#2677 fix(tag): 解决taro-h5图文demo不展示图标问题+harmonycpp适配问题修改
  src/packages/tag/demos/taro/demo4.tsx
  src/packages/tag/tag.harmony.css
  src/packages/tag/tag.scss
Labels: size/S

#2676 fix(empty): 修复 harmonycpp 部分未适配问题
  src/packages/empty/demos/taro/demo1.tsx
  src/packages/empty/demos/taro/demo3.tsx
  src/packages/empty/demos/taro/demo6.tsx
Labels: size/S

#2670 feat(Infiniteloading): 多端适配
  src/config.json
  src/packages/infiniteloading/demos/taro/demo1.tsx
  src/packages/infiniteloading/demos/taro/demo2.tsx
  src/packages/infiniteloading/demos/taro/demo3.tsx
  src/packages/infiniteloading/demos/taro/demo4.tsx
  src/packages/infiniteloading/infiniteloading.taro.tsx
  src/packages/infiniteloading/infiniteloading.tsx
Labels: size/L

#2666 fix(avatarcropper): 多语言支持
  src/packages/avatarcropper/__tests__/__snapshots__/avatarcropper.spec.tsx.snap
  src/packages/avatarcropper/avatarcropper.scss
  src/packages/avatarcropper/avatarcropper.tsx
Labels: size/XS

#2678 chore: ci
  .github/workflows/ci.yml
  pnpm-lock.yaml
Labels: size/XXL

#2680 fix: npm run build, lint, test failure in 3.0
  .eslintignore
  .prettierignore
  package.json
  src/packages/avatar/avatar.taro.tsx
  src/packages/avatarcropper/avatarcropper.taro.tsx
  src/packages/configprovider/types.ts
  src/packages/hoverbutton/__test__/__snapshots__/hoverbutton.spec.tsx.snap
  src/packages/infiniteloading/__tests__/__snapshots__/infiniteloading.spec.tsx.snap
  src/packages/popup/popup.rn.tsx
  src/packages/range/range.taro.tsx
  src/packages/range/range.tsx
  src/packages/uploader/__tests__/uploader.spec.tsx
  src/packages/uploader/uploader.taro.tsx
Labels: size/L

#2682 fix: build site failed in V3.0
  .github/workflows/ci.yml
  vite.config.site.ts
Labels: size/M

#2681 fix: 修改tag和badge字体样式变量
  src/packages/tag/tag.harmony.css
  src/styles/variables.scss
Labels: size/XS
