Repository jdf2e/nutui-react, pull requests merged in 2024-09, with the labels that each got.

#2567 feat(uploader): support beforeupload props in taro
  src/packages/uploader/demos/taro/demo1.tsx
  src/packages/uploader/doc.taro.md
  src/packages/uploader/uploader.taro.tsx
Labels: size/M

#2564 fix(sticky): rerender sticky when threshold change
  src/packages/sticky/sticky.taro.tsx
  src/packages/sticky/sticky.tsx
Labels: size/XS

#2572 fix(sticky): should rerender when zIndex changes
  pnpm-lock.yaml
  src/packages/sticky/sticky.taro.tsx
  src/packages/sticky/sticky.tsx
Labels: size/S

#2574 feat: demos for popup & dialog
  src/packages/popup/demos/h5/demo5.tsx
  src/packages/popup/demos/h5/demo6.tsx
  src/packages/popup/demos/h5/demo7.tsx
  src/packages/popup/demos/taro/demo5.tsx
  src/packages/popup/demos/taro/demo6.tsx
  src/packages/popup/demos/taro/demo7.tsx
  src/packages/popup/demos/taro/demo8.tsx
Labels: size/M

#2573 chore: remove deprecated usage of husky initialization
  .husky/commit-msg
Labels: size/XS

#2571 fix: remove icons defaultprops
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#2577 chore: merge branch 'next' into 'dev-harmony'
  .husky/commit-msg
  CHANGELOG.md
  package.json
  packages/nutui-codemod/package.json
  pnpm-lock.yaml
  scripts/generate-local-changelog.js
  src/packages/cell/cell.harmony.css
  src/packages/cell/cell.scss
  src/packages/cell/cell.taro.tsx
  src/packages/cell/cell.tsx
  src/packages/cell/demos/h5/demo1.tsx
  src/packages/cell/demos/taro/demo1.tsx
  src/packages/cell/doc.en-US.md
  src/packages/cell/doc.md
  src/packages/cell/doc.taro.md
  src/packages/cell/doc.zh-TW.md
  src/packages/input/input.taro.tsx
  src/packages/popup/demos/h5/demo5.tsx
  src/packages/popup/demos/h5/demo6.tsx
  src/packages/popup/demos/h5/demo7.tsx
  src/packages/popup/demos/taro/demo5.tsx
  src/packages/popup/demos/taro/demo6.tsx
  src/packages/popup/demos/taro/demo7.tsx
  src/packages/popup/demos/taro/demo8.tsx
  src/packages/pulltorefresh/demo.taro.tsx
  src/packages/pulltorefresh/demos/taro/demo4.tsx
  src/packages/pulltorefresh/pulltorefresh.taro.tsx
  src/packages/sticky/sticky.taro.tsx
  src/packages/sticky/sticky.tsx
  src/packages/tabs/tabs.taro.tsx
  src/packages/uploader/__tests__/uploader.spec.tsx
  src/packages/uploader/demos/h5/demo1.tsx
  src/packages/uploader/demos/taro/demo1.tsx
  src/packages/uploader/doc.taro.md
  src/packages/uploader/preview.tsx
  src/packages/uploader/uploader.taro.tsx
  src/packages/uploader/uploader.tsx
Labels: size/XL

#2579 refactor: resolve sass nested rules warning
  src/packages/elevator/elevator.scss
  src/packages/popover/popover.scss
  src/packages/tabs/tabs.scss
  src/packages/uploader/uploader.scss
  src/sites/doc/components/nav/nav.scss
  src/sites/mobile/App.scss
Labels: size/M

#2581 fix(props): add mergeProps utility to resolve all defaultProps warnings
  src/packages/actionsheet/actionsheet.taro.tsx
  src/packages/actionsheet/actionsheet.tsx
  src/packages/animatingnumbers/__tests__/animatingnumbers.spec.tsx
  src/packages/animatingnumbers/countup.taro.tsx
  src/packages/animatingnumbers/countup.tsx
  src/packages/dialog/dialog.taro.tsx
  src/packages/dialog/dialog.tsx
  src/packages/notify/notify.taro.tsx
  src/packages/toast/toast.taro.tsx
  src/utils/merge-props.ts
Labels: size/M

#2525 fix: findDomNode from transition
  src/packages/form/demos/h5/demo1.tsx
  src/packages/form/demos/taro/demo1.tsx
  src/packages/menuitem/menuitem.taro.tsx
  src/packages/menuitem/menuitem.tsx
  src/packages/notify/notify.taro.tsx
  src/packages/popup/popup.taro.tsx
Labels: size/S

#2585 fix: 子组件不存在demo.taro.tsx，应该跳过子组件
  scripts/rn/copy-file.js
Labels: size/XS

#2582 fix(datepicker): show zero on page
  src/packages/datepicker/datepicker.taro.tsx
  src/packages/datepicker/datepicker.tsx
Labels: size/XS

#2587 fix: 移除不必要的 fragment 元素
  src/packages/audio/audio.taro.tsx
  src/packages/avatarcropper/avatarcropper.taro.tsx
  src/packages/avatarcropper/avatarcropper.tsx
  src/packages/calendaritem/calendaritem.taro.tsx
  src/packages/calendaritem/calendaritem.tsx
  src/packages/ellipsis/ellipsis.taro.tsx
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/inputnumber/inputnumber.tsx
  src/packages/layout/layout.taro.tsx
  src/packages/layout/layout.tsx
  src/packages/overlay/overlay.taro.tsx
  src/packages/overlay/overlay.tsx
  src/packages/pagination/pagination.taro.tsx
  src/packages/pagination/pagination.tsx
  src/packages/popup/popup.taro.tsx
  src/packages/popup/popup.tsx
  src/packages/tour/tour.taro.tsx
Labels: size/L

#2591 fix(cascader): 受控状态下 value 变化时同步组件选中状态
  src/packages/cascader/cascader.taro.tsx
  src/packages/cascader/cascader.tsx
Labels: size/XS

#2596 fix: progress typescript
  src/packages/progress/progress.taro.tsx
Labels: size/XS

#2598 fix: 处理ts类型异常
  src/packages/backtop/backtop.taro.tsx
  src/packages/cell/cell.tsx
  src/packages/elevator/elevator.taro.tsx
  src/packages/fixednav/fixednav.taro.tsx
Labels: size/S

#2599 feat: 自动更新taro版本的脚本, 适用于beta版本
  package.json
  packages/nutui-taro-demo/package.json
  packages/nutui-taro-demo/scripts/taro/upgradeTaro
Labels: size/M

#2605 fix: 类型构建错误
  vite.config.build.taro.ts
  vite.config.build.ts
Labels: size/XS

#2597 fix: i18n
  src/locales/base.ts
  src/locales/en-US.ts
  src/locales/id-ID.ts
  src/locales/tr-TR.ts
  src/locales/zh-CN.ts
  src/locales/zh-TW.ts
  src/locales/zh-UG.ts
  src/packages/address/address.taro.tsx
  src/packages/address/address.tsx
  src/packages/address/customRender.taro.tsx
  src/packages/address/customRender.tsx
  src/packages/address/types.ts
  src/packages/avatar/avatar.tsx
  src/packages/avatarcropper/__tests__/__snapshots__/avatarcropper.spec.tsx.snap
  src/packages/avatarcropper/avatarcropper.taro.tsx
  src/packages/avatarcropper/avatarcropper.tsx
  src/packages/cascader/cascader.taro.tsx
  src/packages/cascader/cascader.tsx
  src/packages/collapseitem/collapseitem.taro.tsx
  src/packages/collapseitem/collapseitem.tsx
  src/packages/configprovider/configprovider.taro.tsx
  src/packages/configprovider/configprovider.tsx
  src/packages/countdown/countdown.taro.tsx
  src/packages/countdown/countdown.tsx
  src/packages/elevator/elevator.taro.tsx
  src/packages/elevator/elevator.tsx
  src/packages/ellipsis/ellipsis.taro.tsx
  src/packages/ellipsis/ellipsis.tsx
  src/packages/empty/empty.taro.tsx
  src/packages/empty/empty.tsx
  src/packages/griditem/griditem.taro.tsx
  src/packages/griditem/griditem.tsx
  src/packages/image/image.taro.tsx
  src/packages/image/image.tsx
  src/packages/imagepreview/__test__/imagepreview.spec.tsx
  src/packages/notify/notify.taro.tsx
  src/packages/notify/notify.tsx
  src/packages/pagination/pagination.taro.tsx
  src/packages/pagination/pagination.tsx
  src/packages/picker/picker.tsx
  src/packages/searchbar/searchbar.taro.tsx
  src/packages/searchbar/searchbar.tsx
  src/packages/signature/signature.taro.tsx
  src/packages/swiper/__tests__/swiper.spec.tsx
  src/packages/timeselect/timeselect.taro.tsx
  src/packages/timeselect/timeselect.tsx
  src/packages/uploader/file-item.ts
  src/packages/uploader/uploader.taro.tsx
  src/packages/uploader/uploader.tsx
  src/sites/assets/styles/variables.scss
  src/sites/doc/components/header/header.scss
Labels: size/L

#2603 chore: replace local prettier plugin with npm package
  .prettierrc
  package.json
  packages/nutui-prettier-plugin/index.js
  packages/nutui-prettier-plugin/package.json
  plugins/table-format.mjs
  pnpm-lock.yaml
Labels: size/L

#2607 chore: update dependency linguist-languages to be included within package
  package.json
  pnpm-lock.yaml
  src/packages/rate/doc.md
Labels: size/S

#2614 feat(popup): RN
  gulpfile.js
  package.json
  packages/nutui-taro-demo/config/index.js
  packages/nutui-taro-demo/scripts/taro/generate-nutui-taro.js
  pnpm-lock.yaml
  scripts/rn/copy-file.js
  scripts/taro/generate-nutui-taro.js
  src/config.json
  src/packages/popup/demo.taro.tsx
  src/packages/popup/demos/taro/demo1.tsx
  src/packages/popup/demos/taro/demo3.tsx
  src/packages/popup/demos/taro/demo7.tsx
  src/packages/popup/index.rn.ts
  src/packages/popup/popup.harmony.css
  src/packages/popup/popup.rn.tsx
  src/packages/popup/popup.scss
Labels: size/XXL

#2618 feat(Uploader): add support for deleteIcon prop customization
  src/packages/uploader/demo.taro.tsx
  src/packages/uploader/demo.tsx
  src/packages/uploader/demos/h5/demo14.tsx
  src/packages/uploader/demos/taro/demo14.tsx
  src/packages/uploader/doc.en-US.md
  src/packages/uploader/doc.md
  src/packages/uploader/doc.taro.md
  src/packages/uploader/doc.zh-TW.md
  src/packages/uploader/preview.taro.tsx
  src/packages/uploader/preview.tsx
  src/packages/uploader/uploader.taro.tsx
  src/packages/uploader/uploader.tsx
Labels: size/L

#2612 fix: 修改jd小程序高版本弹幕不滚动问题
  src/packages/barrage/barrage.taro.tsx
  src/packages/barrage/demos/taro/demo1.tsx
Labels: size/M
