Repository jdf2e/nutui-react, pull requests merged in 2025-08, with the labels that each got.

#3318 feat: add plugin for bizui using nutui
  packages/nutui-inject-ui-styles/.gitignore
  packages/nutui-inject-ui-styles/README.md
  packages/nutui-inject-ui-styles/dist/index.js
  packages/nutui-inject-ui-styles/dist/index.js.map
  packages/nutui-inject-ui-styles/package.json
  packages/nutui-inject-ui-styles/rollup.config.js
  packages/nutui-inject-ui-styles/src/babel-component-style.ts
  packages/nutui-inject-ui-styles/src/index.ts
  packages/nutui-inject-ui-styles/src/type.ts
  packages/nutui-inject-ui-styles/tsconfig.json
  packages/nutui-inject-ui-styles/types/index.d.ts
Labels: size/L, 3.x, action:review

#3321 feat: 调整button圆角、dialog内边间距
  src/styles/variables-jmapp.scss
Labels: size/XS, 2.x, action:review

#3319 feat(notify): 支持promise调用notice
  src/packages/notify/notify.tsx
Labels: size/XS, 3.x, action:review

#3325 fix: 为兼容 cpp 版本做的暂时性的牺牲改动
  package.json
  src/packages/dialog/dialog.taro.tsx
  src/packages/overlay/overlay.taro.tsx
  src/packages/popup/popup.taro.tsx
Labels: size/L, action:review

#3328 feat(price): 支持自定义颜色&数据原样输出
  src/packages/price/demo.taro.tsx
  src/packages/price/demo.tsx
  src/packages/price/demos/h5/demo10.tsx
  src/packages/price/demos/h5/demo11.tsx
  src/packages/price/demos/taro/demo10.tsx
  src/packages/price/demos/taro/demo11.tsx
  src/packages/price/doc.en-US.md
  src/packages/price/doc.md
  src/packages/price/doc.taro.md
  src/packages/price/doc.zh-TW.md
  src/packages/price/price.taro.tsx
  src/packages/price/price.tsx
  src/types/spec/price/base.ts
Labels: size/L, 3.x, action:review

#3330 chore: 升级icon库
  package.json
  pnpm-lock.yaml
  src/packages/address/__test__/__snapshots__/address.spec.tsx.snap
  src/packages/audio/__test__/__snapshots__/audio.spec.tsx.snap
  src/packages/backtop/__test__/__snapshots__/backtop.spec.tsx.snap
  src/packages/badge/__test__/__snapshots__/badge.spec.tsx.snap
  src/packages/cascader/__tests__/__snapshots__/cascader.spec.tsx.snap
  src/packages/checkbox/__test__/__snapshots__/checkbox.spec.tsx.snap
  src/packages/collapse/__test__/__snapshots__/collapse.spec.tsx.snap
  src/packages/grid/__test__/__snapshots__/grid.spec.tsx.snap
  src/packages/hoverbutton/__test__/__snapshots__/hoverbutton.spec.tsx.snap
  src/packages/image/__test__/__snapshots__/image.spec.tsx.snap
  src/packages/menu/__test__/__snapshots__/menu.spec.tsx.snap
  src/packages/noticebar/__test__/__snapshots__/noticebar.spec.tsx.snap
  src/packages/numberkeyboard/_test_/__snapshots__/index.spec.tsx.snap
  src/packages/rate/__test__/__snapshots__/rate.spec.tsx.snap
  src/packages/resultpage/__test__/__snapshots__/resultpage.spec.tsx.snap
  src/packages/tabbar/__tests__/__snapshots__/tabbar.spec.tsx.snap
  src/packages/timeselect/__test__/__snapshots__/timeselect.spec.tsx.snap
Labels: size/L, 3.x, action:review
