Repository jdf2e/nutui-react, pull requests merged in 2025-03, with the labels that each got.

#3037 fix: textarea 鸿蒙适配
  src/packages/textarea/demo.taro.tsx
  src/packages/textarea/demos/h5/demo1.tsx
  src/packages/textarea/demos/h5/demo2.tsx
  src/packages/textarea/demos/h5/demo3.tsx
  src/packages/textarea/demos/h5/demo4.tsx
  src/packages/textarea/demos/h5/demo5.tsx
  src/packages/textarea/demos/h5/demo6.tsx
  src/packages/textarea/demos/h5/demo7.tsx
  src/packages/textarea/demos/h5/demo8.tsx
  src/packages/textarea/demos/h5/demo9.tsx
  src/packages/textarea/demos/taro/demo1.tsx
  src/packages/textarea/demos/taro/demo2.tsx
  src/packages/textarea/demos/taro/demo3.tsx
  src/packages/textarea/demos/taro/demo4.tsx
  src/packages/textarea/demos/taro/demo5.tsx
  src/packages/textarea/demos/taro/demo6.tsx
  src/packages/textarea/demos/taro/demo7.tsx
  src/packages/textarea/demos/taro/demo8.tsx
  src/packages/textarea/demos/taro/demo9.tsx
  src/packages/textarea/textarea.taro.tsx
Labels: size/L, 3.x, action:review

#3041 fix(collapse): 去掉 demo 顶部留白
  src/packages/collapse/demo.taro.tsx
Labels: size/XS, 3.x, action:review

#3040 fix(watermark): 小程序图片高度未撑开
  src/packages/watermark/demos/taro/demo2.tsx
Labels: size/XS, action:review

#3043 fix(Tabs): 合并2.x版本
  src/packages/tabs/tabs.taro.tsx
Labels: size/S, 3.x, action:review

#3044 fix(Tabbar): inactive color for harmony
  src/packages/tabbaritem/tabbaritem.scss
Labels: size/XS, 3.x, action:review

#3042 feat:增加一个以组为单位的编译逻辑
  scripts/harmony/update-taro-entry.js
Labels: size/M, 3.x, action:review

#3045 fix: change index
  src/config.json
Labels: size/L, 3.x, action:review

#3046 fix: config v15 调整
  src/config.json
Labels: size/L, 3.x, action:review

#3026 feat: datepickerview
  src/config.json
  src/packages/datepicker/datepicker.taro.tsx
  src/packages/datepicker/datepicker.tsx
  src/packages/datepickerview/__test__/__snapshots__/datepickerview.spec.tsx.snap
  src/packages/datepickerview/__test__/datepickerview.spec.tsx
  src/packages/datepickerview/datepickerview.scss
  src/packages/datepickerview/datepickerview.taro.tsx
  src/packages/datepickerview/datepickerview.tsx
  src/packages/datepickerview/demo.taro.tsx
  src/packages/datepickerview/demo.tsx
  src/packages/datepickerview/demos/h5/demo1.tsx
  src/packages/datepickerview/demos/h5/demo2.tsx
  src/packages/datepickerview/demos/taro/demo1.tsx
  src/packages/datepickerview/demos/taro/demo2.tsx
  src/packages/datepickerview/doc.en-US.md
  src/packages/datepickerview/doc.md
  src/packages/datepickerview/doc.taro.md
  src/packages/datepickerview/doc.zh-TW.md
  src/packages/datepickerview/index.taro.ts
  src/packages/datepickerview/index.ts
  src/packages/datepickerview/types.ts
Labels: size/XXL, 3.x, action:review

#3017 feat(shortpassword): harmony
  src/config.json
  src/packages/shortpassword/shortpassword.scss
  src/packages/shortpassword/shortpassword.taro.tsx
  src/packages/shortpassword/shortpassword.tsx
Labels: size/S, 3.x, action:review

#3048 fix(navbar): tabpane 展示控制只限于 navbar
  src/packages/navbar/demo.scss
  src/packages/navbar/demo.taro.tsx
  src/packages/navbar/demo.tsx
Labels: size/XS, 3.x, action:review

#3047 fix: H5 小程序走查中遇到的问题修复
  src/packages/avatarcropper/demo.taro.tsx
  src/packages/menu/demo.taro.tsx
  src/packages/sidebar/demo.taro.tsx
  src/packages/watermark/demos/taro/demo1.tsx
Labels: size/S, 3.x, action:review

#3052 fix: 调整dd展示
  migrate-from-v2.md
  src/config.json
  src/packages/sidenavbar/__test__/sidenavbar.spec.tsx
  src/packages/sidenavbar/context.ts
  src/packages/sidenavbar/demo.taro.tsx
  src/packages/sidenavbar/demo.tsx
  src/packages/sidenavbar/demos/h5/demo1.tsx
  src/packages/sidenavbar/demos/h5/demo2.tsx
  src/packages/sidenavbar/demos/taro/demo1.tsx
  src/packages/sidenavbar/demos/taro/demo2.tsx
  src/packages/sidenavbar/doc.en-US.md
  src/packages/sidenavbar/doc.md
  src/packages/sidenavbar/doc.taro.md
  src/packages/sidenavbar/doc.zh-TW.md
  src/packages/sidenavbar/index.taro.ts
  src/packages/sidenavbar/index.ts
  src/packages/sidenavbar/sidenavbar.scss
  src/packages/sidenavbar/sidenavbar.taro.tsx
  src/packages/sidenavbar/sidenavbar.tsx
  src/packages/sidenavbar/utils.ts
  src/packages/sidenavbaritem/__test__/__snapshots__/sidenavbaritem.spec.tsx.snap
  src/packages/sidenavbaritem/__test__/sidenavbaritem.spec.tsx
  src/packages/sidenavbaritem/index.taro.ts
  src/packages/sidenavbaritem/index.ts
  src/packages/sidenavbaritem/sidenavbaritem.scss
  src/packages/sidenavbaritem/sidenavbaritem.taro.tsx
  src/packages/sidenavbaritem/sidenavbaritem.tsx
  src/packages/subsidenavbar/__test__/__snapshots__/subsidenavbar.spec.tsx.snap
  src/packages/subsidenavbar/__test__/subsidenavbar.spec.tsx
  src/packages/subsidenavbar/index.taro.ts
  src/packages/subsidenavbar/index.ts
  src/packages/subsidenavbar/subsidenavbar.scss
  src/packages/subsidenavbar/subsidenavbar.taro.tsx
  src/packages/subsidenavbar/subsidenavbar.tsx
  src/styles/variables-jmapp.scss
  src/styles/variables-jrkf.scss
  src/styles/variables.scss
Labels: size/XXL, 3.x, action:review

#3051 fix: demos full css
  packages/nutui-taro-demo/src/app.scss
  src/packages/drag/demo.taro.tsx
  src/packages/menu/demo.taro.tsx
  src/packages/tabs/demo.taro.tsx
Labels: size/S, action:review

#3049 fix(navbar): 居左展示时，副标题居左
  src/packages/navbar/demos/h5/demo2.tsx
  src/packages/navbar/demos/taro/demo2.tsx
Labels: size/S, 3.x, action:review

#3053 fix: hoverbutton h5 border is lost
  src/packages/hoverbutton/demo.taro.tsx
  src/packages/hoverbutton/demo.tsx
  src/packages/hoverbutton/demos/h5/demo1.tsx
  src/packages/hoverbutton/demos/h5/demo2.tsx
  src/packages/hoverbutton/demos/h5/demo3.tsx
  src/packages/hoverbutton/demos/h5/demo4.tsx
  src/packages/hoverbutton/demos/h5/demo6.tsx
  src/packages/hoverbutton/demos/taro/demo1.tsx
  src/packages/hoverbutton/demos/taro/demo2.tsx
  src/packages/hoverbutton/demos/taro/demo3.tsx
  src/packages/hoverbutton/demos/taro/demo4.tsx
  src/packages/hoverbutton/demos/taro/demo6.tsx
Labels: size/L, 3.x, action:review

#3050 fix(input): 显示设置 placeholder 字体颜色
  src/packages/input/input.scss
  src/packages/input/input.taro.tsx
Labels: size/S, 3.x, action:review

#3054 fix(Drag): 解决taro不能滑动问题
  packages/nutui-taro-demo/src/app.scss
  src/packages/drag/demos/taro/demo2.tsx
  src/packages/drag/demos/taro/demo3.tsx
  src/packages/drag/demos/taro/demo4.tsx
  src/packages/drag/drag.scss
  src/packages/drag/drag.taro.tsx
Labels: size/M, 3.x, action:review

#3058 fix(docs): 快速上手文件
  src/sites/sites-react/doc/docs/react/start-react.en-US.md
  src/sites/sites-react/doc/docs/react/start-react.md
  src/sites/sites-react/doc/docs/taro/intro-react.en-US.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/start-react.en-US.md
  src/sites/sites-react/doc/docs/taro/start-react.md
Labels: size/XXL, 3.x, action:review

#3056 docs: fix some mistakes in the documentation
  src/packages/popover/doc.taro.md
  src/packages/uploader/doc.md
  src/packages/uploader/doc.taro.md
  src/packages/uploader/doc.zh-TW.md
Labels: size/XS, 3.x, action:review

#3057 fix: taro default import error
  src/utils/get-system-info.ts
  src/utils/platform-taro.ts
Labels: size/S, 3.x, action:review

#3059 fix(input): style 属性设置为 CSSProperties 类型的值
  src/packages/input/input.taro.tsx
Labels: size/XS, 3.x, action:review

#3055 chore: remove version sign in site
  src/sites/sites-react/doc/components/nav/nav.tsx
Labels: size/S, 3.x, action:review

#3062 fix(cell): 优化自定义右侧区域demo展示
  src/packages/cell/demos/h5/demo4.tsx
  src/packages/cell/demos/taro/demo4.tsx
Labels: size/XS, 3.x, action:review

#3061 refactor(fixednav): 优化组件徽标的实现方式,解决原有不对称问题
  src/packages/fixednav/fixednav.scss
  src/packages/fixednav/fixednav.taro.tsx
  src/packages/fixednav/fixednav.tsx
Labels: size/M, 3.x, action:review

#3063 docs(site): 删除无用的代码，更新视觉版本号
  src/sites/config/baseConfig.ts
  src/sites/config/index.ts
Labels: size/L, 3.x, action:review

#3060 fix(signature): 解决taro h5不能绘制问题
  src/packages/signature/signature.taro.tsx
Labels: size/XS, 3.x, action:review

#3064 fix: 解决按需引入picker和datepicker没有样式问题
  src/packages/datepickerview/datepickerview.scss
  src/packages/picker/picker.scss
Labels: size/XS, 3.x, action:review

#3039 feat(swipe): harmony
  src/config.json
  src/hooks/use-client-rect.ts
  src/packages/swipe/demos/taro/demo9.tsx
  src/packages/swipe/swipe.scss
  src/packages/swipe/swipe.taro.tsx
  src/utils/get-rect-by-taro.ts
Labels: size/M, 3.x, action:review

#3065 chore: add jdtaro. True means that will repeat
  src/config.json
Labels: size/S, 3.x, action:review

#3067 fix: sync v15 sign
  src/config.json
Labels: size/XS, 3.x, action:review

#3068 fix(fixednav): 引入 badge 样式
  src/packages/fixednav/fixednav.scss
Labels: size/XS, 3.x, action:review

#3071 docs: update start react md
  src/sites/sites-react/doc/docs/react/start-react.en-US.md
  src/sites/sites-react/doc/docs/react/start-react.md
Labels: size/M, 3.x, action:review

#3075 fix(Popup): popup demos 调优
  src/packages/popup/demos/h5/demo4.tsx
  src/packages/popup/demos/taro/demo4.tsx
Labels: size/M, 3.x, action:review

#3074 fix(CalendarCard): 修复日历卡片在jd下的demo展示
  src/packages/calendarcard/demo.taro.tsx
Labels: size/M, 3.x, action:review

#3073 chore: 类型文件中增加 jsdoc
  package.json
  scripts/build-comments-to-dts.mjs
  scripts/build-taro.mjs
  src/config.json
  src/packages/datepickerview/doc.en-US.md
  src/packages/datepickerview/doc.md
  src/packages/datepickerview/doc.taro.md
  src/packages/datepickerview/doc.zh-TW.md
  src/packages/rate/doc.taro.md
  src/types/index.ts
  src/types/spec/picker/base.ts
  src/types/spec/picker/h5.ts
  src/types/spec/picker/taro.ts
  src/types/spec/pickerview/base.ts
  src/types/spec/pickerview/h5.ts
  src/types/spec/pickerview/taro.ts
  src/types/spec/steps/base.ts
  src/types/spec/steps/h5.ts
  src/types/spec/steps/taro.ts
Labels: size/L, 3.x, action:review

#2988 refactor(pagination): data abstraction via hooks
  src/hooks/use-pagination.ts
  src/packages/pagination/pagination.taro.tsx
  src/packages/pagination/pagination.tsx
Labels: size/L, 3.x, action:review

#3006 fix(inputnumber): 增加 beforeChange，优化异步逻辑
  src/packages/inputnumber/__tests__/inputnumber.spec.tsx
  src/packages/inputnumber/demos/h5/demo8.tsx
  src/packages/inputnumber/demos/taro/demo8.tsx
  src/packages/inputnumber/doc.en-US.md
  src/packages/inputnumber/doc.md
  src/packages/inputnumber/doc.taro.md
  src/packages/inputnumber/doc.zh-TW.md
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/inputnumber/inputnumber.tsx
  src/sites/sites-react/doc/docs/react/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
  src/types/spec/inputnumber/base.ts
Labels: size/XL, 3.x, action:review

#3083 fix: correct usages about toast props
  src/packages/icon/demo.taro.tsx
  src/packages/icon/demos/taro/demo6.tsx
  src/packages/icon/demos/taro/demo7.tsx
  src/packages/infiniteloading/demos/taro/demo2.tsx
  src/packages/inputnumber/demos/taro/demo3.tsx
  src/packages/inputnumber/demos/taro/demo8.tsx
  src/packages/inputnumber/demos/taro/demo9.tsx
  src/packages/numberkeyboard/demos/taro/demo6.tsx
  src/packages/progress/demos/taro/demo7.tsx
  src/packages/pulltorefresh/demos/taro/demo4.tsx
  src/packages/searchbar/demos/taro/demo3.tsx
  src/packages/searchbar/demos/taro/demo4.tsx
  src/packages/switch/demos/taro/demo2.tsx
  src/packages/switch/demos/taro/demo6.tsx
  src/packages/table/demo.taro.tsx
  src/packages/toast/demos/taro/demo2.tsx
  src/packages/toast/doc.taro.md
Labels: size/M, action:review

#3085 chore: remove migrate ci-workflow
  .github/workflows/sync-h5.yml
  .github/workflows/sync-migrate.yml
  .github/workflows/sync-taro.yml
  scripts/copy-docs-h5-or-taro.js
  scripts/copy-migrate-from-v1.js
  scripts/copy-migrate-from-v2.js
Labels: size/L, 3.x, action:review

#3084 fix(sidebar): disabled props and content display abnormal in harmony
  src/packages/sidebar/demos/taro/demo1.tsx
  src/packages/sidebar/demos/taro/demo4.tsx
  src/packages/sidebar/demos/taro/demo5.tsx
  src/packages/sidebar/demos/taro/demo6.tsx
  src/packages/sidebar/sidebar.taro.tsx
Labels: size/S, 3.x, action:review

#3090 fix: 开发环境中导出 types 下的类型
  scripts/generate-nutui.js
  scripts/taro/generate-nutui-taro.js
Labels: size/XS, 3.x, action:review

#3089 fix: correct import paths
  packages/nutui-taro-demo/config/index.js
  src/packages/configprovider/demos/h5/demo4.tsx
  src/packages/configprovider/demos/taro/demo4.tsx
  src/sites/sites-react/doc/docs/react/international-react.en-US.md
  src/sites/sites-react/doc/docs/react/international-react.md
  src/sites/sites-react/doc/docs/react/start-react.en-US.md
  src/sites/sites-react/doc/docs/react/start-react.md
  src/sites/sites-react/doc/docs/taro/international-react.en-US.md
  src/sites/sites-react/doc/docs/taro/international-react.md
  src/sites/sites-react/doc/docs/taro/start-react.en-US.md
  src/sites/sites-react/doc/docs/taro/start-react.md
  tsconfig.json
  vite.config.demo.ts
  vite.config.mts
Labels: size/M, 3.x, action:review

#3093 fix(swipe): 调整 demo 中字体为 12
  src/packages/swipe/demos/taro/demo1.tsx
  src/packages/swipe/demos/taro/demo2.tsx
  src/packages/swipe/demos/taro/demo3.tsx
  src/packages/swipe/demos/taro/demo4.tsx
  src/packages/swipe/demos/taro/demo5.tsx
  src/packages/swipe/demos/taro/demo6.tsx
  src/packages/swipe/demos/taro/demo7.tsx
  src/packages/swipe/demos/taro/demo8.tsx
  src/packages/swipe/demos/taro/demo9.tsx
Labels: size/M, 3.x, action:review

#3099 test(Calendar): fixed
  src/packages/calendar/__tests__/__snapshots__/calendar.spec.tsx.snap
  src/packages/calendar/__tests__/calendar.spec.tsx
Labels: size/XS, 2.x

#3097 feat(pickerview): 选中值增加class类名用于自定义样式
  packages/nutui-taro-demo/config/index.js
  src/packages/pickerview/__test__/__snapshots__/pickerview.spec.tsx.snap
  src/packages/pickerview/pickerroller.taro.tsx
  src/packages/pickerview/pickerroller.tsx
Labels: size/M, 3.x, action:review

#3096 fix: adjust site style about listyle
  src/sites/sites-react/doc/components/contribution/contribution.tsx
Labels: size/M, 3.x, action:review

#3098 docs: 补充web 设置 px 转 rem时的文档
  src/sites/sites-react/doc/docs/react/start-react.en-US.md
  src/sites/sites-react/doc/docs/react/start-react.md
  src/sites/sites-react/doc/docs/taro/start-react.en-US.md
  src/sites/sites-react/doc/docs/taro/start-react.md
Labels: size/M, 3.x, action:review

#3101 fix(SearchBar): demo 样式变量修订
  src/packages/searchbar/demos/h5/demo3.tsx
  src/packages/searchbar/demos/taro/demo3.tsx
Labels: size/XS, 3.x, action:review

#3103 fix(resultpage): 引入button样式
  src/packages/empty/empty.scss
  src/packages/resultpage/resultpage.scss
Labels: size/XS, 3.x, action:review

#3100 fix(SearchBar): demos fixed
  src/packages/searchbar/demos/h5/demo3.tsx
  src/packages/searchbar/demos/taro/demo3.tsx
Labels: size/XS, 2.x, action:review

#3105 feat: 优化了一下文档样式,更紧凑清晰
  src/sites/assets/styles/highlight.scss
  src/sites/assets/styles/md-style.scss
  src/sites/sites-react/doc-taro/App.scss
  src/sites/sites-react/doc/App.scss
  src/sites/sites-react/doc/components/contribution/contribution.scss
  src/sites/sites-react/doc/components/contribution/contribution.tsx
  src/sites/sites-react/doc/components/demoblock/codeblock.tsx
  src/sites/sites-react/doc/components/nav/nav.scss
  src/sites/sites-react/doc/components/nav/nav.tsx
  src/sites/theme/App.scss
  src/sites/theme/components/nav/nav.scss
Labels: size/L, 3.x, action:review

#3107 fix(inputnumber): value 大于 max 图标应处于禁用态
  src/packages/inputnumber/inputnumber.taro.tsx
  src/packages/inputnumber/inputnumber.tsx
Labels: size/S, action:review

#3104 test(uploader): optimize async test cases stability
  src/packages/uploader/__tests__/uploader.spec.tsx
Labels: size/M, 3.x, action:review

#2939 fix(ImagePreview): 优化代码，fix 因为popup最大宽度导致的问题
  src/packages/imagepreview/__test__/imagepreview.spec.tsx
  src/packages/imagepreview/imagepreview.scss
  src/packages/imagepreview/imagepreview.taro.tsx
  src/packages/imagepreview/imagepreview.tsx
  src/packages/notify/Notification.tsx
  src/packages/toast/Notification.tsx
  src/sites/sites-react/doc-taro/App.scss
  src/sites/sites-react/doc/App.scss
Labels: size/XL, 3.x, action:review

#3102 feat(pickerview): 小程序支持自定义列表行高
  src/packages/datepickerview/__test__/__snapshots__/datepickerview.spec.tsx.snap
  src/packages/picker/demos/h5/demo8.tsx
  src/packages/picker/demos/taro/demo8.tsx
  src/packages/pickerview/__test__/__snapshots__/pickerview.spec.tsx.snap
  src/packages/pickerview/pickerroller.taro.tsx
  src/packages/pickerview/pickerroller.tsx
  src/packages/pickerview/pickerview.scss
Labels: size/XL, 3.x, action:review

#3111 fix(badge): 解决中文偏上问题
  src/packages/badge/badge.scss
  src/styles/theme-dark.scss
  src/styles/theme-default.scss
  src/styles/variables-jmapp.scss
  src/styles/variables-jrkf.scss
  src/styles/variables.scss
Labels: size/S, 3.x, action:review

#3106 feat(demoblock): code block scrolling behavior， CodesandBox function and copyCode styles
  package.json
  pnpm-lock.yaml
  src/sites/sites-react/doc/components/demoblock/codesandbox/index.css
  src/sites/sites-react/doc/components/demoblock/codesandbox/index.html
  src/sites/sites-react/doc/components/demoblock/codesandbox/package.json
  src/sites/sites-react/doc/components/demoblock/demoblock.scss
  src/sites/sites-react/doc/components/demoblock/demoblock.tsx
Labels: size/L, 3.x, action:review

#3119 fix: update pkgjson title
  src/sites/sites-react/doc/components/demoblock/codesandbox/package.json
Labels: size/XS, 3.x, action:review

#3123 fix(badge): 修正css变量定义
  src/styles/variables.scss
Labels: size/XS, 3.x, action:review

#3121 chore: support ui review
  packages/nutui-taro-demo/config/prod.js
Labels: size/S, 3.x, action:review

#3124 fix: build jmapp
  scripts/generate-themes.js
Labels: size/XS, 2.x

#3118 refactor(badge): 支持禁用模式
  src/packages/badge/badge.scss
  src/packages/badge/badge.taro.tsx
  src/packages/badge/badge.tsx
  src/packages/badge/demo.taro.tsx
  src/packages/badge/demo.tsx
  src/packages/badge/demos/h5/demo9.tsx
  src/packages/badge/demos/taro/demo9.tsx
  src/packages/badge/doc.en-US.md
  src/packages/badge/doc.md
  src/packages/badge/doc.taro.md
  src/packages/badge/doc.zh-TW.md
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
  src/styles/variables-jmapp.scss
  src/styles/variables-jrkf.scss
  src/styles/variables.scss
  src/types/spec/badge/base.ts
Labels: size/L, 3.x, action:review

#3117 fix(overlay): 扩大点击范围
  src/packages/overlay/demos/taro/demo1.tsx
  src/packages/overlay/demos/taro/demo2.tsx
  src/packages/overlay/demos/taro/demo3.tsx
  src/packages/overlay/demos/taro/demo4.tsx
  src/packages/overlay/demos/taro/demo5.tsx
  src/packages/overlay/demos/taro/demo6.tsx
Labels: size/S, 3.x, action:review

#3080 feat(lottie): 支持京东小程序
  package.json
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
  scripts/harmony/update-taro-entry.js
  scripts/taro/generate-taro-route.js
  src/packages/lottie/doc.taro.md
  src/packages/lottie/index.taro.ts
  src/packages/lottie/index.ts
  src/packages/lottie/lottie.tsx
  src/packages/lottie/lottiemp.taro.tsx
  src/packages/lottie/lottieweb.taro.tsx
Labels: size/S, 3.x, action:review

#3082 feat(notify): v15
  packages/nutui-taro-demo/src/app.scss
  src/packages/configprovider/types.ts
  src/packages/drag/demo.taro.tsx
  src/packages/notify/Notification.tsx
  src/packages/notify/__test__/notify.spec.tsx
  src/packages/notify/demo.taro.tsx
  src/packages/notify/demo.tsx
  src/packages/notify/demos/h5/demo1.tsx
  src/packages/notify/demos/h5/demo2.tsx
  src/packages/notify/demos/h5/demo3.tsx
  src/packages/notify/demos/h5/demo4.tsx
  src/packages/notify/demos/taro/demo1.tsx
  src/packages/notify/demos/taro/demo2.tsx
  src/packages/notify/demos/taro/demo3.tsx
  src/packages/notify/demos/taro/demo4.tsx
  src/packages/notify/doc.en-US.md
  src/packages/notify/doc.md
  src/packages/notify/doc.taro.md
  src/packages/notify/doc.zh-TW.md
  src/packages/notify/notify.scss
  src/packages/notify/notify.taro.tsx
  src/packages/notify/notify.tsx
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
  src/styles/variables-jmapp.scss
  src/styles/variables-jrkf.scss
  src/styles/variables.scss
  src/types/spec/notify/base.ts
Labels: size/XL, 3.x, action:review

#3126 fix: doc css
  src/sites/sites-react/doc/components/nav/nav.scss
Labels: size/XS, 3.x, action:review

#3125 fix(searchbar): 支付宝小程序设置 enableInPageRenderInput 后无法触发 onChange
  src/packages/searchbar/searchbar.scss
  src/packages/searchbar/searchbar.taro.tsx
Labels: size/M, 2.x, action:review

#3130 fix(searchbar): 支付宝小程序设置 enableInPageRenderInput 后无法触发 onChange
  src/packages/searchbar/searchbar.taro.tsx
  src/types/spec/searchbar/taro.ts
Labels: size/M, 3.x, action:review

#3122 feat(switch): 异步切换支持受控loading态
  src/packages/switch/__test__/switch.spec.tsx
  src/packages/switch/demos/h5/demo2.tsx
  src/packages/switch/demos/taro/demo2.tsx
  src/packages/switch/demos/taro/demo6.tsx
  src/packages/switch/doc.en-US.md
  src/packages/switch/doc.md
  src/packages/switch/doc.taro.md
  src/packages/switch/doc.zh-TW.md
  src/packages/switch/switch.scss
  src/packages/switch/switch.taro.tsx
  src/packages/switch/switch.tsx
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
  src/types/spec/switch/base.ts
  src/types/spec/switch/h5.ts
  src/types/spec/switch/taro.ts
Labels: size/L, 3.x, action:review

#3110 feat(Tabbar): v15 样式适配；增加 icon/value/title 的function类型，支持根据active状态渲染不同数据；增加 onDoubleClick 事件
  src/packages/tabbar/__tests__/__snapshots__/tabbar.spec.tsx.snap
  src/packages/tabbar/__tests__/tabbar.spec.tsx
  src/packages/tabbar/demo.taro.tsx
  src/packages/tabbar/demo.tsx
  src/packages/tabbar/demos/h5/demo1.tsx
  src/packages/tabbar/demos/h5/demo2.tsx
  src/packages/tabbar/demos/h5/demo3.tsx
  src/packages/tabbar/demos/h5/demo4.tsx
  src/packages/tabbar/demos/h5/demo5.tsx
  src/packages/tabbar/demos/h5/demo6.tsx
  src/packages/tabbar/demos/h5/demo7.tsx
  src/packages/tabbar/demos/h5/demo8.tsx
  src/packages/tabbar/demos/h5/demo9.tsx
  src/packages/tabbar/demos/taro/demo1.tsx
  src/packages/tabbar/demos/taro/demo2.tsx
  src/packages/tabbar/demos/taro/demo3.tsx
  src/packages/tabbar/demos/taro/demo4.tsx
  src/packages/tabbar/demos/taro/demo5.tsx
  src/packages/tabbar/demos/taro/demo6.tsx
  src/packages/tabbar/demos/taro/demo7.tsx
  src/packages/tabbar/demos/taro/demo8.tsx
  src/packages/tabbar/demos/taro/demo9.tsx
  src/packages/tabbar/doc.en-US.md
  src/packages/tabbar/doc.md
  src/packages/tabbar/doc.taro.md
  src/packages/tabbar/doc.zh-TW.md
  src/packages/tabbar/tabbar.scss
  src/packages/tabbar/tabbar.taro.tsx
  src/packages/tabbar/tabbar.tsx
  src/packages/tabbaritem/tabbaritem.scss
  src/packages/tabbaritem/tabbaritem.taro.tsx
  src/packages/tabbaritem/tabbaritem.tsx
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
  src/styles/variables.scss
  src/types/spec/tabbar/base.ts
Labels: size/XXL, 3.x, action:review

#3086 feat(skeleton): v15
  src/config.json
  src/packages/skeleton/__test__/skeleton.spec.tsx
  src/packages/skeleton/demo.scss
  src/packages/skeleton/demo.taro.tsx
  src/packages/skeleton/demo.tsx
  src/packages/skeleton/demos/h5/demo1.tsx
  src/packages/skeleton/demos/h5/demo2.tsx
  src/packages/skeleton/demos/h5/demo3.tsx
  src/packages/skeleton/demos/h5/demo4.tsx
  src/packages/skeleton/demos/h5/demo5.tsx
  src/packages/skeleton/demos/taro/demo1.tsx
  src/packages/skeleton/demos/taro/demo2.tsx
  src/packages/skeleton/demos/taro/demo3.tsx
  src/packages/skeleton/demos/taro/demo4.tsx
  src/packages/skeleton/demos/taro/demo5.tsx
  src/packages/skeleton/doc.en-US.md
  src/packages/skeleton/doc.md
  src/packages/skeleton/doc.taro.md
  src/packages/skeleton/doc.zh-TW.md
  src/packages/skeleton/skeleton.scss
  src/packages/skeleton/skeleton.taro.tsx
  src/packages/skeleton/skeleton.tsx
  src/sites/sites-react/doc/docs/react/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
  src/styles/variables-jmapp.scss
  src/styles/variables-jrkf.scss
  src/styles/variables.scss
  src/types/spec/skeleton/base.ts
Labels: size/XL, 3.x, action:review

#3133 feat: 构建主题的css文件
  scripts/generate-themes.js
Labels: size/S, 2.x

#3134 fix: tabbar config json
  src/config.json
Labels: size/XS, 3.x, action:review

#3137 chore: 修复正式环境的 publicPath
  packages/nutui-taro-demo/config/prod.js
Labels: size/XS, 3.x, action:review

#3132 fix(switch): 简化props使用
  src/packages/switch/switch.taro.tsx
  src/packages/switch/switch.tsx
Labels: size/XS, 3.x, action:review

#3138 fix: 主题文件添加到 sideEffects 中
  package.json
Labels: size/XS, 2.x
