Repository jdf2e/nutui-react, pull requests merged in 2025-01, with the labels that each got.

#2831 feat(performance): getRectByTaro 方法在小程序内增加缓存以提升性能
  src/utils/get-rect-by-taro.ts
  src/utils/lru.ts
Labels: size/M, 2.x

#2916 chore(pre-commit): add check-lock-file script
  .husky/pre-commit
  scripts/check-lock.js
Labels: size/S, 2.x

#2914 fix: 调整日历日期
  src/packages/calendar/demos/h5/demo10.tsx
  src/packages/calendar/demos/h5/demo11.tsx
  src/packages/calendar/demos/h5/demo2.tsx
  src/packages/calendar/demos/h5/demo3.tsx
  src/packages/calendar/demos/h5/demo4.tsx
  src/packages/calendar/demos/h5/demo5.tsx
  src/packages/calendar/demos/h5/demo6.tsx
  src/packages/calendar/demos/h5/demo7.tsx
  src/packages/calendar/demos/h5/demo8.tsx
  src/packages/calendar/demos/h5/demo9.tsx
  src/packages/calendar/demos/taro/demo10.tsx
  src/packages/calendar/demos/taro/demo11.tsx
  src/packages/calendar/demos/taro/demo2.tsx
  src/packages/calendar/demos/taro/demo3.tsx
  src/packages/calendar/demos/taro/demo4.tsx
  src/packages/calendar/demos/taro/demo5.tsx
  src/packages/calendar/demos/taro/demo6.tsx
  src/packages/calendar/demos/taro/demo7.tsx
  src/packages/calendar/demos/taro/demo8.tsx
  src/packages/calendar/demos/taro/demo9.tsx
Labels: size/L, 2.x

#2910 fix(textarea): 字数限制文本遮挡输入框的内容
  src/packages/textarea/doc.en-US.md
  src/packages/textarea/doc.md
  src/packages/textarea/doc.taro.md
  src/packages/textarea/doc.zh-TW.md
  src/packages/textarea/textarea.scss
  src/styles/variables.scss
Labels: size/S, 2.x

#2913 fix(swiper): 修复duration不生效
  src/packages/swiper/swiper.taro.tsx
Labels: size/XS, 2.x

#2912 fix(tabs): 修复意外地出现了滚动条
  src/packages/tabs/tabs.taro.tsx
Labels: size/XS, 2.x

#2915 chore(pre-commit): add check-lock-file script
  .husky/pre-commit
  pnpm-lock.yaml
  scripts/check-lock.js
Labels: size/S, 3.x

#2925 refactor: replace lodash.isEqual with react-fast-compare
  package.json
  pnpm-lock.yaml
  src/packages/configprovider/configprovider.taro.tsx
  src/packages/configprovider/configprovider.tsx
  src/utils/use-custom-event.ts
Labels: wonderful, size/XXL, 3.x

#2926 refactor: site running faster when it's development
  index.html
  src/config.json
  src/packages/button/button.taro.tsx
  src/packages/button/button.tsx
  src/sites/assets/locale/index.ts
  src/sites/assets/locale/taro/index.ts
  src/sites/assets/styles/md-style.scss
  src/sites/assets/styles/variables.scss
  src/sites/assets/util/index.ts
  src/sites/doc/App.scss
  src/sites/doc/App.tsx
  src/sites/doc/components/demo-preview/demo-preview.scss
  src/sites/doc/components/demo-preview/demo-preview.tsx
  src/sites/doc/components/demoblock/codeblock.tsx
  src/sites/doc/components/header/header.scss
  src/sites/doc/components/header/header.tsx
  src/sites/doc/components/issue/issue.scss
  src/sites/doc/components/issue/issue.tsx
  src/sites/doc/components/nav/nav.tsx
  src/sites/mobile/App.tsx
  theme.html
Labels: size/XL, 3.x

#2927 fix(form): 分割线未生效
  src/packages/cellgroup/cellgroup.scss
  src/packages/formitem/formitem.scss
Labels: size/S, 2.x

#2931 fix(form): item label 未对齐
  src/packages/formitem/formitem.scss
Labels: size/XS, 2.x

#2940 refactor: new components are generated automatically
  package.json
  pnpm-lock.yaml
  scripts/create-component-mode.js
  scripts/demo.js
Labels: wonderful, size/XL, size/XXL, 3.x

#2937 fix: imageSize=0无效
  src/packages/empty/empty.taro.tsx
  src/packages/empty/empty.tsx
Labels: size/XS, 2.x

#2911 fix: 修订主题变量
  src/packages/configprovider/types.ts
  src/styles/variables.scss
Labels: size/L, 3.x

#2943 docs: popup 增加 taro ios 兼容 faq
  src/packages/popup/doc.taro.md
Labels: size/XS, 2.x

#2944 refactor: popup 优化代码
  src/packages/popup/doc.taro.md
  src/packages/popup/popup.taro.tsx
  src/packages/popup/popup.tsx
Labels: size/L, 3.x

#2946 fix: eslint fixes
  scripts/demo.js
Labels: size/M, size/S, 3.x, 2.x

#2953 feat(form): resetFields 增加 namepath 参数，用于重置指定的字段
  src/packages/form/__tests__/form.spec.tsx
  src/packages/form/doc.en-US.md
  src/packages/form/doc.md
  src/packages/form/doc.taro.md
  src/packages/form/doc.zh-TW.md
  src/packages/form/useform.taro.ts
  src/packages/form/useform.ts
Labels: size/L, 2.x

#2951 fix: 受控模式下返回的selectedOptions进行校验处理
  src/packages/datepicker/datepicker.taro.tsx
  src/packages/datepicker/datepicker.tsx
Labels: size/S, 2.x

#2948 fix: tabs 代码简化\修订纵向样式
  src/packages/tabpane/tabpane.taro.tsx
  src/packages/tabpane/tabpane.tsx
  src/packages/tabs/demos/h5/demo1.tsx
  src/packages/tabs/demos/h5/demo10.tsx
  src/packages/tabs/demos/h5/demo11.tsx
  src/packages/tabs/demos/h5/demo12.tsx
  src/packages/tabs/demos/h5/demo13.tsx
  src/packages/tabs/demos/h5/demo14.tsx
  src/packages/tabs/demos/h5/demo2.tsx
  src/packages/tabs/demos/h5/demo20.tsx
  src/packages/tabs/demos/h5/demo21.tsx
  src/packages/tabs/demos/h5/demo22.tsx
  src/packages/tabs/demos/h5/demo3.tsx
  src/packages/tabs/demos/h5/demo4.tsx
  src/packages/tabs/demos/h5/demo5.tsx
  src/packages/tabs/demos/h5/demo6.tsx
  src/packages/tabs/demos/h5/demo7.tsx
  src/packages/tabs/demos/h5/demo8.tsx
  src/packages/tabs/demos/h5/demo9.tsx
  src/packages/tabs/demos/taro/demo1.tsx
  src/packages/tabs/demos/taro/demo10.tsx
  src/packages/tabs/demos/taro/demo11.tsx
  src/packages/tabs/demos/taro/demo12.tsx
  src/packages/tabs/demos/taro/demo13.tsx
  src/packages/tabs/demos/taro/demo14.tsx
  src/packages/tabs/demos/taro/demo2.tsx
  src/packages/tabs/demos/taro/demo20.tsx
  src/packages/tabs/demos/taro/demo21.tsx
  src/packages/tabs/demos/taro/demo22.tsx
  src/packages/tabs/demos/taro/demo3.tsx
  src/packages/tabs/demos/taro/demo4.tsx
  src/packages/tabs/demos/taro/demo5.tsx
  src/packages/tabs/demos/taro/demo6.tsx
  src/packages/tabs/demos/taro/demo7.tsx
  src/packages/tabs/demos/taro/demo8.tsx
  src/packages/tabs/demos/taro/demo9.tsx
  src/packages/tabs/tabs.scss
  src/packages/tabs/tabs.taro.tsx
  src/packages/tabs/tabs.tsx
Labels: size/L, 3.x

#2949 fix: tabs 代码简化,调整部分样式
  src/packages/address/__test__/__snapshots__/address.spec.tsx.snap
  src/packages/cascader/__tests__/__snapshots__/cascader.spec.tsx.snap
  src/packages/tabpane/tabpane.taro.tsx
  src/packages/tabpane/tabpane.tsx
  src/packages/tabs/__test__/tabs.spec.tsx
  src/packages/tabs/demos/h5/demo1.tsx
  src/packages/tabs/demos/h5/demo10.tsx
  src/packages/tabs/demos/h5/demo11.tsx
  src/packages/tabs/demos/h5/demo12.tsx
  src/packages/tabs/demos/h5/demo13.tsx
  src/packages/tabs/demos/h5/demo14.tsx
  src/packages/tabs/demos/h5/demo16.tsx
  src/packages/tabs/demos/h5/demo2.tsx
  src/packages/tabs/demos/h5/demo20.tsx
  src/packages/tabs/demos/h5/demo21.tsx
  src/packages/tabs/demos/h5/demo22.tsx
  src/packages/tabs/demos/h5/demo3.tsx
  src/packages/tabs/demos/h5/demo4.tsx
  src/packages/tabs/demos/h5/demo5.tsx
  src/packages/tabs/demos/h5/demo6.tsx
  src/packages/tabs/demos/h5/demo7.tsx
  src/packages/tabs/demos/h5/demo8.tsx
  src/packages/tabs/demos/h5/demo9.tsx
  src/packages/tabs/demos/taro/demo1.tsx
  src/packages/tabs/demos/taro/demo10.tsx
  src/packages/tabs/demos/taro/demo11.tsx
  src/packages/tabs/demos/taro/demo12.tsx
  src/packages/tabs/demos/taro/demo13.tsx
  src/packages/tabs/demos/taro/demo14.tsx
  src/packages/tabs/demos/taro/demo16.tsx
  src/packages/tabs/demos/taro/demo2.tsx
  src/packages/tabs/demos/taro/demo20.tsx
  src/packages/tabs/demos/taro/demo21.tsx
  src/packages/tabs/demos/taro/demo22.tsx
  src/packages/tabs/demos/taro/demo3.tsx
  src/packages/tabs/demos/taro/demo4.tsx
  src/packages/tabs/demos/taro/demo5.tsx
  src/packages/tabs/demos/taro/demo6.tsx
  src/packages/tabs/demos/taro/demo7.tsx
  src/packages/tabs/demos/taro/demo8.tsx
  src/packages/tabs/demos/taro/demo9.tsx
  src/packages/tabs/tabs.scss
  src/packages/tabs/tabs.taro.tsx
  src/packages/tabs/tabs.tsx
Labels: size/XL, 2.x

#2957 docs(toast): 修复文档中的函数式例子
  src/packages/toast/demo.taro.tsx
  src/packages/toast/demos/taro/demo2.tsx
Labels: size/XS, 2.x

#2958 docs(toast): 修复文档中的函数式例子
  src/packages/toast/demo.taro.tsx
  src/packages/toast/demos/taro/demo2.tsx
Labels: size/XS, 3.x

#2960 docs(configprovider): 优化文档中的主题配置描述
  src/packages/configprovider/doc.en-US.md
  src/packages/configprovider/doc.md
  src/packages/configprovider/doc.taro.md
  src/packages/configprovider/doc.zh-TW.md
Labels: size/XS, 3.x

#2959 docs(configprovider): 优化文档中的主题配置描述
  src/packages/configprovider/doc.en-US.md
  src/packages/configprovider/doc.md
  src/packages/configprovider/doc.taro.md
  src/packages/configprovider/doc.zh-TW.md
Labels: size/XS, 2.x
