Repository jdf2e/nutui-react, pull requests merged in 2025-04, with the labels that each got.

#3141 fix: contribution img failed to display
  src/sites/sites-react/doc/docs/react/contributing-react.md
  src/sites/sites-react/doc/docs/react/intro-react.md
  src/sites/sites-react/doc/docs/taro/contributing-react.md
  src/sites/sites-react/doc/docs/taro/intro-react.md
Labels: size/XS, 3.x, action:review

#3139 feat(collapse): 适配鸿蒙
  src/config.json
  src/packages/collapse/__test__/__snapshots__/collapse.spec.tsx.snap
  src/packages/collapse/__test__/collapse.spec.tsx
  src/packages/collapseitem/collapseitem.scss
  src/packages/collapseitem/collapseitem.taro.tsx
  src/packages/collapseitem/collapseitem.tsx
Labels: size/L, 3.x, action:review

#3127 feat: 修订 jm 变量名
  package.json
  src/styles/theme-jmapp.scss
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/L, 3.x, action:review

#3129 fix: popover 无法关闭的问题,删除无用代码和无用的样式变量
  packages/nutui-taro-demo/src/app.ts
  src/config.json
  src/hooks/use-taro-rect.ts
  src/packages/picker/picker.taro.tsx
  src/packages/popover/__tests__/popover.spec.tsx
  src/packages/popover/demo.scss
  src/packages/popover/demo.taro.tsx
  src/packages/popover/demo.tsx
  src/packages/popover/demos/h5/demo1.tsx
  src/packages/popover/demos/h5/demo2.tsx
  src/packages/popover/demos/h5/demo3.tsx
  src/packages/popover/demos/h5/demo4-1.tsx
  src/packages/popover/demos/h5/demo4.tsx
  src/packages/popover/demos/h5/demo5.tsx
  src/packages/popover/demos/h5/demo6.tsx
  src/packages/popover/demos/h5/demo7.tsx
  src/packages/popover/demos/h5/demo8.tsx
  src/packages/popover/demos/taro/demo1.tsx
  src/packages/popover/demos/taro/demo2.tsx
  src/packages/popover/demos/taro/demo3.tsx
  src/packages/popover/demos/taro/demo4-1.tsx
  src/packages/popover/demos/taro/demo4.tsx
  src/packages/popover/demos/taro/demo5.tsx
  src/packages/popover/demos/taro/demo6.tsx
  src/packages/popover/doc.en-US.md
  src/packages/popover/doc.md
  src/packages/popover/doc.taro.md
  src/packages/popover/doc.zh-TW.md
  src/packages/popover/popover.scss
  src/packages/popover/popover.taro.tsx
  src/packages/popover/popover.tsx
  src/packages/popup/popup.scss
  src/packages/tour/__test__/tour.spec.tsx
  src/packages/tour/demo.taro.tsx
  src/packages/tour/demos/h5/demo1.tsx
  src/packages/tour/demos/h5/demo2.tsx
  src/packages/tour/demos/h5/demo3.tsx
  src/packages/tour/demos/h5/demo4.tsx
  src/packages/tour/demos/h5/demo5.tsx
  src/packages/tour/demos/taro/demo1.tsx
  src/packages/tour/demos/taro/demo2.tsx
  src/packages/tour/demos/taro/demo3.tsx
  src/packages/tour/demos/taro/demo4.tsx
  src/packages/tour/demos/taro/demo5.tsx
  src/packages/tour/tour.taro.tsx
  src/sites/sites-react/doc/docs/react/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
  src/styles/variables-jmapp.scss
  src/styles/variables-jrkf.scss
  src/styles/variables.scss
  src/types/spec/popover/base.ts
  src/utils/get-rect-by-taro.ts
  src/utils/lru.ts
Labels: size/XXL, 3.x, action:review

#3144 fix(Popup): 调整最小高度设定为 26%
  src/packages/popup/popup.scss
Labels: size/XS, 3.x, action:review

#3142 fix(button): 样式变量无法生效问题修复
  src/packages/button/button.scss
  src/packages/button/demo.tsx
  src/packages/button/demos/h5/demo1.tsx
  src/packages/button/demos/h5/demo2.tsx
  src/packages/button/demos/h5/demo3.tsx
  src/packages/button/demos/h5/demo4.tsx
  src/packages/button/demos/h5/demo5.tsx
  src/packages/button/demos/h5/demo6.tsx
  src/packages/button/demos/h5/demo7.tsx
  src/packages/button/demos/h5/demo8.tsx
  src/packages/button/demos/h5/demo9.tsx
  src/packages/button/demos/taro/demo8.tsx
  src/packages/button/doc.en-US.md
  src/packages/button/doc.md
  src/packages/button/doc.taro.md
  src/packages/button/doc.zh-TW.md
Labels: size/L, 3.x, action:review

#3145 fix(dialog)：修复函数式调用时 hidecancel 不生效问题
  src/packages/dialog/confirm.tsx
Labels: size/S, 3.x, action:review

#3147 refactor(dialog): 抽离types到标准spec下，去掉web h5 wrap层。
  src/packages/dialog/confirm.tsx
  src/packages/dialog/content.taro.tsx
  src/packages/dialog/content.tsx
  src/packages/dialog/dialog.taro.tsx
  src/packages/dialog/dialog.tsx
  src/packages/dialog/dialogwrap.tsx
  src/packages/dialog/index.taro.ts
  src/packages/dialog/index.ts
  src/packages/dialog/types.taro.ts
  src/packages/dialog/types.ts
  src/types/spec/dialog/base.ts
  src/types/spec/dialog/h5.ts
  src/types/spec/dialog/taro.ts
Labels: size/XL, 3.x, action:review

#3148 fix(tabs): 兼容16
  src/packages/tabpane/tabpane.taro.tsx
  src/packages/tabpane/tabpane.tsx
Labels: size/XS, 2.x, action:review

#3150 fix(tabs): 兼容16的处理
  src/packages/tabpane/tabpane.taro.tsx
  src/packages/tabpane/tabpane.tsx
  src/packages/tabs/__test__/tabs.spec.tsx
Labels: size/S, 3.x, action:review

#3156 chore: 增加 useHtmlComponents 模式
  package.json
  packages/nutui-taro-demo/config/index.js
Labels: size/XS, 3.x, action:review

#3154 fix(skeleton): 废弃inline 导致的警告问题修复
  src/packages/skeleton/skeleton.taro.tsx
  src/packages/skeleton/skeleton.tsx
Labels: size/XS, 3.x, action:review

#3158 fix(docs): 修复 markdown 无法正确编译注释
  src/sites/sites-react/doc/docs/react/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
Labels: size/XS, 3.x, action:review

#3159 fix: codesandbox params error
  src/sites/sites-react/doc/components/demoblock/codesandbox/package.json
Labels: size/XS, 3.x, action:review

#3167 fix(cascader): 选中后 tab 应展示 text 字段的值
  src/packages/cascader/cascader.taro.tsx
  src/packages/cascader/cascader.tsx
  src/packages/cascader/demos/h5/demo1.tsx
  src/packages/cascader/demos/h5/demo2.tsx
  src/packages/cascader/demos/taro/demo1.tsx
  src/packages/cascader/demos/taro/demo2.tsx
Labels: size/M, 3.x, action:review

#3172 feat(dialog): 添加变量处理
  src/packages/dialog/dialog.scss
  src/packages/dialog/doc.en-US.md
  src/packages/dialog/doc.md
  src/packages/dialog/doc.taro.md
  src/packages/dialog/doc.zh-TW.md
  src/styles/variables-jmapp.scss
  src/styles/variables.scss
Labels: size/S, 3.x, action:review

#3165 fix(image): 组件内部的style处理覆盖传入的className
  src/packages/image/image.scss
  src/packages/image/image.taro.tsx
Labels: size/M, 3.x, action:merge

#3146 fix: jmapp demo build
  package.json
  packages/nutui-taro-demo/config/prod.js
  packages/nutui-taro-demo/package.json
  src/sites/sites-react/doc/docs/react/official-theme-react.md
  src/sites/sites-react/doc/docs/taro/official-theme-react.md
  vite.config.demo.ts
Labels: size/S, 3.x, action:review

#3163 docs: 补充快速上手和主题中的配置项的解释
  src/sites/sites-react/doc/docs/react/official-theme-react.en-US.md
  src/sites/sites-react/doc/docs/react/official-theme-react.md
  src/sites/sites-react/doc/docs/react/start-react.en-US.md
  src/sites/sites-react/doc/docs/react/start-react.md
  src/sites/sites-react/doc/docs/react/theme-react.en-US.md
  src/sites/sites-react/doc/docs/react/theme-react.md
  src/sites/sites-react/doc/docs/taro/official-theme-react.en-US.md
  src/sites/sites-react/doc/docs/taro/official-theme-react.md
  src/sites/sites-react/doc/docs/taro/start-react.en-US.md
  src/sites/sites-react/doc/docs/taro/start-react.md
  src/sites/sites-react/doc/docs/taro/theme-react.en-US.md
  src/sites/sites-react/doc/docs/taro/theme-react.md
Labels: size/M, 3.x, action:review

#3160 feat(v15): swipe 增加 v15 的 demo
  src/packages/swipe/demos/h5/demo2.tsx
  src/packages/swipe/demos/taro/demo2.tsx
  src/packages/swipe/swipe.taro.tsx
Labels: size/M, 3.x, action:review

#3169 fix(sidebar): scroll animation not working with sidebarDuration prop
  src/packages/sidebar/sidebar.taro.tsx
Labels: size/S, 3.x, action:review

#3178 fix(image): update image props tsType
  src/packages/image/doc.en-US.md
  src/packages/image/doc.md
  src/packages/image/doc.taro.md
  src/packages/image/doc.zh-TW.md
  src/types/spec/image/base.ts
Labels: size/S, 3.x, action:review

#3187 docs(audio): 修订audio taro 端文档,不再支持taro多端
  src/packages/audio/demo.taro.tsx
  src/packages/audio/doc.taro.md
Labels: size/M, 3.x, action:review

#3188 feat(button): 兼容 taro components
  src/packages/button/button.taro.tsx
Labels: size/XS, 3.x, action:review

#3186 chore: update taro version
  package.json
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
Labels: size/M, 3.x, action:review

#3184 refactor(loading): 移除内置的 lottie，可通过 icon 属性加载 lottie
  src/packages/loading/__test__/loading.spec.tsx
  src/packages/loading/demos/h5/demo1.tsx
  src/packages/loading/demos/taro/demo1.tsx
  src/packages/loading/loading.scss
  src/packages/loading/loading.taro.tsx
  src/packages/loading/loading.tsx
  src/types/spec/loading/base.ts
Labels: size/L, 3.x, action:review

#3181 feat(input): 增加 taro components 属性的支持
  src/packages/input/input.taro.tsx
  src/types/spec/input/taro.ts
Labels: size/S, 3.x, action:review

#3182 feat(form): 增加 taro components 属性的支持,抽象类型
  src/packages/form/form.taro.tsx
  src/packages/form/form.tsx
  src/packages/form/index.taro.ts
  src/packages/form/index.ts
  src/packages/form/types.ts
  src/packages/form/useform.taro.ts
  src/packages/form/useform.ts
  src/packages/formitem/formitem.taro.tsx
  src/packages/formitem/formitem.tsx
  src/packages/formitem/index.taro.ts
  src/packages/formitem/index.ts
  src/packages/formitem/types.ts
  src/types/base/atoms.ts
  src/types/spec/form/base.ts
  src/types/spec/form/h5.ts
  src/types/spec/form/taro.ts
Labels: size/L, 3.x, action:review

#3189 refactor: 打包组件不同主题的 css 文件
  package.json
  packages/nutui-templates/create-app-demo/craco.config.js
  packages/nutui-templates/create-app-demo/package.json
  packages/nutui-templates/create-app-demo/src/App.js
  packages/nutui-templates/vite-demo/package.json
  packages/nutui-templates/vite-demo/src/App.tsx
  packages/nutui-templates/vite-demo/vite.config.ts
  scripts/build-taro.mjs
  scripts/build.mjs
  src/sites/sites-react/doc/docs/react/official-theme-react.en-US.md
  src/sites/sites-react/doc/docs/react/official-theme-react.md
  src/sites/sites-react/doc/docs/react/start-react.en-US.md
  src/sites/sites-react/doc/docs/react/start-react.md
  src/sites/sites-react/doc/docs/taro/official-theme-react.en-US.md
  src/sites/sites-react/doc/docs/taro/official-theme-react.md
  src/sites/sites-react/doc/docs/taro/start-react.en-US.md
  src/sites/sites-react/doc/docs/taro/start-react.md
  src/styles/variables-jrkf.scss
Labels: size/XXL, 3.x, action:review

#3193 docs: jmapp 不判断环境，直接打开
  src/sites/mobile/main.tsx
  src/sites/sites-react/doc/docs/react/official-theme-react.en-US.md
  src/sites/sites-react/doc/docs/react/official-theme-react.md
Labels: size/XS, 3.x, action:review

#3192 fix: 兼容选中值为0的情况
  src/packages/pickerview/pickerroller.taro.tsx
  src/packages/pickerview/pickerview.taro.tsx
  src/packages/pickerview/pickerview.tsx
Labels: size/S, 3.x, action:review

#3197 fix: 删掉无用console
  src/utils/get-rect.ts
  src/utils/supports-passive.ts
Labels: size/XS, 3.x, action:review

#3200 chore: 更新壳工程导入分支
  scripts/harmony/clone-jdharmony.js
Labels: size/XS, 3.x, action:review

#3198 feat(uploader): add listUploadRender prop for custom list mode upload…
  src/packages/uploader/doc.en-US.md
  src/packages/uploader/doc.md
  src/packages/uploader/doc.taro.md
  src/packages/uploader/doc.zh-TW.md
  src/packages/uploader/uploader.taro.tsx
  src/packages/uploader/uploader.tsx
  src/types/spec/uploader/base.ts
Labels: size/L, 3.x, action:review

#3183 fix(tabs): 修复滚动计算与定位逻辑相关问题
  src/packages/tabs/demos/h5/demo16.tsx
  src/packages/tabs/demos/h5/demo17.tsx
  src/packages/tabs/demos/taro/demo16.tsx
  src/packages/tabs/demos/taro/demo17.tsx
  src/packages/tabs/tabs.taro.tsx
Labels: size/M, 3.x, action:review

#3203 perf: optimize the performance issues caused by style injection
  src/sites/mobile/main.tsx
  vite.config.demo.ts
  vite.config.mts
  vite.config.site.mts
  vite.config.site.taro.mts
Labels: size/S, 3.x, action:review

#3204 docs: 升级文档补充
  src/sites/sites-react/doc/docs/react/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
Labels: size/S, 3.x, action:review

#3206 fix(popup): 规范化写动效,兼容处理
  src/packages/popup/popup.scss
Labels: size/S, 2.x

#3205 fix(picker): 解决透传popup的round属性不生效问题
  src/packages/picker/picker.scss
Labels: size/XS, 3.x, action:review
