Repository jdf2e/nutui-react, pull requests merged in 2025-02, with the labels that each got.

#2965 fix: corepack manager use pnpm failed
  .github/workflows/ci.yml
  .github/workflows/cypress.yml
  .github/workflows/realease-tag.yml
  .github/workflows/sync-h5.yml
  .github/workflows/sync-migrate.yml
  .github/workflows/sync-taro.yml
  pnpm-lock.yaml
Labels: size/XXL, 3.x

#2968 perf: 优化 animate
  src/packages/animate/animate.scss
  src/packages/animate/animate.taro.tsx
  src/packages/animate/animate.tsx
Labels: size/L, 3.x

#2967 perf: 优化渲染节点
  src/packages/badge/badge.taro.tsx
  src/packages/badge/badge.tsx
  src/packages/tabbar/__tests__/__snapshots__/tabbar.spec.tsx.snap
  src/packages/tabbaritem/tabbaritem.scss
  src/packages/tabbaritem/tabbaritem.taro.tsx
  src/packages/tabbaritem/tabbaritem.tsx
Labels: size/L, 3.x

#2970 fix(ci): corepack manager use pnpm failed
  .github/workflows/ci.yml
  .github/workflows/realease-tag.yml
  .github/workflows/sync-h5.yml
  .github/workflows/sync-migrate.yml
  .github/workflows/sync-taro.yml
Labels: size/S, 2.x

#2971 fix: calender footer button css
  src/config.json
  src/packages/calendar/calendar.scss
  src/packages/calendar/demos/taro/demo1.tsx
  src/packages/calendaritem/calendaritem.taro.tsx
Labels: size/M, 3.x

#2972 feat: add PR review labels automation
  .github/workflows/pr-labels.yml
Labels: size/M, 3.x

#2980 fix: resolve 'Resource not accessible by integration'
  .github/workflows/pr-labels.yml
Labels: size/XS, 3.x, action:review

#2975 refactor: use compatible systemInfo util API
  src/packages/avatarcropper/avatarcropper.taro.tsx
  src/packages/drag/demos/taro/demo4.tsx
  src/packages/drag/drag.taro.tsx
  src/packages/lottie/mp.taro.tsx
  src/packages/menuitem/menuitem.taro.tsx
  src/packages/pulltorefresh/pulltorefresh.taro.tsx
  src/packages/sticky/sticky.taro.tsx
  src/packages/virtuallist/virtuallist.taro.tsx
  src/utils/get-system-info.ts
Labels: size/M, 3.x, action:review

#2979 fix(textarea): placeholder 可以设置为空字符串
  src/packages/textarea/__test__/__snapshots__/textarea.spec.tsx.snap
  src/packages/textarea/textarea.taro.tsx
  src/packages/textarea/textarea.tsx
Labels: size/L, 3.x, action:review

#2982 chore: release package via ci
  .github/workflows/release-beta.yml
  .github/workflows/release.yml
  .gitignore
  package.json
  scripts/build-comments-to-dts.mjs
  scripts/build-taro.mjs
  scripts/build.mjs
  scripts/postpublish.js
  scripts/prepublish.js
Labels: size/L, 3.x, action:review

#2984 fix: adjust pr-label strategy
  .github/workflows/pr-labels.yml
Labels: size/L, 3.x, action:review

#2983 refactor: calendar
  src/packages/calendar/__tests__/__snapshots__/calendar.spec.tsx.snap
  src/packages/calendar/__tests__/calendar.spec.tsx
  src/packages/calendar/calendar.scss
  src/packages/calendar/calendar.taro.tsx
  src/packages/calendar/calendar.tsx
  src/packages/calendar/demos/h5/demo10.tsx
  src/packages/calendar/demos/h5/demo3.tsx
  src/packages/calendar/demos/h5/demo4.tsx
  src/packages/calendar/demos/taro/demo1.tsx
  src/packages/calendar/demos/taro/demo10.tsx
  src/packages/calendar/utils.tsx
  src/packages/calendarcard/utils.ts
  src/packages/calendaritem/calendaritem.taro.tsx
  src/packages/calendaritem/calendaritem.tsx
  src/utils/date.ts
Labels: size/XXL, 2.x, action:merge

#2966 fix: autocomplete failed
  src/packages/image/image.tsx
  src/packages/popover/popover.taro.tsx
  src/packages/popover/popover.tsx
  src/packages/popover/types.ts
  src/packages/tour/tour.taro.tsx
  src/packages/tour/tour.tsx
  src/packages/uploader/types.ts
  src/types/fix-string-literal-union.ts
Labels: size/M, 3.x, action:review

#2986 feat: pickerview
  src/config.json
  src/packages/pickerview/__test__/__snapshots__/pickerview.spec.tsx.snap
  src/packages/pickerview/__test__/pickerview.spec.tsx
  src/packages/pickerview/demo.taro.tsx
  src/packages/pickerview/demo.tsx
  src/packages/pickerview/demos/h5/demo1.tsx
  src/packages/pickerview/demos/h5/demo2.tsx
  src/packages/pickerview/demos/h5/demo3.tsx
  src/packages/pickerview/demos/h5/demo4.tsx
  src/packages/pickerview/demos/h5/demo5.tsx
  src/packages/pickerview/demos/h5/demo6.tsx
  src/packages/pickerview/demos/h5/demo7.tsx
  src/packages/pickerview/demos/taro/demo1.tsx
  src/packages/pickerview/demos/taro/demo2.tsx
  src/packages/pickerview/demos/taro/demo3.tsx
  src/packages/pickerview/demos/taro/demo4.tsx
  src/packages/pickerview/demos/taro/demo5.tsx
  src/packages/pickerview/demos/taro/demo6.tsx
  src/packages/pickerview/demos/taro/demo7.tsx
  src/packages/pickerview/doc.en-US.md
  src/packages/pickerview/doc.md
  src/packages/pickerview/doc.taro.md
  src/packages/pickerview/doc.zh-TW.md
  src/packages/pickerview/index.taro.ts
  src/packages/pickerview/index.ts
  src/packages/pickerview/pickerroller.taro.tsx
  src/packages/pickerview/pickerroller.tsx
  src/packages/pickerview/pickerview.scss
  src/packages/pickerview/pickerview.taro.tsx
  src/packages/pickerview/pickerview.tsx
  src/packages/pickerview/types.ts
  src/packages/pickerview/utils.ts
  src/styles/variables.scss
Labels: size/XXL, 3.x, action:review

#2992 chore: ci uses pnpm@10
  .github/workflows/ci.yml
  .github/workflows/cypress.yml
  .github/workflows/realease-tag.yml
  .github/workflows/release-beta.yml
  .github/workflows/release.yml
  .github/workflows/sync-h5.yml
  .github/workflows/sync-migrate.yml
  .github/workflows/sync-taro.yml
  package.json
Labels: size/S, action:review

#2994 test: Chore publish beta
  .github/workflows/release-beta.yml
  .github/workflows/release.yml
  package.json
  scripts/build-taro.mjs
  scripts/build.mjs
  src/packages/configprovider/types.ts
Labels: size/M, 3.x, action:review

#2991 fix: remove demo conditional restrictions & update the creation process
  package.json
  scripts/create-component-mode.js
  scripts/demo.js
  scripts/harmony/update-taro-entry.js
  scripts/taro/generate-taro-pages.js
Labels: size/M, action:review

#2996 fix: throw error should not block the export of component
  src/packages/lottie/index.taro.ts
Labels: size/XS, action:review

#2995 refactor: use compatible systemInfo util API
  src/packages/avatarcropper/avatarcropper.taro.tsx
  src/packages/calendar/__tests__/__snapshots__/calendar.spec.tsx.snap
  src/packages/drag/demos/taro/demo4.tsx
  src/packages/drag/drag.taro.tsx
  src/packages/menuitem/menuitem.taro.tsx
  src/packages/pulltorefresh/pulltorefresh.taro.tsx
  src/packages/range/__test__/__snapshots__/range.spec.tsx.snap
  src/packages/sticky/sticky.taro.tsx
  src/packages/virtuallist/virtuallist.taro.tsx
  src/utils/get-system-info.ts
Labels: size/L, 2.x, action:review

#2997 fix: jdharmonycpp version and dd attribute are updated
  packages/nutui-taro-demo/config/index.js
  packages/nutui-taro-demo/package.json
  src/config.json
  src/packages/cell/demos/taro/demo3.tsx
  src/packages/navbar/demos/taro/demo3.tsx
  src/packages/resultpage/resultpage.scss
Labels: size/M, 3.x, action:merge

#2999 chore: show unadapted components for HarmonyOS in Mini Programs and H5
  README_ZH.md
  package.json
  scripts/harmony/update-taro-entry.js
Labels: size/S, 3.x, action:review

#3001 fix: badge harmony
  src/packages/badge/demos/taro/demo1.tsx
Labels: size/XS, 3.x, action:review

#3005 fix: check harmony adaptions
  src/config.json
  src/packages/avatar/demo.scss
  src/packages/avatar/demos/h5/demo1.tsx
  src/packages/avatar/demos/h5/demo2.tsx
  src/packages/avatar/demos/h5/demo3.tsx
  src/packages/avatar/demos/h5/demo4.tsx
  src/packages/avatar/demos/h5/demo5.tsx
  src/packages/avatar/demos/taro/demo1.tsx
  src/packages/avatar/demos/taro/demo2.tsx
  src/packages/avatar/demos/taro/demo3.tsx
  src/packages/avatar/demos/taro/demo4.tsx
  src/packages/avatar/demos/taro/demo5.tsx
  src/packages/hoverbutton/demos/taro/demo3.tsx
  src/packages/hoverbutton/demos/taro/demo5.tsx
  src/packages/hoverbutton/demos/taro/demo6.tsx
  src/packages/icon/demo.taro.tsx
  src/packages/icon/demos/taro/demo1.tsx
  src/packages/icon/demos/taro/demo2.tsx
  src/packages/icon/demos/taro/demo4.tsx
  src/packages/icon/demos/taro/demo5.tsx
  src/packages/icon/demos/taro/demo6.tsx
  src/packages/icon/demos/taro/demo7.tsx
  src/packages/progress/demos/taro/demo6.tsx
  src/packages/skeleton/demo.taro.tsx
  src/packages/skeleton/demo.tsx
  src/packages/skeleton/demos/h5/demo1.tsx
  src/packages/skeleton/demos/h5/demo2.tsx
  src/packages/skeleton/demos/h5/demo3.tsx
  src/packages/skeleton/demos/h5/demo4.tsx
  src/packages/skeleton/demos/h5/demo5.tsx
  src/packages/skeleton/demos/taro/demo1.tsx
  src/packages/skeleton/demos/taro/demo2.tsx
  src/packages/skeleton/demos/taro/demo3.tsx
  src/packages/skeleton/demos/taro/demo4.tsx
  src/packages/skeleton/demos/taro/demo5.tsx
  src/packages/swiper/demos/taro/demo5.tsx
  src/packages/tabbar/demo.taro.tsx
  src/packages/tabs/demos/taro/demo22.tsx
  src/packages/tabs/tabs.scss
Labels: size/L, 3.x, action:review

#3000 chore: remove rn
  .pnpmfile.cjs
  README.md
  packages/nutui-taro-demo/index.js
  packages/nutui-taro-demo/jsbundles/JDReactAPIDemos.js
  packages/nutui-taro-demo/jsbundles/JDReactAPIDemos.version
  packages/nutui-taro-demo/metro.config.js
  pnpm-lock.yaml
  src/packages/backtop/demos/taro/demo5.tsx
Labels: size/S, 3.x, action:review

#3003 fix(swiper): 设置横向轮播后，手势无法触发页面的滚动
  src/packages/calendar/__tests__/__snapshots__/calendar.spec.tsx.snap
  src/packages/swiper/swiper.scss
  src/packages/swiper/swiper.tsx
Labels: size/M, 2.x, action:review

#3008 docs(loading): 主题变量修正
  src/packages/calendar/__tests__/__snapshots__/calendar.spec.tsx.snap
  src/packages/calendar/__tests__/calendar.spec.tsx
  src/packages/loading/demos/h5/demo6.tsx
  src/packages/loading/demos/taro/demo6.tsx
Labels: size/S, 2.x

#3015 fix(Calendar): defaultvalue 为空时,渲染异常
  src/packages/calendaritem/calendaritem.tsx
Labels: size/XS, 2.x, action:review

#3016 fix(form): replace with Taro Form and add the rest property for passt…
  package.json
  packages/nutui-taro-demo/src/pages/index/index.tsx
  scripts/harmony/update-taro-entry.js
  src/packages/form/form.taro.tsx
Labels: size/M, 3.x, action:review

#2978 perf: input
  src/packages/input/input.taro.tsx
  src/packages/input/input.tsx
Labels: size/L, 3.x, action:review

#3004 fix(swiper): 设置横向轮播后，手势无法触发页面的滚动
  src/packages/swiper/swiper.scss
  src/packages/swiper/swiper.tsx
Labels: size/S, 3.x, action:review

#3021 chore: update migrate
  migrate-from-v2.md
  src/packages/backtop/doc.taro.md
Labels: size/XL, 3.x, action:review

#2990 refactor: picker
  src/config.json
  src/packages/datepicker/__test__/datepicker.spec.tsx
  src/packages/datepicker/datepicker.taro.tsx
  src/packages/datepicker/datepicker.tsx
  src/packages/datepicker/demos/h5/demo1.tsx
  src/packages/datepicker/demos/h5/demo2.tsx
  src/packages/datepicker/demos/h5/demo3.tsx
  src/packages/datepicker/demos/h5/demo4.tsx
  src/packages/datepicker/demos/h5/demo5.tsx
  src/packages/datepicker/demos/h5/demo6.tsx
  src/packages/datepicker/demos/h5/demo7.tsx
  src/packages/datepicker/demos/h5/demo8.tsx
  src/packages/datepicker/demos/taro/demo1.tsx
  src/packages/datepicker/demos/taro/demo2.tsx
  src/packages/datepicker/demos/taro/demo3.tsx
  src/packages/datepicker/demos/taro/demo4.tsx
  src/packages/datepicker/demos/taro/demo5.tsx
  src/packages/datepicker/demos/taro/demo6.tsx
  src/packages/datepicker/demos/taro/demo7.tsx
  src/packages/datepicker/demos/taro/demo8.tsx
  src/packages/form/demos/h5/demo7.tsx
  src/packages/form/demos/taro/demo7.tsx
  src/packages/picker/__tests__/picker.spec.tsx
  src/packages/picker/demos/h5/demo1.tsx
  src/packages/picker/demos/h5/demo2.tsx
  src/packages/picker/demos/h5/demo3.tsx
  src/packages/picker/demos/h5/demo4.tsx
  src/packages/picker/demos/h5/demo5.tsx
  src/packages/picker/demos/h5/demo6.tsx
  src/packages/picker/demos/h5/demo7.tsx
  src/packages/picker/demos/h5/demo8.tsx
  src/packages/picker/demos/taro/demo1.tsx
  src/packages/picker/demos/taro/demo2.tsx
  src/packages/picker/demos/taro/demo3.tsx
  src/packages/picker/demos/taro/demo4.tsx
  src/packages/picker/demos/taro/demo5.tsx
  src/packages/picker/demos/taro/demo6.tsx
  src/packages/picker/demos/taro/demo7.tsx
  src/packages/picker/demos/taro/demo8.tsx
  src/packages/picker/index.taro.ts
  src/packages/picker/index.ts
  src/packages/picker/picker.scss
  src/packages/picker/picker.taro.tsx
  src/packages/picker/picker.tsx
  src/packages/picker/pickerpanel.taro.tsx
  src/packages/picker/pickerpanel.tsx
  src/packages/picker/types.ts
  src/packages/pickerview/__test__/pickerview.spec.tsx
  src/packages/pickerview/doc.en-US.md
  src/packages/pickerview/doc.md
  src/packages/pickerview/doc.taro.md
  src/packages/pickerview/doc.zh-TW.md
  src/packages/pickerview/index.taro.ts
  src/packages/pickerview/index.ts
  src/packages/pickerview/pickerroller.taro.tsx
  src/packages/pickerview/pickerroller.tsx
  src/packages/pickerview/pickerview.taro.tsx
  src/packages/pickerview/pickerview.tsx
  src/packages/pickerview/types.ts
Labels: size/XXL, 3.x, action:review

#3025 fix: picker的onchange修改popover demo同步更新
  src/packages/popover/demos/h5/demo4-1.tsx
  src/packages/popover/demos/h5/demo4.tsx
  src/packages/popover/demos/taro/demo4-1.tsx
  src/packages/popover/demos/taro/demo4.tsx
Labels: size/L, 3.x, action:review

#3028 chore: upgrade the jdharmonycpp version
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
Labels: size/XS, 3.x, action:review

#3024 docs: correct demoBlock src error
  src/packages/indicator/doc.taro.md
  src/packages/pickerview/doc.taro.md
  src/packages/popover/doc.taro.md
  src/packages/segmented/doc.taro.md
Labels: size/S, 3.x, action:review

#3018 docs: correct docs mistakes
  src/packages/space/doc.md
  src/packages/space/doc.taro.md
  src/packages/tour/doc.en-US.md
  src/packages/tour/doc.md
  src/packages/tour/doc.taro.md
  src/packages/tour/doc.zh-TW.md
  src/packages/uploader/doc.en-US.md
  src/packages/uploader/doc.md
  src/packages/uploader/doc.taro.md
  src/packages/uploader/doc.zh-TW.md
Labels: size/M, 3.x, action:review

#3020 chore(themes): output multiple themes
  scripts/build-taro.mjs
  scripts/build.mjs
  scripts/replace-css-var.js
  src/packages/configprovider/doc.en-US.md
  src/packages/configprovider/doc.md
  src/packages/configprovider/doc.taro.md
  src/packages/configprovider/doc.zh-TW.md
  src/styles/theme-dark.scss
  src/styles/theme-default.scss
Labels: size/L, 3.x, action:review

#3023 refactor: datepicker
  src/packages/calendar/demos/h5/demo6.tsx
  src/packages/calendar/demos/taro/demo6.tsx
  src/packages/datepicker/__test__/datepicker.spec.tsx
  src/packages/datepicker/datepicker.taro.tsx
  src/packages/datepicker/datepicker.tsx
  src/packages/datepicker/demos/h5/demo1.tsx
  src/packages/datepicker/demos/h5/demo2.tsx
  src/packages/datepicker/demos/h5/demo8.tsx
  src/packages/datepicker/demos/taro/demo1.tsx
  src/packages/datepicker/demos/taro/demo2.tsx
  src/packages/datepicker/demos/taro/demo8.tsx
  src/packages/datepicker/doc.en-US.md
  src/packages/datepicker/doc.md
  src/packages/datepicker/doc.taro.md
  src/packages/datepicker/doc.zh-TW.md
  src/packages/datepicker/index.taro.ts
  src/packages/datepicker/index.ts
  src/packages/datepicker/types.taro.ts
  src/packages/datepicker/types.ts
  src/packages/datepicker/utils.ts
  src/packages/form/demos/h5/demo7.tsx
  src/packages/form/demos/taro/demo7.tsx
  src/packages/picker/__tests__/picker.spec.tsx
  src/packages/picker/index.taro.ts
  src/packages/picker/index.ts
  src/packages/picker/picker.taro.tsx
  src/packages/picker/picker.tsx
  src/packages/picker/types.taro.ts
  src/packages/picker/types.ts
Labels: size/XXL, 3.x, action:review

#3030 fix: correct some docs content
  src/packages/card/doc.en-US.md
  src/packages/card/doc.md
  src/packages/card/doc.taro.md
  src/packages/card/doc.zh-TW.md
  src/packages/collapse/doc.en-US.md
  src/packages/collapse/doc.md
  src/packages/collapse/doc.taro.md
  src/packages/collapse/doc.zh-TW.md
  src/packages/sticky/doc.taro.md
Labels: size/S, 3.x, action:review

#3031 fix: configprovider docs
  src/packages/configprovider/demo.taro.tsx
  src/packages/configprovider/doc.taro.md
Labels: size/S, 3.x, action:review

#3033 fix: popup 鸿蒙适配弹出时退出app的问题
  src/packages/popup/popup.taro.tsx
Labels: size/XS, 3.x, action:review

#3002 fix: harmony review
  package.json
  pnpm-lock.yaml
  src/packages/button/button.scss
  src/packages/button/demos/taro/demo4.tsx
  src/packages/button/demos/taro/demo5.tsx
  src/packages/checkbox/__test__/__snapshots__/checkbox.spec.tsx.snap
  src/packages/checkbox/__test__/checkbox.spec.tsx
  src/packages/checkbox/checkbox.scss
  src/packages/checkbox/checkbox.taro.tsx
  src/packages/checkbox/checkbox.tsx
  src/packages/checkbox/demos/h5/demo15.tsx
  src/packages/checkbox/demos/taro/demo1.tsx
  src/packages/checkbox/demos/taro/demo15.tsx
  src/packages/checkbox/demos/taro/demo6.tsx
  src/packages/checkboxgroup/checkboxgroup.scss
  src/packages/checkboxgroup/checkboxgroup.taro.tsx
  src/packages/icon/doc.en-US.md
  src/packages/icon/doc.md
  src/packages/icon/doc.taro.md
  src/packages/icon/doc.zh-TW.md
  src/packages/indicator/demos/taro/demo1.tsx
  src/packages/indicator/demos/taro/demo2.tsx
  src/packages/indicator/demos/taro/demo4.tsx
  src/packages/indicator/indicator.scss
  src/packages/indicator/indicator.taro.tsx
  src/packages/input/doc.en-US.md
  src/packages/input/doc.md
  src/packages/input/doc.taro.md
  src/packages/input/doc.zh-TW.md
  src/packages/input/input.scss
  src/packages/loading/demos/taro/demo4.tsx
  src/packages/loading/demos/taro/demo7.tsx
  src/packages/loading/demos/taro/demo8.tsx
  src/packages/loading/loading.scss
  src/packages/navbar/demos/taro/demo1.tsx
  src/packages/navbar/demos/taro/demo2.tsx
  src/packages/numberkeyboard/numberkeyboard.taro.tsx
  src/packages/radio/demos/h5/demo7.tsx
  src/packages/radio/demos/taro/demo7.tsx
  src/packages/radio/radio.scss
  src/packages/radiogroup/radiogroup.scss
  src/packages/searchbar/demos/taro/demo3.tsx
  src/packages/searchbar/demos/taro/demo5.tsx
  src/packages/searchbar/searchbar.taro.tsx
  src/packages/searchbar/searchbar.tsx
  src/styles/variables-jmapp.scss
  src/styles/variables-jrkf.scss
  src/styles/variables.scss
Labels: size/XL, 3.x, action:review

#3032 fix: 修订dialog 被盖住、height无法撑开、纵向布局footer 样式问题等。
  src/packages/dialog/dialog.scss
  src/packages/dialog/dialog.taro.tsx
  src/packages/dialog/dialog.tsx
Labels: size/L, 3.x, action:review
