Repository jdf2e/nutui-react, pull requests merged in 2025-06, with the labels that each got.

#3210 fix(elevator): v15 适配 & 选中值支持受控
  src/packages/address/__test__/__snapshots__/address.spec.tsx.snap
  src/packages/elevator/__tests__/elevator.spec.tsx
  src/packages/elevator/demo.tsx
  src/packages/elevator/demos/h5/demo1.tsx
  src/packages/elevator/demos/h5/demo3.tsx
  src/packages/elevator/demos/h5/demo4.tsx
  src/packages/elevator/demos/h5/demo5.tsx
  src/packages/elevator/demos/taro/demo1.tsx
  src/packages/elevator/demos/taro/demo3.tsx
  src/packages/elevator/demos/taro/demo4.tsx
  src/packages/elevator/demos/taro/demo5.tsx
  src/packages/elevator/doc.en-US.md
  src/packages/elevator/doc.md
  src/packages/elevator/doc.taro.md
  src/packages/elevator/doc.zh-TW.md
  src/packages/elevator/elevator.scss
  src/packages/elevator/elevator.taro.tsx
  src/packages/elevator/elevator.tsx
  src/packages/elevator/index.taro.ts
  src/packages/elevator/index.ts
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
  src/styles/variables-jmapp.scss
  src/styles/variables-jrkf.scss
  src/styles/variables.scss
  src/types/spec/elevator/base.ts
Labels: size/XXL, 3.x, action:review

#3258 fix(navbar): 支持background的配置,补充了部分demo
  src/packages/navbar/demos/h5/demo1.tsx
  src/packages/navbar/demos/h5/demo2.tsx
  src/packages/navbar/demos/h5/demo3.tsx
  src/packages/navbar/demos/taro/demo1.tsx
  src/packages/navbar/demos/taro/demo2.tsx
  src/packages/navbar/demos/taro/demo3.tsx
  src/packages/navbar/doc.en-US.md
  src/packages/navbar/doc.md
  src/packages/navbar/doc.taro.md
  src/packages/navbar/doc.zh-TW.md
  src/packages/navbar/navbar.scss
  src/styles/variables.scss
Labels: size/L, 3.x, action:review

#3255 fix(tabs): correct tabpane-background-color css variables
  src/packages/tabpane/tabpane.scss
  src/packages/tabs/doc.en-US.md
  src/packages/tabs/doc.md
  src/packages/tabs/doc.taro.md
  src/packages/tabs/doc.zh-TW.md
  src/styles/variables-jmapp.scss
  src/styles/variables-jrkf.scss
  src/styles/variables.scss
Labels: size/S, 3.x, action:review

#3266 fix(input): handleBlur callback value is undefined in mini-programs
  src/packages/input/input.taro.tsx
Labels: size/XS, 3.x, action:review

#3265 fix(datepicker): 解决未传默认值时限制时间边界不准确问题
  src/packages/datepicker/utils.ts
Labels: size/XS, 3.x, action:review

#3257 chore(site): adjust online debugging visibility
  src/sites/sites-react/doc/components/demoblock/demoblock.tsx
Labels: size/S, 3.x, action:review

#3263 feat(image): support custom error state class name
  src/packages/image/__test__/__snapshots__/image.spec.tsx.snap
  src/packages/image/image.taro.tsx
  src/packages/image/image.tsx
Labels: size/L, 3.x, action:review

#3278 fix(pickerview): 修改快速滚动偶现滑动错位问题
  src/packages/pickerview/pickerroller.taro.tsx
Labels: size/S, 3.x, action:review

#3279 fix(button): 禁用样式修订
  src/packages/button/button.scss
Labels: size/XS, 3.x, action:review

#3228 fix(form): setFieldValue与setFieldsValue 重复触发notifyWatch
  src/packages/form/useform.ts
Labels: size/XS, 2.x, action:review

#3262 fix(overlay): 移除overlay-zIndex，避免zIndex props具备默认值导致css变量无效的使用困惑
  src/packages/overlay/doc.en-US.md
  src/packages/overlay/doc.md
  src/packages/overlay/doc.taro.md
  src/packages/overlay/doc.zh-TW.md
  src/packages/overlay/overlay.scss
  src/styles/variables.scss
Labels: size/XS, 3.x, action:review

#3280 fix(form): label无法修改字号
  src/packages/form/doc.en-US.md
  src/packages/form/doc.md
  src/packages/form/doc.taro.md
  src/packages/form/doc.zh-TW.md
  src/packages/formitem/formitem.scss
  src/styles/variables.scss
Labels: size/S, 3.x, action:review

#3283 fix(form): 修复右侧星星无法展示的问题
  src/packages/form/demos/h5/demo2.tsx
  src/packages/form/demos/taro/demo2.tsx
  src/packages/formitem/formitem.scss
  src/packages/formitem/formitem.taro.tsx
  src/packages/formitem/formitem.tsx
Labels: size/M, 3.x, action:review

#3285 feat(calendarcard): 增加自定义头
  src/packages/calendarcard/calendarcard.taro.tsx
  src/packages/calendarcard/calendarcard.tsx
  src/packages/calendarcard/demo.taro.tsx
  src/packages/calendarcard/demo.tsx
  src/packages/calendarcard/demos/h5/demo12.tsx
  src/packages/calendarcard/demos/taro/demo12.tsx
  src/packages/calendarcard/doc.en-US.md
  src/packages/calendarcard/doc.md
  src/packages/calendarcard/doc.taro.md
  src/packages/calendarcard/doc.zh-TW.md
  src/types/spec/calendarcard/base.ts
Labels: size/L, 3.x, action:review

#3249 fix(noticebar): first item is not visible when scrolling vertically
  src/packages/noticebar/__test__/noticebar.spec.tsx
  src/packages/noticebar/noticebar.taro.tsx
  src/packages/noticebar/noticebar.tsx
Labels: size/M, 3.x, action:review

#3282 feat(dialog): close和cancel各司其职
  src/packages/dialog/__test__/dialog.spec.tsx
  src/packages/dialog/demos/h5/demo2.tsx
  src/packages/dialog/demos/h5/demo6.tsx
  src/packages/dialog/dialog.taro.tsx
  src/packages/dialog/dialog.tsx
Labels: size/M, 3.x, action:review

#3287 fix(configprovider): 修订路径别名
  packages/nutui-taro-demo/config/index.js
  src/packages/configprovider/types.ts
  vite.config.demo.ts
  vite.config.mts
Labels: size/XS, 3.x, action:review

#3251 fix(noticebar): children cannot update responsively in vertical mode
  src/packages/noticebar/__test__/noticebar.spec.tsx
  src/packages/noticebar/demo.taro.tsx
  src/packages/noticebar/demo.tsx
  src/packages/noticebar/demos/h5/demo10.tsx
  src/packages/noticebar/demos/taro/demo10.tsx
  src/packages/noticebar/doc.en-US.md
  src/packages/noticebar/doc.md
  src/packages/noticebar/doc.taro.md
  src/packages/noticebar/doc.zh-TW.md
  src/packages/noticebar/noticebar.taro.tsx
  src/packages/noticebar/noticebar.tsx
Labels: size/L, 3.x, action:review
