Repository jdf2e/nutui-react, pull requests merged in 2025-05, with the labels that each got.

#3220 fix(address): 构建单一样式文件
  scripts/build-taro.mjs
  scripts/replace-css-var.js
  src/packages/address/address.scss
  src/packages/address/elevator.scss
Labels: size/L, 3.x, action:review

#3223 fix(uploader): 多端上传媒体文件逻辑与2x保持一致
  src/packages/uploader/uploader.taro.tsx
Labels: size/XS, 3.x, action:review

#3202 feat(progress): 兼容并支持taro components的progressProps & v15适配
  src/packages/progress/__tests__/__snapshots__/progress.spec.tsx.snap
  src/packages/progress/__tests__/progress.spec.tsx
  src/packages/progress/demo.taro.tsx
  src/packages/progress/demo.tsx
  src/packages/progress/demos/h5/demo4.tsx
  src/packages/progress/demos/h5/demo9.tsx
  src/packages/progress/demos/taro/demo4.tsx
  src/packages/progress/demos/taro/demo9.tsx
  src/packages/progress/doc.en-US.md
  src/packages/progress/doc.md
  src/packages/progress/doc.taro.md
  src/packages/progress/doc.zh-TW.md
  src/packages/progress/progress.scss
  src/packages/progress/progress.taro.tsx
  src/packages/progress/progress.tsx
  src/styles/variables.scss
  src/types/spec/progress/base.ts
  src/types/spec/progress/taro.ts
Labels: size/XL, 3.x, action:review

#3219 fix(uploader): beforeUpload failed to work
  src/packages/uploader/__tests__/uploader.spec.tsx
  src/packages/uploader/demos/h5/demo1.tsx
  src/packages/uploader/uploader.taro.tsx
  src/packages/uploader/uploader.tsx
Labels: size/M, 3.x, action:review

#3216 refactor(steps): v15
  src/config.json
  src/packages/step/step.scss
  src/packages/step/step.taro.tsx
  src/packages/step/step.tsx
  src/packages/steps/__tests__/steps.spec.tsx
  src/packages/steps/demo.taro.tsx
  src/packages/steps/demo.tsx
  src/packages/steps/demos/h5/demo1.tsx
  src/packages/steps/demos/h5/demo2.tsx
  src/packages/steps/demos/h5/demo3.tsx
  src/packages/steps/demos/h5/demo4.tsx
  src/packages/steps/demos/h5/demo5.tsx
  src/packages/steps/demos/h5/demo6.tsx
  src/packages/steps/demos/h5/demo7.tsx
  src/packages/steps/demos/h5/demo8.tsx
  src/packages/steps/demos/h5/demo9.tsx
  src/packages/steps/demos/taro/demo1.tsx
  src/packages/steps/demos/taro/demo2.tsx
  src/packages/steps/demos/taro/demo3.tsx
  src/packages/steps/demos/taro/demo4.tsx
  src/packages/steps/demos/taro/demo5.tsx
  src/packages/steps/demos/taro/demo6.tsx
  src/packages/steps/demos/taro/demo7.tsx
  src/packages/steps/demos/taro/demo8.tsx
  src/packages/steps/demos/taro/demo9.tsx
  src/packages/steps/doc.en-US.md
  src/packages/steps/doc.md
  src/packages/steps/doc.taro.md
  src/packages/steps/doc.zh-TW.md
  src/packages/steps/steps.scss
  src/packages/steps/steps.taro.tsx
  src/packages/steps/steps.tsx
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
  src/styles/variables-jmapp.scss
  src/styles/variables-jrkf.scss
  src/styles/variables.scss
  src/types/spec/steps/base.ts
Labels: size/XXL, 3.x, action:review

#3217 feat(range): 鸿蒙适配,修订NaN,纵向mark时异常问题
  src/packages/range/__test__/__snapshots__/range.spec.tsx.snap
  src/packages/range/demos/taro/demo11.tsx
  src/packages/range/range.scss
  src/packages/range/range.taro.tsx
  src/packages/range/range.tsx
  src/packages/range/utils.tsx
Labels: size/L, 3.x, action:review

#3225 feat(Swiper): 修订autoplay属性,并在taro版本上对齐了tc属性值
  src/packages/swiper/__tests__/swiper.spec.tsx
  src/packages/swiper/demos/h5/demo1.tsx
  src/packages/swiper/demos/taro/demo1.tsx
  src/packages/swiper/demos/taro/demo5.tsx
  src/packages/swiper/demos/taro/demo7.tsx
  src/packages/swiper/demos/taro/demo8.tsx
  src/packages/swiper/demos/taro/demo9.tsx
  src/packages/swiper/doc.en-US.md
  src/packages/swiper/doc.md
  src/packages/swiper/doc.taro.md
  src/packages/swiper/doc.zh-TW.md
  src/packages/swiper/swiper.taro.tsx
  src/packages/swiper/swiper.tsx
  src/sites/sites-react/doc/docs/react/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
  src/types/spec/swiper/base.ts
  src/types/spec/swiper/taro.ts
Labels: size/L, 3.x, action:merge

#3232 fix(configprovider): 调整demo展示
  src/packages/configprovider/demo.taro.tsx
  src/packages/configprovider/demo.tsx
  src/packages/configprovider/demos/h5/demo1.tsx
  src/packages/configprovider/demos/h5/demo2.tsx
  src/packages/configprovider/demos/h5/demo3.tsx
  src/packages/configprovider/demos/h5/demo4.tsx
  src/packages/configprovider/demos/h5/demo5.tsx
  src/packages/configprovider/demos/taro/demo1.tsx
  src/packages/configprovider/demos/taro/demo2.tsx
  src/packages/configprovider/demos/taro/demo3.tsx
  src/packages/configprovider/demos/taro/demo4.tsx
  src/packages/configprovider/demos/taro/demo5.tsx
  src/packages/configprovider/doc.en-US.md
  src/packages/configprovider/doc.md
  src/packages/configprovider/doc.taro.md
  src/packages/configprovider/doc.zh-TW.md
Labels: size/L, 3.x, action:review

#3233 fix(textarea): 修订没有写placeholder时无法展示默认值的情况
  src/packages/textarea/__test__/__snapshots__/textarea.spec.tsx.snap
  src/packages/textarea/textarea.taro.tsx
  src/packages/textarea/textarea.tsx
Labels: size/XS, 3.x, action:review

#3229 feat(Textarea): 增加 ref 属性
  src/packages/input/doc.en-US.md
  src/packages/input/doc.md
  src/packages/input/doc.taro.md
  src/packages/input/doc.zh-TW.md
  src/packages/input/input.taro.tsx
  src/packages/input/input.tsx
  src/packages/textarea/doc.en-US.md
  src/packages/textarea/doc.md
  src/packages/textarea/doc.taro.md
  src/packages/textarea/doc.zh-TW.md
  src/packages/textarea/textarea.taro.tsx
  src/packages/textarea/textarea.tsx
  src/sites/sites-react/doc/docs/react/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/react/migrate-from-v2.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.en-US.md
  src/sites/sites-react/doc/docs/taro/migrate-from-v2.md
Labels: size/L, 3.x, action:review

#3237 feat(lottie): 支持显示设置 dpr 设置宽高
  src/packages/lottie/doc.taro.md
  src/packages/lottie/lottiemp.taro.tsx
  src/types/spec/lottie/taro.ts
Labels: size/S, 3.x, action:review

#3239 fix(uploader): 修复官网蒙层层级、demo中ListItem类型的引入并更新文档
  src/packages/uploader/demos/h5/demo1.tsx
  src/packages/uploader/demos/h5/demo10.tsx
  src/packages/uploader/demos/h5/demo2.tsx
  src/packages/uploader/demos/h5/demo3.tsx
  src/packages/uploader/demos/h5/demo4.tsx
  src/packages/uploader/demos/h5/demo5.tsx
  src/packages/uploader/demos/h5/demo7.tsx
  src/packages/uploader/demos/taro/demo1.tsx
  src/packages/uploader/demos/taro/demo10.tsx
  src/packages/uploader/demos/taro/demo2.tsx
  src/packages/uploader/demos/taro/demo3.tsx
  src/packages/uploader/demos/taro/demo4.tsx
  src/packages/uploader/demos/taro/demo5.tsx
  src/packages/uploader/demos/taro/demo7.tsx
  src/packages/uploader/doc.taro.md
  src/packages/uploader/uploader.scss
Labels: size/M, 3.x, action:review

#3230 fix(pickerview): 高度获取失败兜底值变更
  src/packages/pickerview/pickerroller.taro.tsx
Labels: size/XS, 3.x, action:review

#3235 fix(input): 不需要加 get 属性的，用 nativeElement 就可了
  src/packages/input/doc.en-US.md
  src/packages/input/doc.md
  src/packages/input/doc.taro.md
  src/packages/input/doc.zh-TW.md
  src/packages/input/input.taro.tsx
  src/packages/input/input.tsx
Labels: size/M, 3.x, action:review

#3241 fix: 适配td
  src/packages/address/address.scss
  src/packages/avatar/avatar.taro.tsx
  src/packages/avatar/demos/taro/demo4.tsx
  src/packages/avatar/demos/taro/demo6.tsx
  src/packages/avatar/demos/taro/demo7.tsx
  src/packages/button/button.scss
  src/packages/collapseitem/collapseitem.scss
  src/packages/dialog/dialog.scss
  src/packages/icon/demos/camel-case.ts
  src/packages/icon/demos/h5/demo6.tsx
  src/packages/icon/demos/h5/demo7.tsx
  src/packages/icon/demos/taro/demo6.tsx
  src/packages/icon/demos/taro/demo7.tsx
  src/packages/indicator/demo.taro.tsx
  src/packages/indicator/demos/taro/demo4.tsx
  src/packages/loading/loading.taro.tsx
  src/packages/numberkeyboard/numberkeyboard.scss
  src/packages/pagination/demos/taro/demo5.tsx
  src/packages/pagination/pagination.taro.tsx
  src/packages/skeleton/demos/taro/demo4.tsx
  src/packages/steps/steps.scss
  src/packages/tabbaritem/tabbaritem.scss
  src/packages/tabs/tabs.scss
  src/packages/toast/toast.scss
  src/utils/index.taro.ts
  src/utils/index.ts
  src/utils/taro/platform.ts
  src/utils/taro/px-transform.ts
Labels: size/L, 3.x, action:review

#3243 fix(price): 适配td
  src/packages/price/price.scss
Labels: size/XS, 3.x, action:review
